### ISSUE TITLE
I cannot ingest documents

### ISSUE THREAD

**Issue by knminhaz** [PromtEngineer/localGPT#101]
I have installed the resquirements.txt
Upon running the python ingest.py command, I get the following error:

python ingest.py 
Loading documents from /home/computer/Downloads/localGPT-main/SOURCE_DOCUMENTS
Loaded 1 documents from /home/computer/Downloads/localGPT-main/SOURCE_DOCUMENTS
Split into 72 chunks of text
Traceback (most recent call last):
  File "/home/computer/.local/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 135, in __init__
    from InstructorEmbedding import INSTRUCTOR
  File "/home/computer/.local/lib/python3.10/site-packages/InstructorEmbedding/__init__.py", line 1, in <module>
    from .instructor import *
  File "/home/computer/.local/lib/python3.10/site-packages/InstructorEmbedding/instructor.py", line 9, in <module>
    from sentence_transformers import SentenceTransformer
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/computer/Downloads/localGPT-main/ingest.py", line 78, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/computer/Downloads/localGPT-main/ingest.py", line 69, in main
    embeddings = HuggingFaceInstructEmbeddings(model_name="hkunlp/instructor-xl",
  File "/home/computer/.local/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 141, in __init__
    raise ValueError("Dependencies for InstructorEmbedding not found.") from e
ValueError: Dependencies for InstructorEmbedding not found.

Any idea?

**Comment by Rezzemy** [comment]
Heyo,

I think JaxLib doesn't actually have an official Windows variant - pretty sure it's mainly used on Linux/Mac. But you should be able to build the package by installing these files through command line or other methods (i provided a command line copy paste):


py -m pip install jax==0.3.13 https://whls.blob.core.windows.net/unstable/cuda111/jaxlib-0.3.7+cuda11.cudnn82-cp39-none-win_amd64.whl

There could be a version mismatch, but it's worth a try! The .whl file contains the precompiled Windows version of JaxLib.

**Comment by knminhaz** [comment]
I am using Arch linux and not windows

**Comment by dimohamdy** [comment]
@knminhaz Did you find a solution?

**Comment by manuelrech** [comment]
pip install instructorembeddings sentence-transformers

**Comment by Yyote** [comment]
> pip install instructorembeddings sentence-transformers

ERROR: Could not find a version that satisfies the requirement instructorembeddings (from versions: none)
ERROR: No matching distribution found for instructorembeddings

And still doesn't ingest

**Comment by JohnOstrowick** [comment]
you  need pip install InstructorEmbedding with capital letters.

**Comment by Metassive** [comment]
The same thing happens here, whether you type `pip install instructorembeddings sentence-transformers` or `pip install InstructorEmbeddings sentence-transformers` appears this:

```
ERROR: Could not find a version that satisfies the requirement instructorembeddings (from versions: none)
ERROR: No matching distribution found for instructorembeddings
```

Another suggestion?

**Comment by JohnOstrowick** [comment]
Great I think that will help future readers of this page. Thanks for sharing.

**Comment by TinoCoda** [comment]
I'm still facing the same issue currently. I'll follow your instructions and let you know if it fixes the problem.
