### ISSUE TITLE
Problem using TheBloke/Vigogne-Instruct-13B-GPTQ model

### ISSUE THREAD

**Issue by orochvilato** [PromtEngineer/localGPT#161]
Hi !

I'm trying to use your fantastic piece of software with this model https://huggingface.co/TheBloke/Vigogne-Instruct-13B-GPTQ

I've set 
model_id = "TheBloke/Vigogne-Instruct-13B-GPTQ"
model_basename = "Vigogne-Instruct-13B-GPTQ-4bit-128g.no-act-order.safetensors"
in run_localGPT.py
but i've got an error :

```
2023-06-18` 10:59:56,492 - INFO - run_localGPT.py:98 - Tokenizer loaded
Traceback (most recent call last):
  File "/home/olivier/devs/localGPT/run_localGPT.py", line 274, in <module>
    main()
  File "/home/olivier/devs/localGPT/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/olivier/devs/localGPT/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/olivier/devs/localGPT/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/olivier/devs/localGPT/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/olivier/devs/localGPT/run_localGPT.py", line 243, in main
    llm = load_model(device_type, model_id=model_id, model_basename=model_basename)
  File "/home/olivier/devs/localGPT/run_localGPT.py", line 100, in load_model
    model = AutoGPTQForCausalLM.from_quantized(
  File "/home/olivier/devs/localGPT/venv/lib/python3.10/site-packages/auto_gptq/modeling/auto.py", line 82, in from_quantized
    return quant_func(
  File "/home/olivier/devs/localGPT/venv/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 650, in from_quantized
    quantize_config = BaseQuantizeConfig.from_pretrained(model_name_or_path, **kwargs)
  File "/home/olivier/devs/localGPT/venv/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 89, in from_pretrained
    with open(resolved_config_file, "r", encoding="utf-8") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by PromtEngineer** [comment]
@orochvilato Seems like the auto_gptq package is having issues. Are you able to run any of the other quantized models?

**Comment by PromtEngineer** [comment]
@orochvilato thanks, I will close the issue.
