### ISSUE TITLE
 File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake

### ISSUE THREAD

**Issue by hai4john** [PromtEngineer/localGPT#184]
(venv) root@ecs-62c3:~/localGPT# python run_localGPT.py
2023-06-26 17:41:59,515 - INFO - run_localGPT.py:161 - Running on: cuda
2023-06-26 17:41:59,515 - INFO - run_localGPT.py:162 - Display Source Documents set to: False
2023-06-26 17:41:59,653 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
Traceback (most recent call last):
  File "/root/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/root/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/root/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/root/venv/lib/python3.10/site-packages/urllib3/connection.py", line 342, in connect
    self.sock = ssl_wrap_socket(
  File "/root/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 356, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

**Comment by PromtEngineer** [comment]
@hai4john its not a localGPT issue. Seems like your `ssl` package is having connection issues.

**Comment by hai4john** [comment]
Yes, I just want to know if anyone has encountered the same problem and what solutions are available

> @hai4john its not a localGPT issue. Seems like your `ssl` package is having connection issues.

**Comment by hai4john** [comment]
reopen

**Comment by hai4john** [comment]
Fix according to the link
https://stackoverflow.com/questions/71692354/facing-ssl-error-with-huggingface-pretrained-models
