### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by SprigWave** [PromtEngineer/localGPT#191]
I have successfully installed all the requirements with `pip install -r requirements.txt` and upon running `python run_localGPT_API.py` I get the following output:
`load INSTRUCTOR_Transformer
max_seq_length  512
The directory does not exist
Traceback (most recent call last):
  File "C:\Users\sprig\Downloads\localGPT\run_localGPT_API.py", line 53, in <module>
    raise FileNotFoundError(
FileNotFoundError: No files were found inside SOURCE_DOCUMENTS, please put a starter file inside before starting the API!`
I am confused as to what this means seeing as I have a SOURCE_DOCUMENTS folder that contains the constituion PDF provided and two news article .txt files from the zip archive. How would I fix this issue?

**Comment by teleprint-me** [comment]
Hi @SprigWave,

Your issue appears to be related to a directory path issue. The `run_localGPT_API.py` script is attempting to locate the `SOURCE_DOCUMENTS` directory, and isn't able to find it. Even if you have this directory in your project, you might be executing the script from a different location, which could be causing this issue.

Please make sure you are executing the script from the root directory of the project, because the paths are relative to the location where you run the script from.

If you're certain that you are running the script from the correct location, another possibility could be that the path specified in the script might not be accurate. I would suggest reviewing the script to ensure that the path to the `SOURCE_DOCUMENTS` directory is correct.

Feel free to provide any further information if you continue to face the issue. We're here to help!

**Comment by DeutscheGabanna** [comment]
> Please make sure you are executing the script from the root directory of the project

```
ls
    Directory: C:\Users\Paul\Documents\localGPT\localGPT
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        22.06.2023     16:59                .github
d-----        30.06.2023     07:45                DB
d-----        22.06.2023     16:59                localGPTUI
d-----        30.06.2023     07:10                SOURCE_DOCUMENTS
d-----        30.06.2023     07:44                __pycache__
-a----        22.06.2023     16:59            280 .editorconfig
-a----        22.06.2023     16:59             71 .flake8
-a----        22.06.2023     16:59           3271 .gitignore
-a----        22.06.2023     16:59           1085 .pre-commit-config.yaml
-a----        22.06.2023     16:59            378 .pyup.yml
-a----        22.06.2023     16:59            436 ACKNOWLEDGEMENT.md
-a----        30.06.2023     07:44           1388 constants.py
-a----        22.06.2023     16:59           2074 CONTRIBUTING.md
-a----        22.06.2023     16:59           5241 ingest.py
-a----        22.06.2023     16:59          11558 LICENSE
-a----        22.06.2023     16:59            225 pyproject.toml
-a----        22.06.2023     16:59          12214 README.md
-a----        25.06.2023     22:36            533 requirements.txt
-a----        22.06.2023     16:59           8310 run_localGPT.py
-a----        30.06.2023     07:26           9557 run_localGPT_API.py
-a----        22.06.2023     16:59           3752 xlxs_loader.py
```

> another possibility could be that the path specified in the script might not be accurate

```
>>> os.path.dirname(os.path.realpath(r'C:\Users\Paul\Documents\localGPT\localGPT\constants.py'))+r'\SOURCE_DOCUMENTS'
'C:\\Users\\Paul\\Documents\\localGPT\\localGPT\\SOURCE_DOCUMENTS'
```

and

```
>>> os.path.exists(r'C:\Users\Paul\Documents\localGPT\localGPT\SOURCE_DOCUMENTS')
True
```

I am lost for ideas what to do.

**Comment by shiliu2023** [comment]
I same

**Comment by teleprint-me** [comment]
Is the sample pdf inside of the documents folder? It's expecting input from that path (you don't need to specify the file, just the path).

**Comment by DeutscheGabanna** [comment]
Thank you so much for responding to our issue. Unfortunately no, at least not in my case - it does not resolve it.
Just to clear up any misunderstanding - your repo `localGPT` is cloned inside a folder called `localGPT`, so in order to be in the correct path, I need to be here:
```
C:\Users\Paul\Documents\localGPT\localGPT
```
I changed L10 as you said, but it did not have any impact on the issue.

**Comment by teleprint-me** [comment]
Are you inside the root directory when you execute?

e.g.

```sh
cd C:\Users\Paul\Documents\localGPT
python ingest.py
```

**Comment by DeutscheGabanna** [comment]
> Also, do you mean @PromtEngineer main branch or my dev branch?
I'm on main.

> Are you inside the root directory when you execute?
Yes

**Comment by teleprint-me** [comment]
@SprigWave @DeutscheGabanna @shiliu2023 

Thank you for your patience and cooperation. I understand that troubleshooting can sometimes be a bit challenging. Let's try to resolve this issue together.

Firstly, I would like to confirm that I am using the latest commit from the `main` branch. Here's the output from my terminal:

```sh
002b715 (HEAD -> main, origin/main, origin/HEAD) Merge pull request #200 from karthikcs/kar_docs
```

I am running the code on a Linux system, and unfortunately, I don't have access to a Windows or Mac OS X machine for testing. However, I believe we can still find a solution.

When I run the `ingest.py` script from the root directory of the project (`/home/austin/Documents/code/git/localGPT`), it successfully loads the documents from the `SOURCE_DOCUMENTS` directory. Here's the output:

```sh
python ingest.py
2023-07-08 12:18:00,926 - INFO - ingest.py:120 - Loading documents from /home/austin/Documents/code/git/localGPT/SOURCE_DOCUMENTS
2023-07-08 12:18:00,932 - INFO - ingest.py:33 - Loading document batch
2023-07-08 12:18:02,037 - INFO - ingest.py:129 - Loaded 1 documents from /home/austin/Documents/code/git/localGPT/SOURCE_DOCUMENTS
2023-07-08 12:18:02,038 - INFO - ingest.py:130 - Split into 72 chunks of text
...
```

The `SOURCE_DOCUMENTS` directory exists in the root path of the repository and contains the `constitution.pdf` file:

```sh
tree SOURCE_DOCUMENTS 
SOURCE_DOCUMENTS
└── constitution.pdf
```

If you are not using the latest commit, please update your local repository by pulling the latest changes from the `main` branch:

```sh
git pull origin main
```

After updating your repository, please ensure the following:

1. You are in the root path of the repository when running the script.
2. The `SOURCE_DOCUMENTS` directory exists in the root path of the repository.
3. The `constitution.pdf` file is present in the `SOURCE_DOCUMENTS` directory.

Then, try running the script again. If the issue persists, please let me know. I'm here to help.

I am, unfortunately, unable to reproduce the error:

```sh
13:10:52 | ~/Documents/code/git/localGPT
 git:(main | θ) λ python run_localGPT_API.py 
load INSTRUCTOR_Transformer
max_seq_length  512
Using AutoGPTQForCausalLM for quantized models
Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 727/727 [00:00<00:00, 5.79MB/s]
Downloading tokenizer.model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 4.24MB/s]
Downloading (…)/main/tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 8.93MB/s]
Downloading (…)in/added_tokens.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21.0/21.0 [00:00<00:00, 137kB/s]
Downloading (…)cial_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 96.0/96.0 [00:00<00:00, 272kB/s]
Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 552/552 [00:00<00:00, 5.19MB/s]
Downloading (…)quantize_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 57.0/57.0 [00:00<00:00, 305kB/s]
Downloading (…)ct-order.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.89G/3.89G [03:18<00:00, 19.7MB/s]
WARNING:auto_gptq.nn_modules.qlinear_old:CUDA extension not installed.
WARNING:accelerate.utils.modeling:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
WARNING:accelerate.utils.modeling:The safetensors archive passed at /home/austin/.cache/huggingface/hub/models--TheBloke--WizardLM-7B-uncensored-GPTQ/snapshots/dcb3400039f15cff76b43a4921c59d47c5fc2252/WizardLM-7B-uncensored-GPTQ-4bit-128g.compat.no-act-order.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
WARNING:auto_gptq.nn_modules.fused_llama_mlp:skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
Downloading (…)neration_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 137/137 [00:00<00:00, 964kB/s]
WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1)
    Python  3.11.3 (you have 3.11.3)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
The model 'LlamaGPTQForCausalLM' is not supported for text-generation. Supported models are ['BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'CamembertForCausalLM', 'CodeGenForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'Data2VecTextForCausalLM', 'ElectraForCausalLM', 'ErnieForCausalLM', 'GitForCausalLM', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GPTJForCausalLM', 'LlamaForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegaForCausalLM', 'MegatronBertForCausalLM', 'MvpForCausalLM', 'OpenLlamaForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'QDQBertLMHeadModel', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'RwkvForCausalLM', 'Speech2Text2ForCausalLM', 'TransfoXLLMHeadModel', 'TrOCRForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMProphetNetForCausalLM', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'XmodForCausalLM'].
 * Serving Flask app 'run_localGPT_API'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5110
INFO:werkzeug:Press CTRL+C to quit
```

You might be interested in commenting out the following statements from the API script:

```py
# uncomment the following line if you used HuggingFaceEmbeddings in the ingest.py
# EMBEDDINGS = HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL_NAME)
if os.path.exists(PERSIST_DIRECTORY):
    try:
        shutil.rmtree(PERSIST_DIRECTORY)
    except OSError as e:
        print(f"Error: {e.filename} - {e.strerror}.")
else:
    print("The directory does not exist")

run_langest_commands = ["python", "ingest.py"]
if DEVICE_TYPE == "cpu":
    run_langest_commands.append("--device_type")
    run_langest_commands.append(DEVICE_TYPE)

result = subprocess.run(run_langest_commands, capture_output=True)
if result.returncode != 0:
    raise FileNotFoundError(
        "No files were found inside SOURCE_DOCUMENTS, please put a starter file inside before starting the API!"
    )
```

You'll need to run the `ingest.py` on its own as that's where I suspect the problem is originating from.

**Comment by DeutscheGabanna** [comment]
Thanks for replying and investigating this issue with me. I appreciate all that you do to help me (and the OP).
I debugged the script and can say with certainty that Python should be able to see the file. If I step over this line:
`SOURCE_DIRECTORY = f"{ROOT_DIRECTORY}/SOURCE_DOCUMENTS"`
and add this expression to my debug watchlist:
`os.listdir(SOURCE_DIRECTORY)` it correctly resolves to: `['constitution.pdf']`

**Comment by DeutscheGabanna** [comment]
However... seeing your emoji reaction I'm afraid I was misunderstood. I said that I confirmed python sees the file by running a debug expression `os.listdir(SOURCE_DIRECTORY)`, but **it doesn't change the fact that the script itself still fails to see them**.

**Comment by teleprint-me** [comment]
@DeutscheGabanna

I'm sorry to hear that. I gave up on Windows for software development a long time ago. I daily drive Linux because I'm less frustrated as result, so I understand.

Anyways, I'm glad it's working for you now. The downside is there's still no known solution as a result. Maybe someone else will figure it out and post it here as a result.

**Comment by charles-123456** [comment]
opt/localGPT/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/opt/localGPT/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
load INSTRUCTOR_Transformer
max_seq_length  512
The directory does not exist
***DIR****
/opt/localGPT/ingest.py
***result****
CompletedProcess(args=['python', '/opt/localGPT/ingest.py'], returncode=1, stdout=b'load INSTRUCTOR_Transformer\n/opt/localGPT/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32\nmax_seq_length  512\n', stderr=b'2023-07-26 12:20:45,846 - INFO - ingest.py:120 - Loading documents from /opt/localGPT/SOURCE_DOCUMENTS\n2023-07-26 12:20:45,857 - INFO - ingest.py:33 - Loading document batch\n2023-07-26 12:20:46,291 - INFO - ingest.py:129 - Loaded 1 documents from /opt/localGPT/SOURCE_DOCUMENTS\n2023-07-26 12:20:46,291 - INFO - ingest.py:130 - Split into 4 chunks of text\n2023-07-26 12:20:49,743 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large\n/opt/localGPT/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.\n  warn("The installed version of bitsandbytes was compiled without GPU support. "\n2023-07-26 12:20:50,476 - INFO - instantiator.py:21 - Created a temporary directory at /tmp/tmpckbwuggd\n2023-07-26 12:20:50,476 - INFO - instantiator.py:76 - Writing /tmp/tmpckbwuggd/_remote_module_non_scriptable.py\n2023-07-26 12:20:55,740 - INFO - __init__.py:88 - Running Chroma using direct local API.\n2023-07-26 12:20:56,125 - WARNING - __init__.py:43 - Using embedded DuckDB with persistence: data will be stored in: /opt/localGPT/DB\n2023-07-26 12:20:56,384 - INFO - ctypes.py:22 - Successfully imported ClickHouse Connect C data optimizations\n2023-07-26 12:20:56,395 - INFO - json_impl.py:45 - Using python library for writing JSON byte strings\n2023-07-26 12:20:56,528 - INFO - duckdb.py:454 - No existing DB found in /opt/localGPT/DB, skipping load\n2023-07-26 12:20:56,528 - INFO - duckdb.py:466 - No existing DB found in /opt/localGPT/DB, skipping load\nTraceback (most recent call last):\n  File "/opt/localGPT/ingest.py", line 158, in <module>\n    main()\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__\n    return self.main(*args, **kwargs)\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main\n    rv = self.invoke(ctx)\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke\n    return __callback(*args, **kwargs)\n  File "/opt/localGPT/ingest.py", line 144, in main\n    db = Chroma.from_documents(\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 446, in from_documents\n    return cls.from_texts(\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 414, in from_texts\n    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 159, in add_texts\n    embeddings = self._embedding_function.embed_documents(list(texts))\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 158, in embed_documents\n    embeddings = self.client.encode(instruction_pairs, **self.encode_kwargs)\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/InstructorEmbedding/instructor.py", line 521, in encode\n    self.to(device)\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to\n    return self._apply(convert)\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply\n    module._apply(fn)\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply\n    module._apply(fn)\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply\n    module._apply(fn)\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply\n    param_applied = fn(param)\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert\n    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)\n  File "/opt/localGPT/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init\n    torch._C._cuda_init()\nRuntimeError: No CUDA GPUs are available\n2023-07-26 12:20:56,667 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: /opt/localGPT/DB\n')
Traceback (most recent call last):
  File "/opt/localGPT/run_localGPT_API.py", line 58, in <module>
    raise FileNotFoundError(
FileNotFoundError: No files were found inside SOURCE_DOCUMENTS, please put a starter file inside before starting the API!
(venv) chnadmin@falcon-vm:/opt/localGPT$ ^C

I got the above error, what is the mistake, I had Ubuntu 20 version and 16 GB RAM Even though the same error happened, If any help that would be appreciatable?
