### ISSUE TITLE
Can't run ni Anaconda

### ISSUE THREAD

**Issue by zokokook** [PromtEngineer/localGPT#199]
I use Anaconda to setup.

When run ingest.py, occurs the following error:

PS D:\privateGPT-main> & D:/Users/okokook/anaconda3/envs/python311/python.exe d:/localGPT-main/ingest.py
2023-06-30 20:31:25,891 - INFO - ingest.py:120 - Loading documents from D:\localGPT-main/SOURCE_DOCUMENTS
2023-06-30 20:31:29,854 - INFO - ingest.py:129 - Loaded 1 documents from D:\localGPT-main/SOURCE_DOCUMENTS
2023-06-30 20:31:29,854 - INFO - ingest.py:130 - Split into 72 chunks of text
2023-06-30 20:31:33,031 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
Traceback (most recent call last):
  File "D:\Users\okokook\anaconda3\envs\python311\Lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "D:\Users\okokook\anaconda3\envs\python311\Lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request   
    self._validate_conn(conn)
  File "D:\Users\okokook\anaconda3\envs\python311\Lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn 
    conn.connect()
  File "D:\Users\okokook\anaconda3\envs\python311\Lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "D:\Users\okokook\anaconda3\envs\python311\Lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket      
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\okokook\anaconda3\envs\python311\Lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\okokook\anaconda3\envs\python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\okokook\anaconda3\envs\python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "D:\Users\okokook\anaconda3\envs\python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

Who knows how to solve it? Thanks for your information!

**Comment by adjiap** [comment]
I don't know how to solve it, but I'm going to assume, based on the error that you don't have connection to download the HF model, as you're failing the SSL handshake...so, try a VPN?

**Comment by PromtEngineer** [comment]
@zokokook check out #184 .

**Comment by zokokook** [comment]
It has been solved by VPN

Thanks for ur concerns!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: PromptEngineer ***@***.***>
发送时间: Saturday, July 1, 2023 2:29:22 PM
收件人: PromtEngineer/localGPT ***@***.***>
抄送: zokokook ***@***.***>; Mention ***@***.***>
主题: Re: [PromtEngineer/localGPT] Can't run ni Anaconda (Issue #199)


Closed #199<https://github.com/PromtEngineer/localGPT/issues/199> as completed.

―
