### ISSUE TITLE
The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them

### ISSUE THREAD

**Issue by dportabella** [PromtEngineer/localGPT#206]
running on a virtual machine with Ubuntu 22.04.2 LTS:

```
git clone https://github.com/PromtEngineer/localGPT.git
cd localGPT
conda create --name env1 python=3.11.3
conda activate env1
conda install python=3.11.3
sudo apt-get install build-essential -y     # << this solved the "at least C++11 support is needed!"
pip install -r requirements.txt

git clone https://github.com/PanQiWei/AutoGPTQ.git
cd AutoGPTQ
git checkout v0.2.2
pip install .
cd ..

python ingest.py --device_type cpu

python run_localGPT.py

Downloading shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [11:29<00:00, 345.00s/it]
2023-07-04 06:04:31,924 - WARNING - modeling.py:706 - The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Traceback (most recent call last):
  File "/home/supervisor/localGPT/run_localGPT.py", line 232, in <module>
    main()
  File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supervisor/localGPT/run_localGPT.py", line 201, in main
    llm = load_model(device_type, model_id=model_id, model_basename=model_basename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supervisor/localGPT/run_localGPT.py", line 77, in load_model
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 484, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2881, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2980, in _load_pretrained_model
    raise ValueError(
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.
2023-07-04 06:04:32,158 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: /home/supervisor/localGPT/DB
(env1) supervisor@ubuntu:~/localGPT$ 

```

**Comment by dportabella** [comment]
it seems that this means insufficient CPU memory. How much memory is needed?
(for the provided example: SOURCE_DOCUMENTS/constitution.pdf)

**Comment by bartanderson** [comment]
Seems I had the same problem, added safetensors to see if that would help and it didn't
(LocalGPT) D:\Github\LocalGPT\localGPT>pip install safetensors
Requirement already satisfied: safetensors in d:\github\localgpt\lib\site-packages (0.3.1)

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

(LocalGPT) D:\Github\LocalGPT\localGPT>python run_localGPT.py
2023-07-07 20:22:26,813 - INFO - run_localGPT.py:176 - Running on: cuda
2023-07-07 20:22:26,813 - INFO - run_localGPT.py:177 - Display Source Documents set to: False
2023-07-07 20:22:28,104 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-07-07 20:22:37,933 - INFO - __init__.py:88 - Running Chroma using direct local API.
2023-07-07 20:22:37,972 - WARNING - __init__.py:43 - Using embedded DuckDB with persistence: data will be stored in: D:\Github\LocalGPT\localGPT/DB
2023-07-07 20:22:38,023 - INFO - ctypes.py:22 - Successfully imported ClickHouse Connect C data optimizations
2023-07-07 20:22:38,083 - INFO - json_impl.py:45 - Using python library for writing JSON byte strings
2023-07-07 20:22:38,125 - INFO - duckdb.py:460 - loaded in 0 embeddings
2023-07-07 20:22:38,127 - INFO - duckdb.py:472 - loaded in 1 collections
2023-07-07 20:22:38,128 - INFO - duckdb.py:89 - collection with name langchain already exists, returning existing collection
2023-07-07 20:22:38,128 - INFO - run_localGPT.py:43 - Loading Model: TheBloke/vicuna-7B-1.1-HF, on: cuda
2023-07-07 20:22:38,128 - INFO - run_localGPT.py:44 - This action can take a few minutes!
2023-07-07 20:22:38,129 - INFO - run_localGPT.py:86 - Using AutoModelForCausalLM for full models
2023-07-07 20:26:07,794 - INFO - run_localGPT.py:88 - Tokenizer loaded
2023-07-07 20:26:09,848 - WARNING - modeling.py:706 - The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Traceback (most recent call last):
  File "D:\Github\LocalGPT\localGPT\run_localGPT.py", line 253, in <module>
    main()
  File "D:\Github\LocalGPT\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\Github\LocalGPT\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\Github\LocalGPT\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Github\LocalGPT\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\Github\LocalGPT\localGPT\run_localGPT.py", line 222, in main
    llm = load_model(device_type, model_id=model_id, model_basename=model_basename)
  File "D:\Github\LocalGPT\localGPT\run_localGPT.py", line 90, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "D:\Github\LocalGPT\lib\site-packages\transformers\models\auto\auto_factory.py", line 484, in from_pretrained
    return model_class.from_pretrained(
  File "D:\Github\LocalGPT\lib\site-packages\transformers\modeling_utils.py", line 2881, in from_pretrained
    ) = cls._load_pretrained_model(
  File "D:\Github\LocalGPT\lib\site-packages\transformers\modeling_utils.py", line 2980, in _load_pretrained_model
    raise ValueError(
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.
2023-07-07 20:26:09,858 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: D:\Github\LocalGPT\localGPT/DB

**Comment by bartanderson** [comment]
(LocalGPT) D:\Github\LocalGPT\localGPT>python --version
Python 3.10.11

**Comment by PromtEngineer** [comment]
@dportabella what os are you running this one, can you provide details about your hardware? If you are trying to run it cpu, I would recommend to check out ggml models. Here is a good reference for VRAM requirements for a full model. https://discuss.huggingface.co/t/llama-7b-gpu-memory-requirement/34323/2

@bartanderson can you please provide details about your hardware and RAM, here are a few things that we can try. 
1. Use ggml or gptq models and see if you run into the same issues. 
2. Update the code as follows: See if this helps. 

`        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            device_map="auto",
            torch_dtype=torch.float16,
            low_cpu_mem_usage=True,
            trust_remote_code=True,
 offload_folder="offload", 
            # max_memory={0: "15GB"} # Uncomment this line with you encounter CUDA out of memory errors
        )
`

**Comment by bartanderson** [comment]
Thanks for the suggestions.
I am on windows 10 16GB memory with nvidia RTX 3070 Ti  8 GB
I tried a couple models but they couldn't be found for some reason. Do I
need to download them and store them somewhere?
I tried ggml and the one below
Also I am guessing that the assertion for cuda with the ingestion is ok.

(LocalGPT) D:\Github\LocalGPT\localGPT>python ingest.py
2023-07-08 23:20:57,648 - INFO - ingest.py:120 - Loading documents from
D:\Github\LocalGPT\localGPT/SOURCE_DOCUMENTS
2023-07-08 23:21:02,018 - INFO - ingest.py:129 - Loaded 1 documents from
D:\Github\LocalGPT\localGPT/SOURCE_DOCUMENTS
2023-07-08 23:21:02,018 - INFO - ingest.py:130 - Split into 72 chunks of
text
2023-07-08 23:21:07,327 - INFO - SentenceTransformer.py:66 - Load
pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-07-08 23:21:10,238 - INFO - __init__.py:88 - Running Chroma using
direct local API.
2023-07-08 23:21:11,078 - WARNING - __init__.py:43 - Using embedded DuckDB
with persistence: data will be stored in: D:\Github\LocalGPT\localGPT/DB
2023-07-08 23:21:11,091 - INFO - ctypes.py:22 - Successfully imported
ClickHouse Connect C data optimizations
2023-07-08 23:21:11,108 - INFO - json_impl.py:45 - Using python library for
writing JSON byte strings
2023-07-08 23:21:11,147 - INFO - duckdb.py:460 - loaded in 0 embeddings
2023-07-08 23:21:11,149 - INFO - duckdb.py:472 - loaded in 1 collections
2023-07-08 23:21:11,150 - INFO - duckdb.py:89 - collection with name
langchain already exists, returning existing collection
Traceback (most recent call last):
  File "D:\Github\LocalGPT\localGPT\ingest.py", line 158, in <module>
    main()
  File "D:\Github\LocalGPT\lib\site-packages\click\core.py", line 1157, in
__call__
    return self.main(*args, **kwargs)
  File "D:\Github\LocalGPT\lib\site-packages\click\core.py", line 1078, in
main
    rv = self.invoke(ctx)
  File "D:\Github\LocalGPT\lib\site-packages\click\core.py", line 1434, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Github\LocalGPT\lib\site-packages\click\core.py", line 783, in
invoke
    return __callback(*args, **kwargs)
  File "D:\Github\LocalGPT\localGPT\ingest.py", line 144, in main
    db = Chroma.from_documents(
  File
"D:\Github\LocalGPT\lib\site-packages\langchain\vectorstores\chroma.py",
line 446, in from_documents
    return cls.from_texts(
  File
"D:\Github\LocalGPT\lib\site-packages\langchain\vectorstores\chroma.py",
line 414, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File
"D:\Github\LocalGPT\lib\site-packages\langchain\vectorstores\chroma.py",
line 159, in add_texts
    embeddings = self._embedding_function.embed_documents(list(texts))
  File
"D:\Github\LocalGPT\lib\site-packages\langchain\embeddings\huggingface.py",
line 158, in embed_documents
    embeddings = self.client.encode(instruction_pairs, **self.encode_kwargs)
  File
"D:\Github\LocalGPT\lib\site-packages\InstructorEmbedding\instructor.py",
line 521, in encode
    self.to(device)
  File "D:\Github\LocalGPT\lib\site-packages\torch\nn\modules\module.py",
line 1145, in to
    return self._apply(convert)
  File "D:\Github\LocalGPT\lib\site-packages\torch\nn\modules\module.py",
line 797, in _apply
    module._apply(fn)
  File "D:\Github\LocalGPT\lib\site-packages\torch\nn\modules\module.py",
line 797, in _apply
    module._apply(fn)
  File "D:\Github\LocalGPT\lib\site-packages\torch\nn\modules\module.py",
line 797, in _apply
    module._apply(fn)
  File "D:\Github\LocalGPT\lib\site-packages\torch\nn\modules\module.py",
line 820, in _apply
    param_applied = fn(param)
  File "D:\Github\LocalGPT\lib\site-packages\torch\nn\modules\module.py",
line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex()
else None, non_blocking)
  File "D:\Github\LocalGPT\lib\site-packages\torch\cuda\__init__.py", line
239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
2023-07-08 23:21:11,289 - INFO - duckdb.py:414 - Persisting DB to disk,
putting it in the save folder: D:\Github\LocalGPT\localGPT/DB

(LocalGPT) D:\Github\LocalGPT\localGPT>python run_localGPT.py
2023-07-08 23:21:35,186 - INFO - run_localGPT.py:177 - Running on: cuda
2023-07-08 23:21:35,186 - INFO - run_localGPT.py:178 - Display Source
Documents set to: False
2023-07-08 23:21:35,621 - INFO - SentenceTransformer.py:66 - Load
pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-07-08 23:21:38,450 - INFO - __init__.py:88 - Running Chroma using
direct local API.
2023-07-08 23:21:38,458 - WARNING - __init__.py:43 - Using embedded DuckDB
with persistence: data will be stored in: D:\Github\LocalGPT\localGPT/DB
2023-07-08 23:21:38,472 - INFO - ctypes.py:22 - Successfully imported
ClickHouse Connect C data optimizations
2023-07-08 23:21:38,488 - INFO - json_impl.py:45 - Using python library for
writing JSON byte strings
2023-07-08 23:21:38,522 - INFO - duckdb.py:460 - loaded in 0 embeddings
2023-07-08 23:21:38,524 - INFO - duckdb.py:472 - loaded in 1 collections
2023-07-08 23:21:38,525 - INFO - duckdb.py:89 - collection with name
langchain already exists, returning existing collection
2023-07-08 23:21:38,525 - INFO - run_localGPT.py:43 - Loading Model:
TheBloke/orca_mini_3B-GGML, on: cuda
2023-07-08 23:21:38,525 - INFO - run_localGPT.py:44 - This action can take
a few minutes!
2023-07-08 23:21:38,526 - INFO - run_localGPT.py:64 - Using
AutoGPTQForCausalLM for quantized models
Traceback (most recent call last):
  File
"D:\Github\LocalGPT\lib\site-packages\huggingface_hub\utils\_errors.py",
line 261, in hf_raise_for_status
    response.raise_for_status()
  File "D:\Github\LocalGPT\lib\site-packages\requests\models.py", line
1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url:
https://huggingface.co/TheBloke/orca_mini_3B-GGML/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Github\LocalGPT\lib\site-packages\transformers\utils\hub.py",
line 417, in cached_file
    resolved_file = hf_hub_download(
  File
"D:\Github\LocalGPT\lib\site-packages\huggingface_hub\utils\_validators.py",
line 118, in _inner_fn
    return fn(*args, **kwargs)
  File
"D:\Github\LocalGPT\lib\site-packages\huggingface_hub\file_download.py",
line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
  File
"D:\Github\LocalGPT\lib\site-packages\huggingface_hub\utils\_validators.py",
line 118, in _inner_fn
    return fn(*args, **kwargs)
  File
"D:\Github\LocalGPT\lib\site-packages\huggingface_hub\file_download.py",
line 1541, in get_hf_file_metadata
    hf_raise_for_status(r)
  File
"D:\Github\LocalGPT\lib\site-packages\huggingface_hub\utils\_errors.py",
line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error.
(Request ID:
Root=1-64aa35d2-351b855f72d9b3127654f20a;bfc3c321-9020-4a27-abb9-d3ac13e0adee)

Entry Not Found for url:
https://huggingface.co/TheBloke/orca_mini_3B-GGML/resolve/main/config.json.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Github\LocalGPT\localGPT\run_localGPT.py", line 254, in <module>
    main()
  File "D:\Github\LocalGPT\lib\site-packages\click\core.py", line 1157, in
__call__
    return self.main(*args, **kwargs)
  File "D:\Github\LocalGPT\lib\site-packages\click\core.py", line 1078, in
main
    rv = self.invoke(ctx)
  File "D:\Github\LocalGPT\lib\site-packages\click\core.py", line 1434, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Github\LocalGPT\lib\site-packages\click\core.py", line 783, in
invoke
    return __callback(*args, **kwargs)
  File "D:\Github\LocalGPT\localGPT\run_localGPT.py", line 223, in main
    llm = load_model(device_type, model_id=model_id,
model_basename=model_basename)
  File "D:\Github\LocalGPT\localGPT\run_localGPT.py", line 70, in load_model
    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)
  File
"D:\Github\LocalGPT\lib\site-packages\transformers\models\auto\tokenization_auto.py",
line 658, in from_pretrained
    config = AutoConfig.from_pretrained(
  File
"D:\Github\LocalGPT\lib\site-packages\transformers\models\auto\configuration_auto.py",
line 944, in from_pretrained
    config_dict, unused_kwargs =
PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File
"D:\Github\LocalGPT\lib\site-packages\transformers\configuration_utils.py",
line 574, in get_config_dict
    config_dict, kwargs =
cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File
"D:\Github\LocalGPT\lib\site-packages\transformers\configuration_utils.py",
line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "D:\Github\LocalGPT\lib\site-packages\transformers\utils\hub.py",
line 463, in cached_file
    raise EnvironmentError(
OSError: TheBloke/orca_mini_3B-GGML does not appear to have a file named
config.json. Checkout '
https://huggingface.co/TheBloke/orca_mini_3B-GGML/main' for available files.
2023-07-08 23:21:38,742 - INFO - duckdb.py:414 - Persisting DB to disk,
putting it in the save folder: D:\Github\LocalGPT\localGPT/DB

(LocalGPT) D:\Github\LocalGPT\localGPT>

**Comment by HaythamG** [comment]
on the AutoModelForCausalLM.from_pretrained add the parameter : **offload_folder="offload"**

> running on a virtual machine with Ubuntu 22.04.2 LTS:
> 
> ```
> git clone https://github.com/PromtEngineer/localGPT.git
> cd localGPT
> conda create --name env1 python=3.11.3
> conda activate env1
> conda install python=3.11.3
> sudo apt-get install build-essential -y     # << this solved the "at least C++11 support is needed!"
> pip install -r requirements.txt
> 
> git clone https://github.com/PanQiWei/AutoGPTQ.git
> cd AutoGPTQ
> git checkout v0.2.2
> pip install .
> cd ..
> 
> python ingest.py --device_type cpu
> 
> python run_localGPT.py
> 
> Downloading shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [11:29<00:00, 345.00s/it]
> 2023-07-04 06:04:31,924 - WARNING - modeling.py:706 - The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
> Traceback (most recent call last):
>   File "/home/supervisor/localGPT/run_localGPT.py", line 232, in <module>
>     main()
>   File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/supervisor/localGPT/run_localGPT.py", line 201, in main
>     llm = load_model(device_type, model_id=model_id, model_basename=model_basename)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/supervisor/localGPT/run_localGPT.py", line 77, in load_model
>     model = AutoModelForCausalLM.from_pretrained(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 484, in from_pretrained
>     return model_class.from_pretrained(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2881, in from_pretrained
>     ) = cls._load_pretrained_model(
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/supervisor/anaconda3/envs/env1/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2980, in _load_pretrained_model
>     raise ValueError(
> ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.
> 2023-07-04 06:04:32,158 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: /home/supervisor/localGPT/DB
> (env1) supervisor@ubuntu:~/localGPT$ 
> ```
