### ISSUE TITLE
ingest fails on Windows 10

### ISSUE THREAD

**Issue by blap** [PromtEngineer/localGPT#238]
Hi,

On Windows10 the ingest.py fails. 
I need to edit constants.py in to run:

` # Define the folder for storing database
SOURCE_DIRECTORY = f"{ROOT_DIRECTORY}/SOURCE_DOCUMENTS"

PERSIST_DIRECTORY = f"{ROOT_DIRECTORY}/DB" `

to

` # Define the folder for storing database
SOURCE_DIRECTORY = f"{ROOT_DIRECTORY}\SOURCE_DOCUMENTS"

PERSIST_DIRECTORY = f"{ROOT_DIRECTORY}\DB" ` 

but "bitsandbytes" only run in linux...

python -m bitsandbytes
False

===================================BUG REPORT===================================
C:\localGPT\localGPT-env\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 6.1.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
C:\localGPT\localGPT-env\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog/4bit-transformers-bitsandbytes
  warn(msg)
CUDA SETUP: Loading binary C:\localGPT\localGPT-env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118_nocublaslt.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\localGPT\localGPT-env\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\localGPT\localGPT-env\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\localGPT\localGPT-env\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\localGPT\localGPT-env\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\localGPT\localGPT-env\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\localGPT\localGPT-env\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by blap** [comment]
How I install localGPT on windows 10:

cd C:\localGPT
python -m venv localGPT-env
localGPT-env\Scripts\activate.bat
python.exe -m pip install --upgrade pip
python.exe -m pip install --upgrade setuptools
python.exe -m pip install --upgrade wheel
py -m pip install nvidia-cuda-runtime-cu11
py -m pip install nvidia-cuda-cupti-cu11
py -m pip install nvidia-cuda-nvcc-cu11
py -m pip install nvidia-nvml-dev-cu11
py -m pip install nvidia-cuda-nvrtc-cu11
py -m pip install nvidia-nvtx-cu11
py -m pip install nvidia-cuda-sanitizer-api-cu11
py -m pip install nvidia-cublas-cu11 
py -m pip install nvidia-cufft-cu11
py -m pip install nvidia-curand-cu11
py -m pip install nvidia-cusolver-cu11 
py -m pip install nvidia-cusparse-cu11 
py -m pip install nvidia-npp-cu11
py -m pip install nvidia-nvjpeg-cu11
pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu118
python -m pip install -r requirements.txt
git clone https://github.com/PanQiWei/AutoGPTQ.git
cd AutoGPTQ
git checkout v0.2.2
pip install .
cd..
python ingest.py

**Comment by Aegide** [comment]
Ok but does `python ingest.py --device_type cpu` work for you ?

**Comment by blap** [comment]
> Ok but does `python ingest.py --device_type cpu` work for you ?

No...
Now I got:

(localGPT-env) C:\localGPT>python run_localGPT.py

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\localGPT\localGPT-env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118_nocublaslt.dll
CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 118
C:\localGPT\localGPT-env\lib\site-packages\bitsandbytes\cuda_setup\main.py:152: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary C:\localGPT\localGPT-env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118_nocublaslt.dll...
2023-07-24 13:35:06,548 - INFO - run_localGPT.py:176 - Running on: cuda
2023-07-24 13:35:06,548 - INFO - run_localGPT.py:177 - Display Source Documents set to: False
2023-07-24 13:35:07,549 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-07-24 13:35:18,696 - INFO - __init__.py:88 - Running Chroma using direct local API.
2023-07-24 13:35:18,716 - WARNING - __init__.py:43 - Using embedded DuckDB with persistence: data will be stored in: C:\localGPT\DB
2023-07-24 13:35:18,755 - INFO - ctypes.py:22 - Successfully imported ClickHouse Connect C data optimizations
2023-07-24 13:35:18,787 - INFO - json_impl.py:45 - Using python library for writing JSON byte strings
2023-07-24 13:35:18,909 - INFO - duckdb.py:460 - loaded in 58 embeddings
2023-07-24 13:35:18,909 - INFO - duckdb.py:472 - loaded in 1 collections
2023-07-24 13:35:18,919 - INFO - duckdb.py:89 - collection with name langchain already exists, returning existing collection
2023-07-24 13:35:18,919 - INFO - run_localGPT.py:43 - Loading Model: TheBloke/Llama-2-7B-Chat-GGML, on: cuda
2023-07-24 13:35:18,919 - INFO - run_localGPT.py:44 - This action can take a few minutes!
2023-07-24 13:35:18,919 - INFO - run_localGPT.py:64 - Using AutoGPTQForCausalLM for quantized models
Traceback (most recent call last):
  File "C:\localGPT\run_localGPT.py", line 256, in <module>
    main()
  File "C:\localGPT\localGPT-env\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\localGPT\localGPT-env\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\localGPT\localGPT-env\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\localGPT\localGPT-env\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\localGPT\run_localGPT.py", line 225, in main
    llm = load_model(device_type, model_id=model_id, model_basename=model_basename)
  File "C:\localGPT\run_localGPT.py", line 70, in load_model
    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)
  File "C:\localGPT\localGPT-env\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 720, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "C:\localGPT\localGPT-env\lib\site-packages\transformers\tokenization_utils_base.py", line 1825, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'TheBloke/Llama-2-7B-Chat-GGML'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'TheBloke/Llama-2-7B-Chat-GGML' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.
2023-07-24 13:35:20,914 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: C:\localGPT\DB

(localGPT-env) C:\localGPT>

**Comment by blap** [comment]
#257
