### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by DaneCode** [PromtEngineer/localGPT#243]
I am new to messing around with LLM but every time I try to put an input into the prompt I get the following error. I even did a fresh install of conda on the computer to follow install instructions exactly. I'm not sure if it is my computer, me, or the code is the issue. Before Llama 2 was the default I had traceback issue with Vicuna as well after entering a question into the prompt.
Traceback (most recent call last):
  File "C:\Users\user\Documents\llm\localgpt_llama2\run_localGPT.py", line 256, in <module>
    main()
  File "C:\Users\user\.conda\envs\localgpt_llama2\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\.conda\envs\localgpt_llama2\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\.conda\envs\localgpt_llama2\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\.conda\envs\localgpt_llama2\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\user\Documents\llm\localgpt_llama2\run_localGPT.py", line 225, in main
    llm = load_model(device_type, model_id=model_id, model_basename=model_basename)
  File "C:\Users\user\Documents\llm\localgpt_llama2\run_localGPT.py", line 70, in load_model
    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)
  File "C:\Users\user\.conda\envs\localgpt_llama2\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 720, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "C:\Users\user\.conda\envs\localgpt_llama2\lib\site-packages\transformers\tokenization_utils_base.py", line 1825, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'TheBloke/Llama-2-7B-Chat-GGML'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'TheBloke/Llama-2-7B-Chat-GGML' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.
2023-07-22 22:18:14,307 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: C:\Users\user\Documents\llm\localgpt_llama2/DB

**Comment by PromtEngineer** [comment]
@DaneCode are you trying to run this on cpu or gpu?

**Comment by DaneCode** [comment]
I'm trying to run it with GPU its a 3080ti

**Comment by DaneCode** [comment]
I went back and tested the Ingest command again and reading the output it looks like there was an issue with the ingest.  I am getting this error.

AssertionError: Torch not compiled with CUDA enabled

It appears that Pytorch may have been installed without cuda support. I went back and did the ingest using cpu and it ran to completion. I then ran run_localGPT.py and it is now running on cpu. I'll probably have to go in and install the cuda version of Pytorch so I can use my gpu.

https://github.com/pytorch/pytorch/issues/30664

**Comment by klei22** [comment]
Seems I am running into the same problem for both GPTQ and GGML models (the HF Face formats appear to download properly).

Trying again with just cpu, and will try later on a cloud server.

**Comment by agates-gates** [comment]
I got the same error as @DaneCode when running run_localGPT.py on cuda and no errors when running with --device_type cpu option. With option it starts to download model. Without options - it doesn't.

**Comment by Kharankumar** [comment]
This is the error i ran into . i am running it in cpu

python run_localGPT.py             
2023-10-11 02:33:27,102 - INFO - run_localGPT.py:229 - Running on: cpu
2023-10-11 02:33:27,103 - INFO - run_localGPT.py:230 - Display Source Documents set to: False
2023-10-11 02:33:27,103 - INFO - run_localGPT.py:231 - Use history set to: False
2023-10-11 02:33:27,504 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-10-11 02:33:30,663 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-10-11 02:33:30,835 - INFO - run_localGPT.py:56 - Loading Model: TheBloke/Llama-2-7b-Chat-GGUF, on: cpu
2023-10-11 02:33:30,835 - INFO - run_localGPT.py:57 - This action can take a few minutes!
2023-10-11 02:33:30,835 - INFO - load_models.py:38 - Using Llamacpp for GGUF/GGML quantized models
Exception ignored in: <function Llama.__del__ at 0x00000229A8BA6560>
Traceback (most recent call last):
  File "C:\Users\intellectyx\Desktop\localGPT\venv\lib\site-packages\llama_cpp\llama.py", line 1333, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'
Traceback (most recent call last):
  File "C:\Users\intellectyx\Desktop\localGPT\run_localGPT.py", line 266, in <module>
  File "C:\Users\intellectyx\Desktop\localGPT\run_localGPT.py", line 266, in <module>
    main()
  File "C:\Users\intellectyx\Desktop\localGPT\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\intellectyx\Desktop\localGPT\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\intellectyx\Desktop\localGPT\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\intellectyx\Desktop\localGPT\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\intellectyx\Desktop\localGPT\run_localGPT.py", line 237, in main
    qa = retrieval_qa_pipline(device_type, use_history, promptTemplate_type=model_type)
  File "C:\Users\intellectyx\Desktop\localGPT\run_localGPT.py", line 144, in retrieval_qa_pipline
    qa = RetrievalQA.from_chain_type(
  File "C:\Users\intellectyx\Desktop\localGPT\venv\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 100, in from_chain_type
    combine_documents_chain = load_qa_chain(
  File "C:\Users\intellectyx\Desktop\localGPT\venv\lib\site-packages\langchain\chains\question_answering\__init__.py", line 249, in load_qa_chain   
    return loader_mapping[chain_type](
  File "C:\Users\intellectyx\Desktop\localGPT\venv\lib\site-packages\langchain\chains\question_answering\__init__.py", line 73, in _load_stuff_chain    llm_chain = LLMChain(    llm_chain = LLMChain(
  File "C:\Users\intellectyx\Desktop\localGPT\venv\lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
llm
  none is not an allowed value (type=type_error.none.not_allowed)

anyone came across and cleared it?
