### ISSUE TITLE
NameError: name 'autogptq_cuda_256' is not defined

### ISSUE THREAD

**Issue by CalendulaED** [PromtEngineer/localGPT#251]
It seems like AutoGPTQ quantization module not being able to access the CUDA extension.

The previous ingest problem is solve by 
pip install git+https://github.com/Keith-Hon/bitsandbytes-windows.git

By right now, when I change modal id and name to
`model_id="TheBloke/llama-2-7B-Guanaco-QLoRA-GPTQ"
    model_basename = "gptq_model-4bit-128g.safetensors"`

The modal link is this one: [https://huggingface.co/TheBloke/llama-2-7B-Guanaco-QLoRA-GPTQ/tree/main](url)
and I run ` python .\run_localGPT.py --device_type cuda `

It will have the following output:
`
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
2023-07-23 17:07:02,970 - INFO - run_localGPT.py:176 - Running on: cuda
2023-07-23 17:07:02,971 - INFO - run_localGPT.py:177 - Display Source Documents set to: False
2023-07-23 17:07:03,266 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-07-23 17:07:05,639 - INFO - __init__.py:88 - Running Chroma using direct local API.
2023-07-23 17:07:05,661 - WARNING - __init__.py:43 - Using embedded DuckDB with persistence: data will be stored in: D:\OnlineLearning\GPT\localGPT/DB
2023-07-23 17:07:05,674 - INFO - ctypes.py:22 - Successfully imported ClickHouse Connect C data optimizations
2023-07-23 17:07:05,691 - INFO - json_impl.py:45 - Using python library for writing JSON byte strings
2023-07-23 17:07:05,730 - INFO - duckdb.py:460 - loaded in 72 embeddings
2023-07-23 17:07:05,732 - INFO - duckdb.py:472 - loaded in 1 collections
2023-07-23 17:07:05,733 - INFO - duckdb.py:89 - collection with name langchain already exists, returning existing collection
2023-07-23 17:07:05,733 - INFO - run_localGPT.py:43 - Loading Model: TheBloke/llama-2-7B-Guanaco-QLoRA-GPTQ, on: cuda
2023-07-23 17:07:05,733 - INFO - run_localGPT.py:44 - This action can take a few minutes!
2023-07-23 17:07:05,734 - INFO - run_localGPT.py:64 - Using AutoGPTQForCausalLM for quantized models
Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 695/695 [00:00<00:00, 1.35MB/s]
C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\wuyux\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.  
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Downloading tokenizer.model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 15.0MB/s]
Downloading (…)/main/tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 29.1MB/s]
Downloading (…)in/added_tokens.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21.0/21.0 [00:00<?, ?B/s]
Downloading (…)cial_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 435/435 [00:00<?, ?B/s]
2023-07-23 17:07:06,514 - INFO - run_localGPT.py:71 - Tokenizer loaded
Downloading (…)lve/main/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 667/667 [00:00<00:00, 667kB/s]
Downloading (…)quantize_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 185/185 [00:00<00:00, 185kB/s]
Downloading (…)bit-128g.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.90G/3.90G [01:00<00:00, 63.9MB/s]
2023-07-23 17:08:08,047 - INFO - _base.py:746 - lm_head not been quantized, will be ignored when make_quant.
2023-07-23 17:08:08,051 - WARNING - qlinear_cuda_old.py:15 - CUDA extension not installed.
Traceback (most recent call last):
  File "D:\OnlineLearning\GPT\localGPT\run_localGPT.py", line 258, in <module>
    main()
  File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\OnlineLearning\GPT\localGPT\run_localGPT.py", line 227, in main
    llm = load_model(device_type, model_id=model_id, model_basename=model_basename)
  File "D:\OnlineLearning\GPT\localGPT\run_localGPT.py", line 73, in load_model
    model = AutoGPTQForCausalLM.from_quantized(
  File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\auto_gptq\modeling\auto.py", line 94, in from_quantized
    return quant_func(
  File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\auto_gptq\modeling\_base.py", line 749, in from_quantized
    make_quant(
  File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\auto_gptq\modeling\_utils.py", line 92, in make_quant
    make_quant(
  File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\auto_gptq\modeling\_utils.py", line 92, in make_quant
    make_quant(
  File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\auto_gptq\modeling\_utils.py", line 92, in make_quant
    make_quant(
  [Previous line repeated 1 more time]
  File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\auto_gptq\modeling\_utils.py", line 84, in make_quant
    new_layer = QuantLinear(
  File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\auto_gptq\nn_modules\qlinear\qlinear_cuda_old.py", line 83, in __init__
    self.autogptq_cuda = autogptq_cuda_256
NameError: name 'autogptq_cuda_256' is not defined
2023-07-23 17:08:08,075 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: D:\OnlineLearning\GPT\localGPT/DB
`

**Comment by Thutmose3** [comment]
Same error, any news?

**Comment by Ananderz** [comment]
Yes!

I had this issue when I had the latest version of auto-gptq. You guys need v0.2.2 

Uninstall
pip uninstall auto-gptq --yes

git clone https://github.com/PanQiWei/AutoGPTQ.git
cd AutoGPTQ
git checkout v0.2.2
pip install .

(Yes the pip install is a .)

**Comment by red1xe** [comment]
@Ananderz I did it same thing but I got this error:
e file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for auto-gptq
  Running setup.py clean for auto-gptq
Failed to build auto-gptq
ERROR: Could not build wheels for auto-gptq, which is required to install pyproject.toml-based projects

**Comment by KonradHoeffner** [comment]
Why install AutoGPTQ 0.2.2 from source and not from pip?

**Comment by CalendulaED** [comment]
> Yes!
> 
> I had this issue when I had the latest version of auto-gptq. You guys need v0.2.2
> 
> Uninstall pip uninstall auto-gptq --yes
> 
> git clone https://github.com/PanQiWei/AutoGPTQ.git cd AutoGPTQ git checkout v0.2.2 pip install .
> 
> (Yes the pip install is a .)

But I got error when installing the 0.2.2 version of it
Building wheels for collected packages: auto-gptq
  Building wheel for auto-gptq (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [106 lines of output]
      include dirs are: ['autogptq_cuda']
      running bdist_wheel
      C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\auto_gptq
      copying auto_gptq\__init__.py -> build\lib.win-amd64-cpython-310\auto_gptq
      creating build\lib.win-amd64-cpython-310\auto_gptq\eval_tasks
      copying auto_gptq\eval_tasks\language_modeling_task.py -> build\lib.win-amd64-cpython-310\auto_gptq\eval_tasks
      copying auto_gptq\eval_tasks\sequence_classification_task.py -> build\lib.win-amd64-cpython-310\auto_gptq\eval_tasks
      copying auto_gptq\eval_tasks\text_summarization_task.py -> build\lib.win-amd64-cpython-310\auto_gptq\eval_tasks
      copying auto_gptq\eval_tasks\_base.py -> build\lib.win-amd64-cpython-310\auto_gptq\eval_tasks
      copying auto_gptq\eval_tasks\__init__.py -> build\lib.win-amd64-cpython-310\auto_gptq\eval_tasks
      creating build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\auto.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\bloom.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\codegen.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\gpt2.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\gptj.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\gpt_bigcode.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\gpt_neox.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\llama.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\moss.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\opt.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\rw.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\_base.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\_const.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\_utils.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      copying auto_gptq\modeling\__init__.py -> build\lib.win-amd64-cpython-310\auto_gptq\modeling
      creating build\lib.win-amd64-cpython-310\auto_gptq\nn_modules
      copying auto_gptq\nn_modules\fused_gptj_attn.py -> build\lib.win-amd64-cpython-310\auto_gptq\nn_modules
      copying auto_gptq\nn_modules\fused_llama_attn.py -> build\lib.win-amd64-cpython-310\auto_gptq\nn_modules
      copying auto_gptq\nn_modules\fused_llama_mlp.py -> build\lib.win-amd64-cpython-310\auto_gptq\nn_modules
      copying auto_gptq\nn_modules\qlinear.py -> build\lib.win-amd64-cpython-310\auto_gptq\nn_modules
      copying auto_gptq\nn_modules\qlinear_old.py -> build\lib.win-amd64-cpython-310\auto_gptq\nn_modules
      copying auto_gptq\nn_modules\qlinear_triton.py -> build\lib.win-amd64-cpython-310\auto_gptq\nn_modules
      copying auto_gptq\nn_modules\_fused_base.py -> build\lib.win-amd64-cpython-310\auto_gptq\nn_modules
      copying auto_gptq\nn_modules\__init__.py -> build\lib.win-amd64-cpython-310\auto_gptq\nn_modules
      creating build\lib.win-amd64-cpython-310\auto_gptq\quantization
      copying auto_gptq\quantization\gptq.py -> build\lib.win-amd64-cpython-310\auto_gptq\quantization
      copying auto_gptq\quantization\quantizer.py -> build\lib.win-amd64-cpython-310\auto_gptq\quantization
      copying auto_gptq\quantization\__init__.py -> build\lib.win-amd64-cpython-310\auto_gptq\quantization
      creating build\lib.win-amd64-cpython-310\auto_gptq\utils
      copying auto_gptq\utils\data_utils.py -> build\lib.win-amd64-cpython-310\auto_gptq\utils
      copying auto_gptq\utils\import_utils.py -> build\lib.win-amd64-cpython-310\auto_gptq\utils
      copying auto_gptq\utils\__init__.py -> build\lib.win-amd64-cpython-310\auto_gptq\utils
      creating build\lib.win-amd64-cpython-310\auto_gptq\eval_tasks\_utils
      copying auto_gptq\eval_tasks\_utils\classification_utils.py -> build\lib.win-amd64-cpython-310\auto_gptq\eval_tasks\_utils
      copying auto_gptq\eval_tasks\_utils\generation_utils.py -> build\lib.win-amd64-cpython-310\auto_gptq\eval_tasks\_utils
      copying auto_gptq\eval_tasks\_utils\__init__.py -> build\lib.win-amd64-cpython-310\auto_gptq\eval_tasks\_utils
      creating build\lib.win-amd64-cpython-310\auto_gptq\nn_modules\triton_utils
      copying auto_gptq\nn_modules\triton_utils\custom_autotune.py -> build\lib.win-amd64-cpython-310\auto_gptq\nn_modules\triton_utils
      copying auto_gptq\nn_modules\triton_utils\kernels.py -> build\lib.win-amd64-cpython-310\auto_gptq\nn_modules\triton_utils
      copying auto_gptq\nn_modules\triton_utils\mixin.py -> build\lib.win-amd64-cpython-310\auto_gptq\nn_modules\triton_utils
      copying auto_gptq\nn_modules\triton_utils\__init__.py -> build\lib.win-amd64-cpython-310\auto_gptq\nn_modules\triton_utils
      running build_ext
      C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。       
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\wuyux\AppData\Local\Temp\pip-install-fpryo4yc\auto-gptq_f49fd3747443445a829dfcefe48508ac\setup.py", line 92, in <module>
          setup(
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\wheel\bdist_wheel.py", line 346, in run
          self.run_command("build")
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\wuyux\anaconda3\envs\localgpt\lib\site-packages\torch\utils\cpp_extension.py", line 387, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.2) mismatches the version that was used to compile
      PyTorch (11.8). Please make sure to use the same CUDA versions.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for auto-gptq
  Running setup.py clean for auto-gptq
Failed to build auto-gptq
ERROR: Could not build wheels for auto-gptq, which is required to install pyproject.toml-based projects

**Comment by KonradHoeffner** [comment]
The important part from your error log is this line:

`The detected CUDA version (12.2) mismatches the version that was used to compile
PyTorch (11.8)`

Either install CUDA 11.8 or, if like me on Arch Linux you can't do that due to gcc dependency conflicts, use Docker instead to have a controlled environment where the dependencies are correct.

**Comment by Quetzalcohuatl** [comment]
i confirm downgraded to 0.2.2 fixes this issue. It occurred for me when loading the recent llama2 gptq model. It is an issue with auto-gptq, not with this package.

**Comment by KonradHoeffner** [comment]
@ CalendulaED can you try again with the newest main branch and `pip install -r requirements.txt` again?

**Comment by theyodaway** [comment]
Initially I tried with pip3 install auto_gtpq which was installed sucessfully but was throwing error auto_gtpq_cuda_256 is not defined while running the code.
I downloaded  auto_gptq-0.2.2+cu117-cp310-cp310-linux_x86_64.whl from https://github.com/PanQiWei/AutoGPTQ/releases and ran pip3 install auto_gptq-0.2.2+cu117-cp310-cp310-linux_x86_64.whl. It worked for me

**Comment by daniell0gda** [comment]
for me not, tried different auto_gptq 0.2.2 and newest.. and I still got 
```  
(myLocalGPT) PS C:\private\myLocalGPT> python llama.py --model_name="TheBloke/Llama-2-7B-GPTQ"     
CUDA extension not installed.
The safetensors archive passed at C:\Users\Daniel/.cache\huggingface\hub\models--TheBloke--Llama-2-7B-GPTQ\snapshots\98ffa0d89723ce1e3214f477469b2db67c6c4586\gptq_model-4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` 
method. Defaulting to 'pt' metadata.
skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://e30c0e3c6961f91403.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Traceback (most recent call last):
  File "C:\Users\Daniel\.conda\envs\myLocalGPT\lib\site-packages\gradio\routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Daniel\.conda\envs\myLocalGPT\lib\site-packages\gradio\blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "C:\Users\Daniel\.conda\envs\myLocalGPT\lib\site-packages\gradio\blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\Daniel\.conda\envs\myLocalGPT\lib\site-packages\gradio\utils.py", line 347, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\Daniel\.conda\envs\myLocalGPT\lib\site-packages\gradio\utils.py", line 340, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\Daniel\.conda\envs\myLocalGPT\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Daniel\.conda\envs\myLocalGPT\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Daniel\.conda\envs\myLocalGPT\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Daniel\.conda\envs\myLocalGPT\lib\site-packages\gradio\utils.py", line 323, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\Daniel\.conda\envs\myLocalGPT\lib\site-packages\gradio\utils.py", line 692, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\private\myLocalGPT\llama.py", line 85, in bot
    inputs = tokenizer(instruction, return_tensors="pt").to(model.device)
  File "C:\Users\Daniel\.conda\envs\myLocalGPT\lib\site-packages\auto_gptq\modeling\_base.py", line 411, in device
    device = [d for d in self.hf_device_map.values() if d not in {'cpu', 'disk'}][0]
IndexError: list index out of range

```
:(
