### ISSUE TITLE
I am using mac os and getting this error despite having source documents in the folder

### ISSUE THREAD

**Issue by Sherlock2111** [PromtEngineer/localGPT#260]
The directory does not exist
Traceback (most recent call last):
  File "/Users/user01/localGPT/run_localGPT_API.py", line 53, in <module>
    raise FileNotFoundError(
FileNotFoundError: No files were found inside SOURCE_DOCUMENTS, please put a starter file inside before starting the API!

**Comment by Sherlock2111** [comment]
@PromtEngineer please look into this and reply ASAP

**Comment by Sherlock2111** [comment]
@PromtEngineer

**Comment by conacts** [comment]
My solution can be found [here](https://github.com/PromtEngineer/localGPT/pull/271). The issue was caused by not having a cuda device and cuda being default.

**Comment by Sherlock2111** [comment]
still not solved

**Comment by conacts** [comment]
@Sherlock2111 can you elaborate on your issue?

**Comment by Sherlock2111** [comment]
I am trying to run UI I did all the steps but it doesn’t run this the error I got
FileNotFoundError: No files were found inside SOURCE_DOCUMENTS, please put a starter file inside before starting the API!

**Comment by Sherlock2111** [comment]
where as I have put my files in the source folder already and code runs on cpu efficiently

**Comment by Sherlock2111** [comment]
please help

**Comment by conacts** [comment]
So if we look at the code, we notice the error you see is caused by 
```python
run_langest_commands = ["python", "ingest.py"]
...
result = subprocess.run(run_langest_commands, capture_output=True)
if result.returncode != 0:
    raise FileNotFoundError(
        "No files were found inside SOURCE_DOCUMENTS, please put a starter file inside before starting the API!"
    )
```

This means the issue lies in executing the `ingest.py` file. 

My issues (being on an M1 mac similar to you) came from cuda being the default. This caused the `ingest.py` program to exit with an error code. Although the error raised mentions the files in the SOURCE_DOCUMENTS folder, this is not a true representation of the error.

**Comment by davetwchiu** [comment]
Whenever I run "run_localGPT_API.py", the DB folder will mysteriously disappear.

**Comment by Sherlock2111** [comment]
@conacts so what is the solution?

**Comment by conacts** [comment]
@Sherlock2111 @davetwchiu  I am going to need more information to help solve the problem. For example, send me an example of you having the folder with the `.parquet` files from the given example. This is what my current directory looks like:

```
[cs@zsh] ~/junction/localGPT$ tree -L 2
.
├── ACKNOWLEDGEMENT.md
├── CONTRIBUTING.md
├── DB
│   ├── chroma-collections.parquet
│   └── chroma-embeddings.parquet
├── LICENSE
├── README.md
├── SOURCE_DOCUMENTS
│   └── constitution.pdf
├── __pycache__
│   └── constants.cpython-311.pyc
├── constants.py
├── ingest.py
├── localGPT
│   ├── bin
│   ├── lib
│   ├── pyvenv.cfg
│   └── share
├── localGPTUI
│   ├── localGPTUI.py
│   ├── static
│   └── templates
├── pyproject.toml
├── requirements.txt
├── run_localGPT.py
└── run_localGPT_API.py
```

Now could you run the `tree -L 2` command before and after running `python run_localGPT_API.py` and send me the results. 

Also, are you able to get the prompt to put in a question? This is what mine looks like:
```
...
AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 |

Enter a query:
```

**Comment by Sherlock2111** [comment]
File "/Users/user01/Library/Python/3.9/lib/python/site-packages/auto_gptq/nn_modules/qlinear/qlinear_cuda_old.py", line 83, in __init__
    self.autogptq_cuda = autogptq_cuda_256
NameError: name 'autogptq_cuda_256' is not defined

this the new error I'm getting

**Comment by Sherlock2111** [comment]
<img width="1792" alt="Screenshot 2023-07-29 at 1 13 13 PM" src="https://github.com/PromtEngineer/localGPT/assets/140428081/4b874461-cb40-45d7-9c0c-dacf5f8c6571">

**Comment by theworkerant** [comment]
@Sherlock2111 These scripts are a bit of mess in the current state of the repo. It seems the API script tries to re-run the `ingest.py` and blows away your DB in the mean time. I commented out the whole section about starting with `if os.path.exists(PERSIST_DIRECTORY)` all the way through line you see the SOURCE_DOCUMENTS error on (before `# load the vectorstore`)

My API at least runs at this point (still working on the UI...)
