### ISSUE TITLE
AutoGPTQForCausalLM has changed API?

### ISSUE THREAD

**Issue by cottrell** [PromtEngineer/localGPT#262]
Is there a version snap missing in this repo perhaps? Did the behaviour of the transformers package change?

If a manual download is required let's put that in the README with specifics of the version and files.

```2023-07-24 18:16:36,549 - INFO - run_localGPT.py:64 - Using AutoGPTQForCausalLM for quantized models
Traceback (most recent call last):
  File "/home/cottrell/dev/localGPT/run_localGPT.py", line 256, in <module>
    main()
  File "/home/cottrell/anaconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cottrell/anaconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/cottrell/anaconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cottrell/anaconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cottrell/dev/localGPT/run_localGPT.py", line 225, in main
    llm = load_model(device_type, model_id=model_id, model_basename=model_basename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cottrell/dev/localGPT/run_localGPT.py", line 70, in load_model
    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cottrell/anaconda3/envs/localGPT/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 720, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cottrell/anaconda3/envs/localGPT/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'TheBloke/Llama-2-7B-Chat-GGML'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'TheBloke/Llama-2-7B-Chat-GGML' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.
2023-07-24 18:16:37,519 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: /home/cottrell/dev/localGPT/DB
```

**Comment by gkielian** [comment]
+1 having similar error

**Comment by PromtEngineer** [comment]
@cottrell seems like you are trying to use the ggml model with cuda. If you are running this on gpu, then use the gptq models. There is a PR #253 to support ggml models on gpus. Testing that.
