### ISSUE TITLE
I followed the instructions in the setup but it always defaults to CPU

### ISSUE THREAD

**Issue by videogamingeducation** [PromtEngineer/localGPT#318]
CPU Utilization 88% and GPU is 0. I would like to know why thanks

**Comment by videogamingeducation** [comment]
![image](https://github.com/PromtEngineer/localGPT/assets/84913219/7f98d6c4-f992-4432-b6c1-9b0ae7559893)

**Comment by videogamingeducation** [comment]
![image](https://github.com/PromtEngineer/localGPT/assets/84913219/31a00ac4-46e1-4b2d-9e41-e5113e44bc32)

**Comment by andypotato** [comment]
Try running a GPTQ model instead of GGML.

Since you're running Windows / CUDA, you can use my install guide here:
https://github.com/PromtEngineer/localGPT/issues/287#issuecomment-1656545054

The current setup guide on the localGPT repo does not work.

**Comment by videogamingeducation** [comment]
I tried this

pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117

But it gave me errors when compling llama regarding cmake.

 × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [191 lines of output]


      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- The C compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
        No CMAKE_C_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
      -- The C compiler identification is MSVC 19.36.32537.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.36.32537.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (3.9s)
      -- Generating done (0.0s)
      -- Build files have been written to: C:/Users/ninop/AppData/Local/Temp/pip-install-7a4bs3ev/llama-cpp-python_b2f52bf5d34a485595a00401b20511e9/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build
        Command:
          'C:\Users\ninop\AppData\Local\Temp\pip-build-env-a40ny4aa\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9' -G 'Visual Studio 17 2022' --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.10.12 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\ninop\AppData\Local\Temp\pip-build-env-a40ny4aa\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\ninop\anaconda3\envs\localGPT\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\ninop\anaconda3\envs\localGPT\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\ninop\anaconda3\envs\localGPT\libs\python310.lib' '-DPython_EXECUTABLE:PATH=C:\Users\ninop\anaconda3\envs\localGPT\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\ninop\anaconda3\envs\localGPT' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Users\ninop\anaconda3\envs\localGPT\Include' '-DPython_LIBRARY:PATH=C:\Users\ninop\anaconda3\envs\localGPT\libs\python310.lib' '-DPython3_EXECUTABLE:PATH=C:\Users\ninop\anaconda3\envs\localGPT\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\ninop\anaconda3\envs\localGPT' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Users\ninop\anaconda3\envs\localGPT\Include' '-DPython3_LIBRARY:PATH=C:\Users\ninop\anaconda3\envs\localGPT\libs\python310.lib' -T v143 -A x64 -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
      -- The C compiler identification is MSVC 19.36.32537.0
      -- The CXX compiler identification is MSVC 19.36.32537.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - broken
      CMake Error at C:/Users/ninop/AppData/Local/Temp/pip-build-env-a40ny4aa/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: 'C:/Users/ninop/AppData/Local/Temp/pip-install-7a4bs3ev/llama-cpp-python_b2f52bf5d34a485595a00401b20511e9/_skbuild/win-amd64-3.10/cmake-build/CMakeFiles/CMakeScratch/TryCompile-d2sgnj'

          Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_9ebd6.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
          MSBuild version 17.6.3+07e294721 for .NET Framework
          Build started 7/30/2023 11:32:32 AM.

          Project "C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj" on node 1 (default targets).
          PrepareForBuild:
            Creating directory "cmTC_9ebd6.dir\Debug\".
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
            Creating directory "C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\Debug\".
            Creating directory "cmTC_9ebd6.dir\Debug\cmTC_9ebd6.tlog\".
          InitializeBuildStatus:
            Creating "cmTC_9ebd6.dir\Debug\cmTC_9ebd6.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
          ClCompile:
            C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_9ebd6.dir\Debug\\" /Fd"cmTC_9ebd6.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\testCCompiler.c"
            Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32537 for x64
            testCCompiler.c
            Copyright (C) Microsoft Corporation.  All rights reserved.
            cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_9ebd6.dir\Debug\\" /Fd"cmTC_9ebd6.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\testCCompiler.c"
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: The specified task executable "CL.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.dir\Debug\cmTC_9ebd6.tlog'. [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          Done Building Project "C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj" (default targets) -- FAILED.

          Build FAILED.

          "C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj" (default target) (1) ->
          (PrepareForBuild target) ->
            C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]


          "C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj" (default target) (1) ->
          (ClCompile target) ->
            C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: The specified task executable "CL.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.dir\Debug\cmTC_9ebd6.tlog'. [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-d2sgnj\cmTC_9ebd6.vcxproj]

              1 Warning(s)
              1 Error(s)

          Time Elapsed 00:00:00.22





        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (project)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\ninop\AppData\Local\Temp\pip-build-env-a40ny4aa\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
        File "C:\Users\ninop\AppData\Local\Temp\pip-build-env-a40ny4aa\overlay\Lib\site-packages\skbuild\cmaker.py", line 357, in configure
          raise SKBuildError(msg)

      An error occurred while configuring with CMake.
        Command:
          'C:\Users\ninop\AppData\Local\Temp\pip-build-env-a40ny4aa\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9' -G 'Visual Studio 17 2022' --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.10.12 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\ninop\AppData\Local\Temp\pip-build-env-a40ny4aa\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\ninop\anaconda3\envs\localGPT\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\ninop\anaconda3\envs\localGPT\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\ninop\anaconda3\envs\localGPT\libs\python310.lib' '-DPython_EXECUTABLE:PATH=C:\Users\ninop\anaconda3\envs\localGPT\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\ninop\anaconda3\envs\localGPT' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Users\ninop\anaconda3\envs\localGPT\Include' '-DPython_LIBRARY:PATH=C:\Users\ninop\anaconda3\envs\localGPT\libs\python310.lib' '-DPython3_EXECUTABLE:PATH=C:\Users\ninop\anaconda3\envs\localGPT\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\ninop\anaconda3\envs\localGPT' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Users\ninop\anaconda3\envs\localGPT\Include' '-DPython3_LIBRARY:PATH=C:\Users\ninop\anaconda3\envs\localGPT\libs\python310.lib' -T v143 -A x64 -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9
        Working directory:
          C:\Users\ninop\AppData\Local\Temp\pip-install-7a4bs3ev\llama-cpp-python_b2f52bf5d34a485595a00401b20511e9\_skbuild\win-amd64-3.10\cmake-build
      Please see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

**Comment by andypotato** [comment]
Try to remove the llama-cpp-python from requirements.txt and install it manually like this:
```
pip install llama_cpp_python_cuda-0.1.73+cu117-cp310-cp310-win_amd64.whl
```

**If that doesn't work, you need to build it from source:**

Run your Visual Studio installer and make sure you have the following components installed:

- MSVC VS 2022 C++ x64/x86 build tools
- Windows 10/11 SDK
- C++ Universal Windows Platform support
- C++ CMake tools for Windows

Then run:

```
set LLAMA_CUBLAS=1
set CMAKE_ARGS=-DLLAMA_CUBLAS=on
set FORCE_CMAKE=1
pip install llama-cpp-python==0.1.68 --no-cache-dir --verbose
```

Note that you only need llama.cpp for loading GGML models. If you're running GPTQ models, I believe you could remove it altogether. Also if using GGML, make sure to set the GPU layers according to your GPUs VRAM otherwise you will not see any GPU usage at all.

Good luck!

**Comment by KonradHoeffner** [comment]
I even had to use `CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install --upgrade --force-reinstall llama-cpp-python` to get this to work at all.

**Comment by KonradHoeffner** [comment]
I think a warning message would be helpful in the GGML case where BLAS is not available.
