### ISSUE TITLE
Error while quering the model

### ISSUE THREAD

**Issue by samsonthomas951** [PromtEngineer/localGPT#342]
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: mem required  = 5407.71 MB (+ 1026.00 MB per state)
llama_new_context_with_model: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 

Enter a query: what is life ?
Traceback (most recent call last):
  File "/content/localGPT/run_localGPT.py", line 278, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/content/localGPT/run_localGPT.py", line 256, in main
    res = qa(query)
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/retrieval_qa/base.py", line 119, in _call
    docs = self._get_docs(question)
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/retrieval_qa/base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/base.py", line 376, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/chroma.py", line 182, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/chroma.py", line 230, in similarity_search_with_score
    results = self.__query_collection(
  File "/usr/local/lib/python3.10/dist-packages/langchain/utils.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/chroma.py", line 121, in __query_collection
    return self._collection.query(
  File "/usr/local/lib/python3.10/dist-packages/chromadb/api/models/Collection.py", line 219, in query
    return self._client._query(
  File "/usr/local/lib/python3.10/dist-packages/chromadb/api/local.py", line 408, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "/usr/local/lib/python3.10/dist-packages/chromadb/db/clickhouse.py", line 583, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "/usr/local/lib/python3.10/dist-packages/chromadb/db/index/hnswlib.py", line 230, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying
2023-08-06 12:06:53,951 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: /content/localGPT/DB

_is there any solution to this problem?_ **Help me solve it **

**Comment by eagleEggs** [comment]
I believe I received this when I hadn't ingested any data with ingest.py - It ingests files from the source folder [/SOURCE_DOCUMENTS] which you have to add files to.
