### ISSUE TITLE
ERROR - chroma.py:129 - Chroma collection langchain contains fewer than 2 elements.

### ISSUE THREAD

**Issue by irshad001** [PromtEngineer/localGPT#343]
I have a `.csv` dataset (having more than 100K observations and 6 columns) that I have ingested using the `ingest.py` function. However, when I run the run_LocalGPT.py and ask questions about the dataset I get the below errors. 

2023-08-06 20:09:28,829 - ERROR - chroma.py:129 - Chroma collection langchain contains fewer than 4 elements.
2023-08-06 20:09:28,840 - ERROR - chroma.py:129 - Chroma collection langchain contains fewer than 3 elements.
2023-08-06 20:09:28,841 - ERROR - chroma.py:129 - Chroma collection langchain contains fewer than 2 elements.

Also, I suspect that the embedding is not happening properly. Can anyone please confirm what is going wrong?

When I ask how many how observations are there in the dataset it says only 1 observation.

**Comment by alexfilothodoros** [comment]
Hi.
I think there is an issue with loading CSV files.
Probably only the first line is read.
I had the same issue and this thread helped me.

https://github.com/imartinez/privateGPT/pull/560


If you want, you could prepare a sample file and see if I can read it.

Cheers

**Comment by irshad001** [comment]
Hi @alexfilothodoros,

Thank you for your response. 

I tried to use the fix from https://github.com/imartinez/privateGPT/pull/560  but it is throwing the below errors:


`Traceback (most recent call last):
  File "/Workspace/ubixGPT/ingest.py", line 161, in <module>
    main()
  File "/Workspace/llama_venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Workspace/llama_venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Workspace/llama_venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Workspace/llama_venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Workspace/ubixGPT/ingest.py", line 130, in main
    texts = text_splitter.split_documents(text_documents)
  File "/Workspace/llama_venv/lib/python3.9/site-packages/langchain/text_splitter.py", line 102, in split_documents
    texts.append(doc.page_content)
AttributeError: 'list' object has no attribute 'page_content'`


Here's a sample of the data I am using:

`A,B,C,D,E,data_type,profit,sales
A1,B1,Atlanta,GA,2017/12/24,training,24.96,49.92
A1,B1,Atlanta,GA,2017/12/24,training,24.96,35.88
A2,B1,Atlanta,GA,2017/12/24,training,24.96,85.80
A2,B1,Atlanta,GA,2017/12/24,training,17.94,49
A2,B1,Atlanta,GA,2017/12/24,training,17.94,35
A2,B1,Atlanta,GA,2017/12/24,training,17.94,85
A2,B1,Atlanta,GA,2017/12/24,training,42.90,49
A2,B1,Atlanta,GA,2017/12/24,training,42.90,35
A2,B1,Atlanta,GA,2017/12/24,training,42.90,85`

**Comment by alexfilothodoros** [comment]
Hi @irshad001 

I will try with your data, but after 15.08.

I hope it's nothing urgent.

**Comment by irshad001** [comment]
Hi @alexfilothodoros 
That is fine. Thank you for offering help. Appreciate it.

**Comment by jianjye** [comment]
I'm having the same issue with a CSV file as well. Seems like only the first row is ingested. My actual CSV have about 24k rows x 4 columns, but I was able to reproduce the issue even with just 10 rows. 

Sample data:
```
acquisition,acquiree,acquirer,price
GrandCentral acquired by Google,GrandCentral,Google,60000000.0
Last.fm acquired by CBS Entertainment,Last.fm,CBS Entertainment,280000000.0
FeedBurner acquired by Google,FeedBurner,Google,100000000.0
PayPal acquired by eBay,PayPal,eBay,1500000000.0
WallStrip acquired by CBS Entertainment,WallStrip,CBS Entertainment,5000000.0
Snapfish acquired by HP,Snapfish,HP,300000000.0
Pickle acquired by Scripps Networks,Pickle,Scripps Networks,4100000.0
Musicmatch acquired by Yahoo,Musicmatch,Yahoo,160000000.0
Shopzilla acquired by The E.W. Scripps Company,Shopzilla,The E.W. Scripps Company,560000000.0
```

**Comment by alexfilothodoros** [comment]
Hi @jianjye 

Could you, please, try with this file? I get a "index corrupted" error with your data.

This file works on me. Ask it something like "what color is dog7?"

[dogs.csv](https://github.com/PromtEngineer/localGPT/files/12356384/dogs.csv)

**Comment by jianjye** [comment]
Here you go: [acquisitions.csv](https://github.com/PromtEngineer/localGPT/files/12360752/acquisitions.csv)

https://github.com/imartinez/privateGPT/pull/560 didn't work for me. Changing `load_single_document()` as per the diff gives me this error: 
```
AttributeError: 'list' object has no attribute 'metadata'
``` 

Thanks for looking into this 🙏

**Comment by irshad001** [comment]
Thank you so much for your response @alexfilothodoros

I am also getting the same error as @jianjye. 

`AttributeError: 'list' object has no attribute 'metadata'`

**Comment by alexfilothodoros** [comment]
Hi everyone!

Yes, the issue is with the CSV loader.
I have implemented  the https://github.com/imartinez/privateGPT/pull/560 and it's working.

@jianjye This is with your file.


![vsc](https://github.com/PromtEngineer/localGPT/assets/6419847/44416536-f2b2-487d-9651-1fe127177abd)

@PromtEngineer Not sure how to proceed with this fix. This is someone else's work and I wouldn't like to take the credit for it.

**Comment by IrshadUbix** [comment]
Hi @alexfilothodoros ,

I implemented those https://github.com/imartinez/privateGPT/pull/560 issue changes in my `ingest.py` file from localGPT but it threw following error:

`Traceback (most recent call last):
  File "/{Path}/localGPT/ingest.py", line 161, in <module>
    main()
  File "/{Path}/llama_venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/{Path}/llama_venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/{Path}/llama_venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Workspace/llama_venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/{Path}/localGPT/ingest.py", line 130, in main
    texts = text_splitter.split_documents(text_documents)
  File "/{Path}/llama_venv/lib/python3.9/site-packages/langchain/text_splitter.py", line 112, in split_documents
    texts.append(doc.page_content)
AttributeError: 'list' object has no attribute 'page_content'`


I also tried directly using `ingest.py` file from privateGPT inside the localGPT project. However, it threw following error:

`Traceback (most recent call last):
  File "/{Path}/localGPT/ingest_priv.py", line 166, in <module>
    main()
  File "/{Path}/localGPT/ingest_priv.py", line 143, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "/{Path}/llama_venv/lib/python3.9/site-packages/langchain/embeddings/huggingface.py", line 49, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceEmbeddings
model_name
  none is not an allowed value (type=type_error.none.not_allowed)`

Can you please share your version of `ingest.py`

**Comment by irshad001** [comment]
Hi @alexfilothodoros ,

I implemented those https://github.com/imartinez/privateGPT/pull/560 issue changes in my ingest.py file from localGPT but it threw following error:

`Traceback (most recent call last): File "/{Path}/localGPT/ingest.py", line 161, in <module> main() File "/{Path}/llama_venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__ return self.main(*args, **kwargs) File "/{Path}/llama_venv/lib/python3.9/site-packages/click/core.py", line 1078, in main rv = self.invoke(ctx) File "/{Path}/llama_venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) File "/Workspace/llama_venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke return __callback(*args, **kwargs) File "/{Path}/localGPT/ingest.py", line 130, in main texts = text_splitter.split_documents(text_documents) File "/{Path}/llama_venv/lib/python3.9/site-packages/langchain/text_splitter.py", line 112, in split_documents texts.append(doc.page_content) AttributeError: 'list' object has no attribute 'page_content'`

I also tried directly using `ingest.py` file from **privateGPT** inside the **localGPT** project. However, it threw the following error:

`Traceback (most recent call last): File "/{Path}/localGPT/ingest_priv.py", line 166, in <module> main() File "/{Path}/localGPT/ingest_priv.py", line 143, in main embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name) File "/{Path}/llama_venv/lib/python3.9/site-packages/langchain/embeddings/huggingface.py", line 49, in __init__ super().__init__(**kwargs) File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__ pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceEmbeddings model_name none is not an allowed value (type=type_error.none.not_allowed)`

Can you please share your version of `ingest.py`

**Comment by alexfilothodoros** [comment]
@jianjye @irshad001 
Here's a quick and dirty adaptation, of https://github.com/imartinez/privateGPT/pull/560, to localgpt. https://github.com/alexfilothodoros/localGPT/blob/main/ingest.py

**Comment by irshad001** [comment]
Hi @alexfilothodoros ,
Thank you so much when I tried this on `dogs.csv` file i am getting the following error:

```2023-08-18 21:04:17,069 - INFO - ingest.py:111 - Loading documents from /Workspace/localGPT/SOURCE_DOCUMENTS
Loading new documents:   0%|                              | 0/1 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Workspace/localGPT/ingest.py", line 32, in load_single_document
    loader_class, loader_args = DOCUMENT_MAP[ext]
TypeError: cannot unpack non-iterable ABCMeta object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Workspace/localGPT/ingest.py", line 142, in <module>
    main()
  File "/Workspace/llama_venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Workspace/llama_venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Workspace/llama_venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Workspace/llama_venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Workspace/localGPT/ingest.py", line 112, in main
    documents = load_documents(SOURCE_DIRECTORY)
  File "/Workspace/localGPT/ingest.py", line 59, in load_documents
    for i, docs in enumerate(pool.imap_unordered(load_single_document, filtered_files)):
  File "/opt/conda/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
TypeError: cannot unpack non-iterable ABCMeta object```

**Comment by jianjye** [comment]
@alexfilothodoros Thanks for taking a look at this! I tried the updated ingest.py with both `dogs.csv` and my own `acquisitions.csv`, I get the same error as @irshad001 unfortunately. 

May I know if you folks are using Windows or Mac? Python 3.9 or 3.10? I have a feeling that this is something lower level.

**Comment by irshad001** [comment]
I am using Ubuntu, VERSION="20.04.6"
Python 3.9.12
GCC 7.5.0

**Comment by alexfilothodoros** [comment]
I am using Win10
python 3.11.4

**Comment by irshad001** [comment]
@alexfilothodoros, for you it is running fine I gather with your modifications to the `ingest.py` file. Am I correct to assume that?

**Comment by alexfilothodoros** [comment]
Hi,

I will try to upload a new version in my fork today.

**Comment by alexfilothodoros** [comment]
Hi @irshad001  @jianjye 

Could you please try running again ingest from my fork? If you clone it, you will find the dogs.csv in the SOURCE_DIRECTORY already.

**Comment by irshad001** [comment]
I got constants2 not found error at first. So tried I installing it but couldn't as according to my package distribution there's not package like that. So I changed the following code 
from:

```
from constants2 import (
    CHROMA_SETTINGS,
    DOCUMENT_MAP,
    EMBEDDING_MODEL_NAME,
    INGEST_THREADS,
    PERSIST_DIRECTORY,
    SOURCE_DIRECTORY,
)
```

to:
```
from constants import (
    CHROMA_SETTINGS,
    DOCUMENT_MAP,
    EMBEDDING_MODEL_NAME,
    INGEST_THREADS,
    PERSIST_DIRECTORY,
    SOURCE_DIRECTORY,
)
```

and ran python ingest.py and I get the following error:
```
 python ingest.py
2023-08-21 12:00:45,335 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
Downloading (…)c7233/.gitattributes: 100%|██████████████████████████████████████████████| 1.48k/1.48k [00:00<00:00, 235kB/s]
Downloading (…)_Pooling/config.json: 100%|█████████████████████████████████████████████████| 270/270 [00:00<00:00, 55.8kB/s]
Downloading (…)/2_Dense/config.json: 100%|██████████████████████████████████████████████████| 116/116 [00:00<00:00, 118kB/s]
Downloading pytorch_model.bin: 100%|████████████████████████████████████████████████████| 3.15M/3.15M [00:00<00:00, 211MB/s]
Downloading (…)9fb15c7233/README.md: 100%|█████████████████████████████████████████████| 66.3k/66.3k [00:00<00:00, 42.3MB/s]
Downloading (…)b15c7233/config.json: 100%|█████████████████████████████████████████████| 1.53k/1.53k [00:00<00:00, 2.27MB/s]
Downloading (…)ce_transformers.json: 100%|██████████████████████████████████████████████████| 122/122 [00:00<00:00, 215kB/s]
Downloading pytorch_model.bin: 100%|████████████████████████████████████████████████████| 1.34G/1.34G [00:02<00:00, 475MB/s]
Downloading (…)nce_bert_config.json: 100%|███████████████████████████████████████████████| 53.0/53.0 [00:00<00:00, 24.9kB/s]
Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████████████| 2.20k/2.20k [00:00<00:00, 2.86MB/s]
Downloading spiece.model: 100%|███████████████████████████████████████████████████████████| 792k/792k [00:00<00:00, 379MB/s]
Downloading (…)c7233/tokenizer.json: 100%|█████████████████████████████████████████████| 2.42M/2.42M [00:00<00:00, 62.5MB/s]
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████| 2.41k/2.41k [00:00<00:00, 2.97MB/s]
Downloading (…)15c7233/modules.json: 100%|██████████████████████████████████████████████████| 461/461 [00:00<00:00, 794kB/s]
2023-08-21 12:00:50,509 - INFO - instantiator.py:21 - Created a temporary directory at /tmp/tmpa67zld3h
2023-08-21 12:00:50,509 - INFO - instantiator.py:76 - Writing /tmp/tmpa67zld3h/_remote_module_non_scriptable.py
Traceback (most recent call last):
  File "/Workspace/localGPT/ingest.py", line 126, in <module>
    main()
  File "/Workspace/localGPT/ingest.py", line 100, in main
    embeddings = HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL_NAME)
  File "/Workspace/llama_venv/lib/python3.9/site-packages/langchain/embeddings/huggingface.py", line 59, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "/Workspace/llama_venv/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "/Workspace/llama_venv/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/Workspace/llama_venv/lib/python3.9/site-packages/sentence_transformers/models/Pooling.py", line 120, in load
    return Pooling(**config)
TypeError: __init__() got an unexpected keyword argument 'pooling_mode_weightedmean_tokens'
```

**Comment by irshad001** [comment]
Hi @jianjye did you try the fork code?

**Comment by alexfilothodoros** [comment]
oops I forgot to upload another version of the constants script.
I was experimenting with changing the document_map and it seems that I missed something.

I will fix it tomorrow.

The TypeError that you get is strange. Maybe @PromtEngineer  can think of something?

**Comment by alexfilothodoros** [comment]
Hi
I made some tiny changes in my fork. Then I cloned it and I was able to run it.

I cannot reproduce the  `pooling_mode_weightedmean_tokens` error.

**Comment by irshad001** [comment]
Hi @alexfilothodoros ,

Thank you so much. I was able to ingest data without any errors this time. However, the problem is in the LLM model. I am using Llama2-7B-GPTQ model.
<img width="707" alt="Screenshot 2023-08-23 053510" src="https://github.com/PromtEngineer/localGPT/assets/7187635/c2afb895-7f7e-4dfb-89f2-a1f4e492d742">

**Comment by alexfilothodoros** [comment]
I am glad that ingesting is working!

**Comment by jianjye** [comment]
Thanks @alexfilothodoros! I can confirm that the ingestion works!

**Comment by alexfilothodoros** [comment]
Great! Glad to hear that :)

**Comment by alexfilothodoros** [comment]
@irshad001 

I think the LLM  problem you are mentioning, might get more attention if you make a open a new issue.
