### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file for 'C:\Users\xxxxx/.cache\torch\sentence_transformers\hkunlp_instructor-large\pytorch_model.bin'

### ISSUE THREAD

**Issue by br76530067** [PromtEngineer/localGPT#345]
Hi everyone, after "python ingest.py --device_type cuda", I ran the "python run_localGPT.py", then I got below exception Traceback:

`(localGPT) C:\Work_Project\LLM\repo_localGOT\localGPT>python run_localGPT.py
C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
2023-08-07 10:56:00,078 - INFO - run_localGPT.py:180 - Running on: cpu
2023-08-07 10:56:00,078 - INFO - run_localGPT.py:181 - Display Source Documents set to: False
2023-08-07 10:56:00,976 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
Traceback (most recent call last):
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\transformers\modeling_utils.py", line 460, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\transformers\modeling_utils.py", line 464, in load_state_dict
    if f.read(7) == "version":
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1821: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Work_Project\LLM\repo_localGOT\localGPT\run_localGPT.py", line 278, in <module>
    main()
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Work_Project\LLM\repo_localGOT\localGPT\run_localGPT.py", line 183, in main
    embeddings = HuggingFaceInstructEmbeddings(model_name=EMBEDDING_MODEL_NAME, model_kwargs={"device": device_type})
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\langchain\embeddings\huggingface.py", line 137, in __init__
    self.client = INSTRUCTOR(
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\InstructorEmbedding\instructor.py", line 474, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\InstructorEmbedding\instructor.py", line 306, in load
    return INSTRUCTOR_Transformer(model_name_or_path=input_path, **config)
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\InstructorEmbedding\instructor.py", line 240, in __init__
    self._load_model(self.model_name_or_path, config, cache_dir, **model_args)
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\sentence_transformers\models\Transformer.py", line 47, in _load_model
    self._load_t5_model(model_name_or_path, config, cache_dir)
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\sentence_transformers\models\Transformer.py", line 55, in _load_t5_model
    self.auto_model = T5EncoderModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\transformers\modeling_utils.py", line 2629, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "C:\Work_Software\Miniconda\envs\localGPT\lib\site-packages\transformers\modeling_utils.py", line 476, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'C:\Users\xxxxx/.cache\torch\sentence_transformers\hkunlp_instructor-large\pytorch_model.bin' at 'C:\Users\xxxxx/.cache\torch\sentence_transformers\hkunlp_instructor-large\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.`

Could you please help me to trouble shut?

Looks like it involves some problem with the file loading....

**Comment by BMartinezS** [comment]
Same problem here

**Comment by PromtEngineer** [comment]
which model are you trying to run? seems like the run_locaGPT.py is running on cpu instead of gpu.

**Comment by ammorcos** [comment]
Same problem here, only with quantized models though

**Comment by br76530067** [comment]
> which model are you trying to run? seems like the run_locaGPT.py is running on cpu instead of gpu.

Sorry for basic question, How could I check which model I am using?

looks like it will load the  pytorch_model.bin here,

hope your feedback

**Comment by br76530067** [comment]
hello, is there any comments? thanks

**Comment by br76530067** [comment]
Is there any news?

**Comment by br76530067** [comment]
> Same problem here

Have you solved it?
