### ISSUE TITLE
requirements.txt missing unstructured module

### ISSUE THREAD

**Issue by kpbird** [PromtEngineer/localGPT#346]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ketanparmar/Code/Experiments/AI/localGPT/ingest.py", line 159, in <module>
    main()
  File "/usr/local/anaconda3/lib/python3.11/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ketanparmar/Code/Experiments/AI/localGPT/ingest.py", line 122, in main
    documents = load_documents(SOURCE_DIRECTORY)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ketanparmar/Code/Experiments/AI/localGPT/ingest.py", line 71, in load_documents
    contents, _ = future.result()
                  ^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
ModuleNotFoundError: No module named 'unstructured'

**Comment by kpbird** [comment]
PR for the issue https://github.com/PromtEngineer/localGPT/pull/347

**Comment by PromtEngineer** [comment]
@kpbird thanks, just merged it.
