### ISSUE TITLE
DB Folder is missing while running run_localGPT_API.py

### ISSUE THREAD

**Issue by sameerudayjoshi** [PromtEngineer/localGPT#377]
Hi,

I have been working on developing this solution as given. On Windows with just CPU, it works perfectly. fine. 
On the Ubuntu VM Server hosted on Azure VM resources, I ran the following commands:
sudo python3.8 ingest.py.
It ran successfully and the DB folder got created. 
For creating the UI, I then ran the following: 
sudo python3.8 run_localGPT_API.py
Here interestingly now I am getting the following stack trace error: 
load INSTRUCTOR_Transformer
max_seq_length  512
The directory does not exist
CompletedProcess(args=['python', 'ingest.py', '--device_type', 'cpu'], returncode=1, stdout=b'', stderr=b'  File "ingest.py", line 24\n    def load_single_document(file_path: str) -> Document:\n                                      ^\nSyntaxError: invalid syntax\n')
Traceback (most recent call last):
  File "run_localGPT_API.py", line 55, in <module>
    raise FileNotFoundError(
FileNotFoundError: No files were found inside SOURCE_DOCUMENTS, please put a starter file inside before starting the API!

And I checked for the folder in the path and the DB file was missing. Kindly assist further.
I have tried running the queries with sudo and I get alot of issues with permissions which I do not have on the system.

**Comment by sameerudayjoshi** [comment]
@PromtEngineer Can you provide a review on why the folder might get deleted under the sudo command line orders?

**Comment by prashant4961** [comment]
same error i got even though the source document folder has a file.
Traceback (most recent call last):
  File "D:\learn\localGPT_llama2_1\run_localGPT_API.py", line 54, in <module>
    raise FileNotFoundError(
FileNotFoundError: No files were found inside SOURCE_DOCUMENTS, please put a starter file inside before starting the API!

**Comment by RajendranDinesh** [comment]
You're running `ingest.py` outside your virtual environment, which is causing the missing files and import errors. To fix it, change this line:

```python
run_langest_commands = ["python", "ingest.py"]
```

to:

```python
run_langest_commands = [r"path\to\your\virtual\env\Scripts\python.exe", "ingest.py"]
```

Replace `path\to\your\virtual\env` with your actual virtual environment path.

Feel free to adapt the response based on the specific virtual environment tool being used and any other details you have.

This should resolve the issue. Let me know if it works!

**Comment by bp020108** [comment]
you mean below path i need to change like below?

run_langest_commands = [r"/home/fabtool/anaconda3/envs/localgpt2_llama2\Scripts\python.exe", "ingest.py"]

(localgpt_llama2) fabtool@XX02:~/localgpt_llama2$ conda env list
# conda environments:
#
base                     /home/fabtool/anaconda3
cas                      /home/fabtool/anaconda3/envs/cas
localgpt2_llama2         /home/fabtool/anaconda3/envs/localgpt2_llama2
localgpt_llama2       *  /home/fabtool/anaconda3/envs/localgpt_llama2

(localgpt_llama2) fabtool@MTN58R01C002:~/localgpt_llama2$

**Comment by RajendranDinesh** [comment]
@bp020108 Yeah Something Like That Should Work, 
Can You Try and Let Me Know Whether That Works?.

**Comment by holyvslin** [comment]
> You're running `ingest.py` outside your virtual environment, which is causing the missing files and import errors. To fix it, change this line (from `run_localGPT_API.py`, line number => **_47_**):
> 
> ```python
> run_langest_commands = ["python", "ingest.py"]
> ```
> 
> to:
> 
> ```python
> run_langest_commands = [r"path\to\your\virtual\env\Scripts\python.exe", "ingest.py"]
> ```
> 
> Replace `path\to\your\virtual\env` with your actual virtual environment path.
> 
> Feel free to adapt the response based on the specific virtual environment tool being used and any other details you have.
> 
> This should resolve the issue. Let me know if it works!

**Verified**, Root cause of this issue is that "python ingest.py" python is called from your system default python version, is not called from Conda path when you run ~/localGPT/run_localGPT_API.py
For my case:
Conda Python is located here:
# ls -l /root/miniconda3/bin/python
 **/root/miniconda3/bin/python** -> python3.11
So change run_localGPT_API.py line below 
run_langest_commands = ["python", "ingest.py"] 
to 
run_langest_commands = ["**/root/miniconda3/bin/python**", "ingest.py"]

So works, Thanks

**Comment by bp020108** [comment]
Ok I will try this and let you know. 
Do you know if we add new documents in Source documents directory then how can we run ingest.py file for new docs only to make it faster? 
I have seen issue where adding new docs and ingesting again not only takes time but it doesn't give answer from old docs (looks like overwriting but only taking new docs only and deleting existing ingest). Please help here if any idea.

**Comment by Fabbiologia** [comment]
I have a similar issue, ingest.py and run_localGPT.py work very well. It just give the error on the API. 
I tested changing the folder within the script to my conda python path but it is not solving the problem for me.

**Comment by bp020108** [comment]
it worked for me (looks like no error so far)
I have used below path: @holyvslin - ii is okay right? 

run_langest_commands = ["/home/fabtool/anaconda3/envs/localgpt_llama2/bin/python3.11", "ingest.py"]

**Comment by Fabbiologia** [comment]
ok... I used the path below: 

run_langest_commands = ["/home/humbolt/miniconda3/envs/localgpt_api/bin/python", "ingest.py"]

and still gives FileNotFoundError

**Comment by bp020108** [comment]
Can you show complete error output.

Please check if you have really that python in that folder? And use
correct  python version.

**Comment by Fabbiologia** [comment]
Error output:
`(localgpt_api) humbolt@humbolt-XPS-15-7590:~/localGPT$ python run_localGPT_API.py --device_type cpu
load INSTRUCTOR_Transformer
max_seq_length  512
The directory does not exist
Traceback (most recent call last):
  File "/home/humbolt/localGPT/run_localGPT_API.py", line 54, in <module>
    raise FileNotFoundError(
FileNotFoundError: No files were found inside SOURCE_DOCUMENTS, please put a starter file inside before starting the API!`


Python folder structure output: 
`(base) humbolt@humbolt-XPS-15-7590:~/miniconda3/bin$ pwd
/home/humbolt/miniconda3/bin
(base) humbolt@humbolt-XPS-15-7590:~/miniconda3/bin$ ls -l | grep python
lrwxrwxrwx 1 humbolt humbolt       10 Aug 22 00:15 python -> python3.10
lrwxrwxrwx 1 humbolt humbolt       10 Aug 22 00:15 python3 -> python3.10
lrwxrwxrwx 1 humbolt humbolt       10 Aug 22 00:15 python3.1 -> python3.10
-rwxrwxr-x 1 humbolt humbolt 17210536 Aug 22 00:15 python3.10
-rwxrwxr-x 1 humbolt humbolt     3489 Aug 22 00:15 python3.10-config
lrwxrwxrwx 1 humbolt humbolt       17 Aug 22 00:15 python3-config -> python3.10-config
`

**Comment by Fabbiologia** [comment]
yes I have the consitution document I also tested by adding other docs. when I go through workflow for run_localGPT.py it works like a charm. It is with the API that gives the error. Maybe my environment mixes up python versions? 

I am also using cpu option to run as i am testing in a pc with poor gpu

**Comment by holyvslin** [comment]
> **Error output:** `(localgpt_api) humbolt@humbolt-XPS-15-7590:~/localGPT$ python run_localGPT_API.py --device_type cpu
> 
> load INSTRUCTOR_Transformer
> 
> max_seq_length 512
> 
> The directory does not exist
> 
> Traceback (most recent call last): File "/home/humbolt/localGPT/run_localGPT_API.py", line 54, in raise FileNotFoundError( FileNotFoundError: No files were found inside SOURCE_DOCUMENTS, please put a starter file inside before starting the API!`
> 
> **Python folder structure output:** (base) humbolt@humbolt-XPS-15-7590:~/miniconda3/bin$ pwd
> 
> /home/humbolt/miniconda3/bin
> 
> (base) humbolt@humbolt-XPS-15-7590:~/miniconda3/bin$ ls -l | grep python
> 
> lrwxrwxrwx 1 humbolt humbolt 10 Aug 22 00:15 python -> python3.10 lrwxrwxrwx 1 humbolt humbolt 10 Aug 22 00:15 python3 -> python3.10 lrwxrwxrwx 1 humbolt humbolt 10 Aug 22 00:15 python3.1 -> python3.10 -rwxrwxr-x 1 humbolt humbolt 17210536 Aug 22 00:15 python3.10 -rwxrwxr-x 1 humbolt humbolt 3489 Aug 22 00:15 python3.10-config lrwxrwxrwx 1 humbolt humbolt 17 Aug 22 00:15 python3-config -> python3.10-config

1. check path and files exist really
2. could change DOCS PATH with absolute path directly
e.g. `SOURCE_DIRECTORY = "~/localGPT/SOURCE_DOCUMENTS" `
3. keep same python(version/path) **inside** run_localGPT_API.py which you already run run_localGPT_API.py successfully.
Pls have a try again. should worked. Just Python version should be aligned with Conda's one. :)

**Comment by holyvslin** [comment]
> Ok I will try this and let you know. Do you know if we add new documents in Source documents directory then how can we run ingest.py file for new docs only to make it faster? I have seen issue where adding new docs and ingesting again not only takes time but it doesn't give answer from old docs (looks like overwriting but only taking new docs only and deleting existing ingest). Please help here if any idea.

Put both documents in **SOURCE_DOCUMENTS**， then run ingest.py, both should be added in DB for later Query. 
Also you could try use UI option, the new document upload will trigger DB update directly, then conversation is ready with the new documents. And 2 function, 1st is Add(old ones + new ) and 2nd is Reset(just new). Web UI capture as below:

![image](https://github.com/PromtEngineer/localGPT/assets/43088535/bd37f88e-4207-4283-b353-0396a0b1b364)
