### ISSUE TITLE
run_localGPT_API.py  file errors.

### ISSUE THREAD

**Issue by prashant4961** [PromtEngineer/localGPT#381]
@PromtEngineer Please help!!
while running run_localGPT_API.py the **### db automatically disappears** and the **### error is of source document** is not present even tough it is present however when i am running run_localGPT.py it is working totally fine.

### **error as follows:**
(localgpt_llama2_1) D:\learn\localGPT_llama2_1>python run_localGPT_API.py
load INSTRUCTOR_Transformer
max_seq_length  512
CompletedProcess(args=['python', 'ingest.py'], returncode=1, stdout=b'', stderr=b'Traceback (most recent call last):\r\n  File "D:\\learn\\localGPT_llama2_1\\ingest.py", line 9, in <module>\r\n    from langchain.text_splitter import Language, RecursiveCharacterTextSplitter\r\nImportError: cannot import name \'Language\' from \'langchain.text_splitter\' (C:\\Users\\user_name\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\langchain\\text_splitter.py)\r\n')

Traceback (most recent call last):
  File "D:\learn\localGPT_llama2_1\run_localGPT_API.py", line 56, in <module>
    raise FileNotFoundError(
FileNotFoundError: No files were found inside SOURCE_DOCUMENTS, please put a starter file inside before starting the API!

**Comment by tunisha-factacy** [comment]
yaa same issue is also faced by me

**Comment by RajendranDinesh** [comment]
You're running `ingest.py` outside your virtual environment, which is causing the missing files and import errors. To fix it, change this line:

```python
run_langest_commands = ["python", "ingest.py"]
```

to:

```python
run_langest_commands = [r"path\to\your\virtual\env\Scripts\python.exe", "ingest.py"]
```

Replace `path\to\your\virtual\env` with your actual virtual environment path.

Feel free to adapt the response based on the specific virtual environment tool being used and any other details you have.

This should resolve the issue. Let me know if it works!

**Comment by RajendranDinesh** [comment]
Please refer to my previous response at #377 for the solution to this question. Let me know whether that works for you.

**Comment by manal-irfan** [comment]
You can your documents or any pdf file in the source document folder and it should work
