### ISSUE TITLE
AttributeError: 'Llama' object has no attribute 'ctx'

### ISSUE THREAD

**Issue by rekhasar10** [PromtEngineer/localGPT#383]
2023-08-17 11:02:17,285 - INFO - run_localGPT.py:50 - Using Llamacpp for GGML quantized models
2023-08-17 11:02:17,404 - INFO - run_localGPT.py:53 - /root/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGML/snapshots/b616819cd4777514e3a2d9b8be69824aca8f5daf/llama-2-7b-chat.ggmlv3.q4_0.bin
Exception ignored in: <function Llama.__del__ at 0x7f5a8dbf2de0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llama_cpp/llama.py", line 343, in __del__
    llama_cpp.llama_free(self.ctx)
                         ^^^^^^^^
AttributeError: 'Llama' object has no attribute 'ctx'
Traceback (most recent call last):
  File "/home/ec2-user/localgpt/localGPT/run_localGPT.py", line 254, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/localgpt/localGPT/run_localGPT.py", line 217, in main
    llm = load_model(device_type, model_id=MODEL_ID, model_basename=MODEL_BASENAME)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/localgpt/localGPT/run_localGPT.py", line 71, in load_model
    return LlamaCpp(**kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: /root/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGML/snapshots/b616819cd4777514e3a2d9b8be69824aca8f5daf/llama-2-7b-chat.ggmlv3.q4_0.bin. Received error Llama.__init__() got an unexpected keyword argument 'lora_path' (type=value_error)
2023-08-17 11:02:17,408 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: /home/ec2-user/localgpt/localGPT/DB

Please help to resolve this issue

**Comment by yxy123** [comment]
@rekhasar10   Have your issue resolved?  I meet same issue.
