### ISSUE TITLE
CUDA Out of Memory Error when asking more than 4 questions on Google Colab T4

### ISSUE THREAD

**Issue by mcgeochd** [PromtEngineer/localGPT#384]
I'm running localGPT on a Google Colab T4 instance as my PC GPU doesn't have enough memory, but when I query it more than 4 or so times it tries to allocate more memory and runs out. My question is: why is Pytorch trying to allocate more memory once the embedding model and llm have been loaded? 

The model I'm using is:
model_id = "TheBloke/orca_mini_v3_13B-GPTQ"
model_basename = "gptq_model-4bit-128g.safetensors"

which takes up 7.26 GB of the 15GB available on the T4.

The path trace of the error I'm getting is:
```
Traceback (most recent call last):
  File "/content/localGPT/run_localGPT.py", line 344, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/content/localGPT/run_localGPT.py", line 322, in main
    res = qa(query)
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/retrieval_qa/base.py", line 120, in _call
    answer = self.combine_documents_chain.run(
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 239, in run
    return self(kwargs, callbacks=callbacks)[self.output_keys[0]]
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/combine_documents/base.py", line 84, in _call
    output, extra_return_dict = self.combine_docs(
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/combine_documents/stuff.py", line 87, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/llm.py", line 213, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/llm.py", line 69, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/llm.py", line 79, in generate
    return self.llm.generate_prompt(
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 134, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks)
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 191, in generate
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 185, in generate
    self._generate(prompts, stop=stop, run_manager=run_manager)
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 436, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager)
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/huggingface_pipeline.py", line 168, in _call
    response = self.pipeline(prompt)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/text_generation.py", line 200, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1122, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1129, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1028, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/text_generation.py", line 261, in _forward
    generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/auto_gptq/modeling/_base.py", line 423, in generate
    return self.model.generate(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1538, in generate
    return self.greedy_search(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2362, in greedy_search
    outputs = self(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/auto_gptq/nn_modules/fused_llama_attn.py", line 109, in forward
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 1845, in softmax
    ret = input.softmax(dim, dtype=dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.77 GiB (GPU 0; 14.75 GiB total capacity; 9.49 GiB already allocated; 1.12 GiB free; 12.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
2023-08-17 10:58:56,535 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: /content/localGPT/DB
```

When first running `run_localGPT.py`, the output was:
```
2023-08-17 10:50:49,764 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-08-17 10:51:01,658 - INFO - run_localGPT.py:50 - Loading Model: TheBloke/orca_mini_v3_13B-GPTQ, on: cuda
2023-08-17 10:51:01,659 - INFO - run_localGPT.py:51 - This action can take a few minutes!
2023-08-17 10:51:01,659 - INFO - run_localGPT.py:73 - Using AutoGPTQForCausalLM for quantized models
2023-08-17 10:51:01,977 - INFO - run_localGPT.py:80 - Tokenizer loaded
2023-08-17 10:51:02,384 - INFO - _base.py:727 - lm_head not been quantized, will be ignored when make_quant.
2023-08-17 10:51:53,186 - WARNING - fused_llama_mlp.py:306 - skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
The model 'LlamaGPTQForCausalLM' is not supported for text-generation. Supported models are ['BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'CamembertForCausalLM', 'CodeGenForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'Data2VecTextForCausalLM', 'ElectraForCausalLM', 'ErnieForCausalLM', 'FalconForCausalLM', 'GitForCausalLM', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GPTJForCausalLM', 'LlamaForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegaForCausalLM', 'MegatronBertForCausalLM', 'MusicgenForCausalLM', 'MvpForCausalLM', 'OpenLlamaForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'QDQBertLMHeadModel', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'RwkvForCausalLM', 'Speech2Text2ForCausalLM', 'TransfoXLLMHeadModel', 'TrOCRForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMProphetNetForCausalLM', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'XmodForCausalLM'].
2023-08-17 10:51:53,744 - INFO - run_localGPT.py:132 - Local LLM Loaded
2023-08-17 10:51:53,746 - INFO - __init__.py:88 - Running Chroma using direct local API.
2023-08-17 10:51:53,784 - WARNING - __init__.py:43 - Using embedded DuckDB with persistence: data will be stored in: /content/localGPT/DB
2023-08-17 10:51:54,012 - INFO - ctypes.py:22 - Successfully imported ClickHouse Connect C data optimizations
2023-08-17 10:51:54,036 - INFO - json_impl.py:45 - Using python library for writing JSON byte strings
2023-08-17 10:51:55,226 - INFO - duckdb.py:460 - loaded in 9211 embeddings
2023-08-17 10:51:55,229 - INFO - duckdb.py:472 - loaded in 1 collections
2023-08-17 10:51:55,230 - INFO - duckdb.py:89 - collection with name langchain already exists, returning existing collection

Enter a query:
```

Any help would be greatly appreciated!

**Comment by StrikeNP** [comment]
You can try setting max memory and creating a weights offload folder so that it offloads extra needed space to disk

E.g. Line 94 on `run_localGPT.py`
```
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            device_map="auto",
            torch_dtype=torch.float16,
            low_cpu_mem_usage=True,
            trust_remote_code=True,
            max_memory={0: "10GB"},  # Uncomment this line with you encounter CUDA out of memory errors
            offload_folder="weights_offload"
        )
```

**Comment by mcgeochd** [comment]
Thanks, I'll try that!

**Comment by moustapha00** [comment]
Same issue here, any advice? Also I wonder why more memory is needed when the embedding model and llm are already loaded.
