### ISSUE TITLE
Cannot download GPTQ models (WSL, NVIDIA)

### ISSUE THREAD

**Issue by hedgar2017** [PromtEngineer/localGPT#399]
The latest commit in main suddenly stopped working with GPTQ models on my 2 Nvidia GTX 1080s:
```
(localGPT-Bandera) [hedgar@hedgaron-prime localGPT]$ python run_localGPT.py --device_type cuda
2023-08-22 21:11:24,601 - INFO - run_localGPT.py:179 - Running on: cuda
2023-08-22 21:11:24,602 - INFO - run_localGPT.py:180 - Display Source Documents set to: False
2023-08-22 21:11:24,832 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-08-22 21:11:27,200 - INFO - __init__.py:88 - Running Chroma using direct local API.
2023-08-22 21:11:27,203 - WARNING - __init__.py:43 - Using embedded DuckDB with persistence: data will be stored in: /home/hedgar/src/ai/localGPT/DB
2023-08-22 21:11:27,207 - INFO - ctypes.py:22 - Successfully imported ClickHouse Connect C data optimizations
2023-08-22 21:11:27,209 - INFO - json_impl.py:45 - Using python library for writing JSON byte strings
2023-08-22 21:11:27,240 - INFO - duckdb.py:460 - loaded in 72 embeddings
2023-08-22 21:11:27,242 - INFO - duckdb.py:472 - loaded in 1 collections
2023-08-22 21:11:27,242 - INFO - duckdb.py:89 - collection with name langchain already exists, returning existing collection
2023-08-22 21:11:27,243 - INFO - run_localGPT.py:45 - Loading Model: TheBloke/wizardLM-7B-GPTQ, on: cuda
2023-08-22 21:11:27,243 - INFO - run_localGPT.py:46 - This action can take a few minutes!
2023-08-22 21:11:27,243 - INFO - run_localGPT.py:68 - Using AutoGPTQForCausalLM for quantized models
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████████████████| 727/727 [00:00<00:00, 6.53MB/s]Downloading tokenizer.model: 100%|████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 7.80MB/s]Downloading (…)/main/tokenizer.json: 100%|██████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 17.3MB/s]Downloading (…)in/added_tokens.json: 100%|████████████████████████████████████████████████████████| 21.0/21.0 [00:00<00:00, 33.9kB/s]Downloading (…)cial_tokens_map.json: 100%|██████████████████████████████████████████████████████████| 435/435 [00:00<00:00, 4.78MB/s]2023-08-22 21:11:29,090 - INFO - run_localGPT.py:75 - Tokenizer loaded
Downloading (…)lve/main/config.json: 100%|██████████████████████████████████████████████████████████| 809/809 [00:00<00:00, 6.45MB/s]Downloading (…)quantize_config.json: 100%|███████████████████████████████████████████████████████████| 158/158 [00:00<00:00, 460kB/s]Traceback (most recent call last):
  File "/home/hedgar/src/ai/localGPT/run_localGPT.py", line 245, in <module>
    main()
  File "/home/hedgar/.conda/envs/localGPT-Bandera/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hedgar/.conda/envs/localGPT-Bandera/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/hedgar/.conda/envs/localGPT-Bandera/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hedgar/.conda/envs/localGPT-Bandera/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hedgar/src/ai/localGPT/run_localGPT.py", line 208, in main
    llm = load_model(device_type, model_id=MODEL_ID, model_basename=MODEL_BASENAME)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hedgar/src/ai/localGPT/run_localGPT.py", line 77, in load_model
    model = AutoGPTQForCausalLM.from_quantized(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hedgar/.conda/envs/localGPT-Bandera/lib/python3.11/site-packages/auto_gptq/modeling/auto.py", line 82, in from_quantized
    return quant_func(
           ^^^^^^^^^^^
  File "/home/hedgar/.conda/envs/localGPT-Bandera/lib/python3.11/site-packages/auto_gptq/modeling/_base.py", line 698, in from_quantized
    raise FileNotFoundError(f"Could not find model in {model_name_or_path}")
FileNotFoundError: Could not find model in TheBloke/wizardLM-7B-GPTQ
2023-08-22 21:11:30,096 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: /home/hedgar/src/ai/localGPT/DB
```

My `nvidia-smi` output:
```
(localGPT-Bandera) [hedgar@hedgaron-prime localGPT]$ nvidia-smi
Tue Aug 22 21:13:51 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.04              Driver Version: 536.23       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080        On  | 00000000:01:00.0  On |                  N/A |
| 50%   49C    P0              49W / 210W |   1153MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce GTX 1080        On  | 00000000:02:00.0  On |                  N/A |
| 50%   40C    P5              19W / 210W |    279MiB /  8192MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        21      G   /Xwayland                                 N/A      |
|    1   N/A  N/A        21      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+
```

My only changes are in constants.py:
```
MODEL_ID = "TheBloke/llama2_7b_chat_uncensored-GPTQ"
MODEL_BASENAME = "gptq_model-4bit-128g"
```

Tried on WSL Ubuntu and WSL Arch. Worked 2 days ago when I was able to run it successfully for the last time, then I cleaned the cache and now I cannot download the models again.

Could we somehow make the error message more informative?

**Comment by jnfarooq** [comment]
did you include the last part of the `MODEL_BASENAME` i.e. `.compat.no-act-order.safetensors`? I think that part is needed.

**Comment by hedgar2017** [comment]
> did you include the last part of the `MODEL_BASENAME` i.e. `.compat.no-act-order.safetensors`? I think that part is needed.

Thanks! Trying now.
Could you point me to the reference of those suffixes?
On the [model page](https://huggingface.co/TheBloke/CodeUp-Llama-2-13B-Chat-HF-GPTQ) they are different or absent.

**Comment by ShishirMaidenCodeLife** [comment]
"The Bloke/" has made a file name change in the last commit. Please update your MODEL_BASENAME to "model.safetensors" rather than the "gptq_model-4bit-128g" so that the model will be accessed from the repository.

**Comment by hedgar2017** [comment]
> "The Bloke/" has made a file name change in the last commit. Please update your MODEL_BASENAME to "model.safetensors" rather than the "gptq_model-4bit-128g" so that the model will be accessed from the repository.

`mode.safetensors` is a suffix or the full name? Could you point where do you see the change?

Hmm, huggingface.co is down at the moment apparently.

**Comment by hedgar2017** [comment]
> "The Bloke/" has made a file name change in the last commit. Please update your MODEL_BASENAME to "model.safetensors" rather than the "gptq_model-4bit-128g" so that the model will be accessed from the repository.

I've found where to look for the model name! Thanks a lot for your help!

**Comment by Pradeep987654321** [comment]
> > "The Bloke/" has made a file name change in the last commit. Please update your MODEL_BASENAME to "model.safetensors" rather than the "gptq_model-4bit-128g" so that the model will be accessed from the repository.
> 
> I've found where to look for the model name! Thanks a lot for your help!

Can you update full name of the new model_basename pls @hedgar2017

**Comment by syedfahimabrar** [comment]
> > > "The Bloke/" has made a file name change in the last commit. Please update your MODEL_BASENAME to "model.safetensors" rather than the "gptq_model-4bit-128g" so that the model will be accessed from the repository.
> > 
> > 
> > I've found where to look for the model name! Thanks a lot for your help!
> 
> Can you update full name of the new model_basename pls @hedgar2017

Hi,
AutoGPTQForCausalLM.from_quantized has revision parameter. Use just model.safetensors in modelbasename and pass the git branch name for the model you are trying to load. Suppose i want to load 'gptq-8bit--1g-actorder_True'. So in load_models.py file i modified the file in the following way:
`model = AutoGPTQForCausalLM.from_quantized(
        model_id,
        revision='gptq-8bit--1g-actorder_True',
        model_basename=model_basename,
        use_safetensors=True,
        trust_remote_code=True,
        device_map="auto",
        use_triton=False,
        quantize_config=None,
    )`
you can make it dynamic, if u want. I didn't bother.
