### ISSUE TITLE
when i run  ingest.py ,i always get error:'Connection reset by peer'

### ISSUE THREAD

**Issue by juzi0551** [PromtEngineer/localGPT#415]
2023-08-25 16:51:58,992 - INFO - ingest.py:121 - Loading documents from /Users/zhonglei/LLM/localGPT/SOURCE_DOCUMENTS
2023-08-25 16:52:01,990 - INFO - ingest.py:130 - Loaded 1 documents from /Users/zhonglei/LLM/localGPT/SOURCE_DOCUMENTS
2023-08-25 16:52:01,990 - INFO - ingest.py:131 - Split into 72 chunks of text
2023-08-25 16:52:23,504 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
Downloading (…)c7233/.gitattributes: 100%|████████████████████████████████████████| 1.48k/1.48k [00:00<00:00, 8.94MB/s]
Downloading (…)_Pooling/config.json: 100%|█████████████████████████████████████████████| 270/270 [00:00<00:00, 708kB/s]
Downloading (…)/2_Dense/config.json: 100%|█████████████████████████████████████████████| 116/116 [00:00<00:00, 507kB/s]
Traceback (most recent call last):
  File "/Users/zhonglei/miniconda3/envs/localgpt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/zhonglei/miniconda3/envs/localgpt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/zhonglei/miniconda3/envs/localgpt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/zhonglei/miniconda3/envs/localgpt/lib/python3.10/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/zhonglei/miniconda3/envs/localgpt/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/zhonglei/miniconda3/envs/localgpt/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/zhonglei/miniconda3/envs/localgpt/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/zhonglei/miniconda3/envs/localgpt/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/Users/zhonglei/miniconda3/envs/localgpt/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

**Comment by Arieck-M** [comment]
Hi, How did you solve this problem?

**Comment by ZhaonianZhang** [comment]
Hi, from my side, this is a connection issue. You can check your network connection or you can change it, for example, I connect my computer to my phone that use my phone network. It worked.
