### ISSUE TITLE
how to ingest files from subfolders in source_documents?

### ISSUE THREAD

**Issue by abcnow** [PromtEngineer/localGPT#431]
Hi Guys: I have a bunch of files organized in subfolders and I would like to keep them organized that way.. so my question is how can I tell the ingest file to ingest files from subfolders as well.. thanks in advance!

**Comment by PromtEngineer** [comment]
We just pushed an update, that should take care of it.

**Comment by abcnow** [comment]
You are the man!

**Comment by abcnow** [comment]
@PromtEngineer ok.. I started to ingest the file and this is what I am getting.. what should I do?
----
 /usr/local/bin/python3 -u "/Users/ac/Downloads/localGPT-main/ingest.py"
Traceback (most recent call last):
  File "/Users/ac/Downloads/localGPT-main/ingest.py", line 12, in <module>
    from constants import (
  File "/Users/ac/Downloads/localGPT-main/constants.py", line 21, in <module>
    CHROMA_SETTINGS = Settings(
                      ^^^^^^^^^
  File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
is_persistent
  extra fields not permitted (type=value_error.extra)
(base)
