### ISSUE TITLE
Could not load Llama model from path: xxxx/llama-2-7b-chat.ggmlv3.q4_0.bin

### ISSUE THREAD

**Issue by XksA-me** [PromtEngineer/localGPT#438]
My Environment
```bash
ubuntu 20.04
gcc 11
cuda 11.6
```

Problems: Could not load Llama model 
```bash
/localGPT# python run_localGPT.py 
2023-08-31 03:28:34,335 - INFO - run_localGPT.py:180 - Running on: cuda
2023-08-31 03:28:34,335 - INFO - run_localGPT.py:181 - Display Source Documents set to: False
2023-08-31 03:28:34,492 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-08-31 03:28:37,688 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-08-31 03:28:37,770 - INFO - run_localGPT.py:45 - Loading Model: TheBloke/Llama-2-7B-Chat-GGML, on: cuda
2023-08-31 03:28:37,770 - INFO - run_localGPT.py:46 - This action can take a few minutes!
2023-08-31 03:28:37,770 - INFO - run_localGPT.py:50 - Using Llamacpp for GGML quantized models
Downloading (…)chat.ggmlv3.q4_0.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.79G/3.79G [05:25<00:00, 11.6MB/s]
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2080 Ti, compute capability 7.5
gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from /root/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGML/snapshots/b616819cd4777514e3a2d9b8be69824aca8f5daf/llama-2-7b-chat.ggmlv3.q4_0.bin

llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/localGPT/run_localGPT.py", line 246, in <module>
    main()
  File "/root/miniconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/localGPT/run_localGPT.py", line 209, in main
    llm = load_model(device_type, model_id=MODEL_ID, model_basename=MODEL_BASENAME)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/localGPT/run_localGPT.py", line 63, in load_model
    return LlamaCpp(**kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/localGPT/lib/python3.11/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: /root/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGML/snapshots/b616819cd4777514e3a2d9b8be69824aca8f5daf/llama-2-7b-chat.ggmlv3.q4_0.bin. Received error  (type=value_error)
```

**Comment by XksA-me** [comment]
Even if I swtich to other models, it won't work. 
```bash
python run_localGPT.py 
2023-08-31 05:50:59,617 - INFO - run_localGPT.py:180 - Running on: cuda
2023-08-31 05:50:59,617 - INFO - run_localGPT.py:181 - Display Source Documents set to: False
2023-08-31 05:50:59,775 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-08-31 05:51:02,950 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-08-31 05:51:03,033 - INFO - run_localGPT.py:45 - Loading Model: TheBloke/Llama-2-7B-Chat-GGML, on: cuda
2023-08-31 05:51:03,033 - INFO - run_localGPT.py:46 - This action can take a few minutes!
2023-08-31 05:51:03,033 - INFO - run_localGPT.py:50 - Using Llamacpp for GGML quantized models
Downloading (…)chat.ggmlv3.q4_1.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.21G/4.21G [06:01<00:00, 11.6MB/s]
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2080 Ti, compute capability 7.5
gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from /root/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGML/snapshots/b616819cd4777514e3a2d9b8be69824aca8f5daf/llama-2-7b-chat.ggmlv3.q4_1.bin

llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/localGPT/run_localGPT.py", line 246, in <module>
    main()
  File "/root/miniconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/localGPT/run_localGPT.py", line 209, in main
    llm = load_model(device_type, model_id=MODEL_ID, model_basename=MODEL_BASENAME)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/localGPT/run_localGPT.py", line 63, in load_model
    return LlamaCpp(**kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/localGPT/lib/python3.11/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: /root/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGML/snapshots/b616819cd4777514e3a2d9b8be69824aca8f5daf/llama-2-7b-chat.ggmlv3.q4_1.bin. Received error  (type=value_error)
```

**Comment by XksA-me** [comment]
I use docker to create an image, but it doesn't work even when running in a container.
My model is placed in `/mnt/example/llama/llama-2-7b-chat.ggmlv3.q4_0.bin`
```bash
2023-08-31 05:43:53,445 - INFO - run_localGPT.py:181 - Running on: cuda
2023-08-31 05:43:53,445 - INFO - run_localGPT.py:182 - Display Source Documents set to: False
2023-08-31 05:43:53,634 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: /mnt/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-08-31 05:43:59,743 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-08-31 05:43:59,843 - INFO - run_localGPT.py:45 - Loading Model: TheBloke/Llama-2-7B-Chat-GGML, on: cuda
2023-08-31 05:43:59,843 - INFO - run_localGPT.py:46 - This action can take a few minutes!
2023-08-31 05:43:59,843 - INFO - run_localGPT.py:50 - Using Llamacpp for GGML quantized models
gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from /mnt/example/llama/llama-2-7b-chat.ggmlv3.q4_0.bin

llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "//run_localGPT.py", line 247, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "//run_localGPT.py", line 210, in main
    llm = load_model(device_type, model_id=MODEL_ID, model_basename=MODEL_BASENAME)
  File "//run_localGPT.py", line 64, in load_model
    return LlamaCpp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: /mnt/example/llama/llama-2-7b-chat.ggmlv3.q4_0.bin. Received error  (type=value_error)
```

**Comment by neckos** [comment]
I have the same problem with this model. Is it something to do with llama switching to GGUF?

**Comment by murcielargo** [comment]
I have same problem too

**Comment by stevew00ds** [comment]
Me too

**Comment by imjwang** [comment]
Yes, I believe this is because of gguf. If you have a current version, can you try an older version of llama-cpp-python?

```bash
CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install -U llama-cpp-python==0.1.78 --no-cache-dir
```

**Comment by xiexiaodev** [comment]
Simply switch to the new gguf model files will likely solve your problem.

**Comment by XksA-me** [comment]
> Yes, I believe this is because of gguf. If you have a current version, can you try an older version of llama-cpp-python?
> 
> ```shell
> CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install -U llama-cpp-python==0.1.78 --no-cache-dir
> ```


Thank you for your reply, but now there are some new issues:`ggml_new_object: not enough space in the context's memory pool (needed 18503312, available 10650320)` 

I‘m sure both graphices and memory are sufficient. Can it be a system version issues? 

Has anyone replicated it under Ubuntu 20.04, and what are the machine graphics card and memory configurations?

```bash
python run_localGPT.py 
2023-09-03 12:39:00,365 - INFO - run_localGPT.py:181 - Running on: cuda
2023-09-03 12:39:00,365 - INFO - run_localGPT.py:182 - Display Source Documents set to: False
2023-09-03 12:39:00,521 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-09-03 12:39:03,884 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-09-03 12:39:03,967 - INFO - run_localGPT.py:45 - Loading Model: TheBloke/Llama-2-7B-Chat-GGML, on: cuda
2023-09-03 12:39:03,967 - INFO - run_localGPT.py:46 - This action can take a few minutes!
2023-09-03 12:39:03,967 - INFO - run_localGPT.py:50 - Using Llamacpp for GGML quantized models
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2080 Ti, compute capability 7.5
llama.cpp: loading model from /123.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 5.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  =  468.40 MB (+ 1024.00 MB per state)
llama_model_load_internal: allocating batch_size x (512 kB + n_ctx x 128 B) = 384 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 35/35 layers to GPU
llama_model_load_internal: total VRAM used: 4954 MB
llama_new_context_with_model: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 

Enter a query: hello
ggml_new_object: not enough space in the context's memory pool (needed 18503312, available 10650320)
Segmentation fault (core dumped)
```

**Comment by imjwang** [comment]
Can you try changing `n_batch` to something like 512?
https://github.com/PromtEngineer/localGPT/blob/80a3ffcfe5a62c6131e64b43cb1996970d30c28d/run_localGPT.py#L62

**Comment by Tonic3** [comment]
Same issue no doubt the GGUF switch, as llama doesn't support GGML anymore.

**Comment by KristoWind** [comment]
I had the same issue, but when I looked into the path I saw the .bin file was corrupt (0 kb). So I manually downloaded the .bin file and replaced the corrupt file with the new file.

**Comment by schoemantian** [comment]
Yeah same issue, and can't even change to a different model:

Link to other issue happening on Windows and Linux https://github.com/PromtEngineer/localGPT/issues/452
