### ISSUE TITLE
breaking commit on Persistency

### ISSUE THREAD

**Issue by dportabella** [PromtEngineer/localGPT#446]
after commit efae120 "There was an issue with Persistency, fixed it"  in August 22,

```
$ python run_localGPT.py -s
Traceback (most recent call last):
  File "/home/david/localGPT/run_localGPT.py", line 24, in <module>
    from constants import EMBEDDING_MODEL_NAME, PERSIST_DIRECTORY, MODEL_ID, MODEL_BASENAME
  File "/home/david/localGPT/constants.py", line 21, in <module>
    CHROMA_SETTINGS = Settings(
                      ^^^^^^^^^
  File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
is_persistent
  extra fields not permitted (type=value_error.extra)
```

**Comment by dportabella** [comment]
sorry, it was my mistake, i didn't update the dependencies. 
it works fine.

**Comment by JohnOstrowick** [comment]
Thanks. I have this error as well. What dependency caused this?

**Comment by Komal-99** [comment]
> sorry, it was my mistake, i didn't update the dependencies. it works fine.

Facing same issue but in Ingest .py can you help which dependencies caused this error
