### ISSUE TITLE
Running on docker produces gguf_init_from_file: invalid magic number 67676a74

### ISSUE THREAD

**Issue by pawelgnatowski** [PromtEngineer/localGPT#447]
Hey! 

I tried to replicate your YT video demo and this is the result:
Which model Llama2 running on GPU+  is useable with your code then @PromtEngineer?
I spent some time trying out different ones but either way I have had a number of other issues.

AFAIK ggml is outdated now and no longer compatible with llama.cpp latest versions.
Closer look: [https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/discussions/14]

Solution or advice would be highly appreciated.

gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from /root/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGML/snapshots/b616819cd4777514e3a2d9b8be69824aca8f5daf/llama-2-7b-chat.ggmlv3.q4_0.bin

llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/root/localGPT/run_localGPT.py", line 246, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/localGPT/run_localGPT.py", line 209, in main
    llm = load_model(device_type, model_id=MODEL_ID, model_basename=MODEL_BASENAME)
  File "/root/localGPT/run_localGPT.py", line 63, in load_model
    return LlamaCpp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: /root/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGML/snapshots/b616819cd4777514e3a2d9b8be69824aca8f5daf/llama-2-7b-chat.ggmlv3.q4_0.bin. Received error  (type=value_error)

**Comment by bondjames12** [comment]
Same issue, unsure of the solution:

 docker run -it --mount src="$HOME/.cache",target=/root/.cache,type=bind --gpus=all localgpt

==========
== CUDA ==
==========

CUDA Version 11.7.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

2023-09-03 20:16:28,115 - INFO - run_localGPT.py:180 - Running on: cuda
2023-09-03 20:16:28,115 - INFO - run_localGPT.py:181 - Display Source Documents set to: False
2023-09-03 20:16:28,211 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-09-03 20:16:31,712 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-09-03 20:16:31,809 - INFO - run_localGPT.py:45 - Loading Model: TheBloke/Llama-2-7B-Chat-GGML, on: cuda
2023-09-03 20:16:31,809 - INFO - run_localGPT.py:46 - This action can take a few minutes!
2023-09-03 20:16:31,809 - INFO - run_localGPT.py:50 - Using Llamacpp for GGML quantized models
gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from /root/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGML/snapshots/b616819cd4777514e3a2d9b8be69824aca8f5daf/llama-2-7b-chat.ggmlv3.q4_0.bin

llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "//run_localGPT.py", line 246, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "//run_localGPT.py", line 209, in main
    llm = load_model(device_type, model_id=MODEL_ID, model_basename=MODEL_BASENAME)
  File "//run_localGPT.py", line 63, in load_model
    return LlamaCpp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: /root/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGML/snapshots/b616819cd4777514e3a2d9b8be69824aca8f5daf/llama-2-7b-chat.ggmlv3.q4_0.bin. Received error  (type=value_error)

**Comment by PromtEngineer** [comment]
Unfortunately, LlamaCPP dropped support for ggml models so if you use the latest version of llamacpp, you will not be able to run ggml models. I would recommend to instead use GGUF models. I am testing an update to support gguf models. 

If you want to go ahead a make the change, probably the only change that you need is to change this [line:](https://github.com/PromtEngineer/localGPT/blob/80a3ffcfe5a62c6131e64b43cb1996970d30c28d/run_localGPT.py#L49C1-L50C1)  from `.ggml `to` .gguf.` In the constants.py file, you will also need to provide gguf files. 

I will be make changes soon.

**Comment by pawelgnatowski** [comment]
just a quick update - I was able to load the model. Though seems to be using mostly CPU not GPU (?!) 
And chroma db were not used?
I need to look deeper into this. It is weird. 
i also need to merge the chroma db fix ( i had a fix in my other code)

**Comment by KonradHoeffner** [comment]
@pawelgnatowski: Did you use the code from #454 or the original one?
And can you paste your command line output?

**Comment by pawelgnatowski** [comment]
@KonradHoeffner thanks for taking a look btw!
root@abace9ccd68a:~/localGPT# python run_localGPT.py --show_sources     
2023-09-07 07:27:20,783 - INFO - run_localGPT.py:180 - Running on: cuda
2023-09-07 07:27:20,783 - INFO - run_localGPT.py:181 - Display Source Documents set to: True
2023-09-07 07:27:20,912 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-09-07 07:27:23,717 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-09-07 07:27:23,789 - INFO - run_localGPT.py:45 - Loading Model: TheBloke/Llama-2-7B-Chat-GGML, on: cuda
2023-09-07 07:27:23,789 - INFO - run_localGPT.py:46 - This action can take a few minutes!
2023-09-07 07:27:23,789 - INFO - run_localGPT.py:50 - Using Llamacpp for GGML quantized models
llama.cpp: loading model from /root/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGML/snapshots/00109c56c85ca9015795ca06c272cbc65c7f1dbf/llama-2-7b-chat.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 5.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: mem required  = 3615.73 MB (+ 1024.00 MB per state)
llama_new_context_with_model: kv self size  = 1024.00 MB
llama_new_context_with_model: compute buffer total size =  153.35 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 

Enter a query:

**Comment by KonradHoeffner** [comment]
The important part is `BLAS = 0` which is strange given that you set `-DLLAMA_CUBLAS=on"`.
