### ISSUE TITLE
Unsupported version of sqlite3

### ISSUE THREAD

**Issue by TD-Excell** [PromtEngineer/localGPT#458]
My sqlite3 is greater then the requested version. Yet, chroma is complaining:
`
(localGPT) @TD-Excell ➜ /workspaces/codespaces-blank/localGPT (main) $ python ingest.py --device_type cpu
Traceback (most recent call last):
  File "/workspaces/codespaces-blank/localGPT/ingest.py", line 12, in <module>
    from constants import (
  File "/workspaces/codespaces-blank/localGPT/constants.py", line 4, in <module>
    from chromadb.config import Settings
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/chromadb/__init__.py", line 69, in <module>
    raise RuntimeError(
RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.
Please visit https://docs.trychroma.com/troubleshooting#sqlite to learn how to upgrade.
(localGPT) @TD-Excell ➜ /workspaces/codespaces-blank/localGPT (main) $ sqlite3 --version
3.38.5 2022-05-06 15:25:27 78d9c993d404cdfaa7fdd2973fa1052e3da9f66215cff9c5540ebe55c407d9fe
(localGPT) @TD-Excell ➜ /workspaces/codespaces-blank/localGPT (main) $ 
`

**Comment by NimrahIrvinei** [comment]
facing this issue
RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.
Please visit https://docs.trychroma.com/troubleshooting#sqlite to learn how to upgrade.

**Comment by ADELBYTES** [comment]
same issue.
