### ISSUE TITLE
how to use GGUF models ?

### ISSUE THREAD

**Issue by N1h1lv5** [PromtEngineer/localGPT#460]
Hi all,

how can i use GGUF mdoels ? is it compatiable with localgpt ? thanks in advance

`OSError: Can't load tokenizer for 'TheBloke/Speechless-Llama2-13B-GGUF'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'TheBloke/Speechless-Llama2-13B-GGUF' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.`

**Comment by devcat-net** [comment]
Hi @N1h1lv5 ,
i have the same problem. During my search for a solution I found following information from TheBloke: https://huggingface.co/TheBloke/LLaMa-7B-GGML/discussions/2#64b55b1b1977b0f2460aacc6
He is saying that you have to use ctransformers to load GGML models. Unfortunatelly I could figure it out how to make switch in the code of this project :-/

**Comment by zzadiues** [comment]
same issue

**Comment by PromtEngineer** [comment]
This is coming soon. Currently testing it.

**Comment by N1h1lv5** [comment]
> This is coming soon. Currently testing it.

Thank you so much !

**Comment by Euplectello** [comment]
Hello all,

I just updated to the latest code for localGPT (September 13th) which now seems to include GGUF models, however, I also get the same error message as stated before:
File "D:\xxx\pythonProjects\localGPT\venv\Lib\site-packages\transformers\tokenization_utils_base.py", line 1838, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'TheBloke/Llama-2-7b-Chat-GGUF'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwi
se, make sure 'TheBloke/Llama-2-7b-Chat-GGUF' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.

What needs to be done to resolve this issue?

Thank you very much!

**Comment by Euplectello** [comment]
> Hello all,
> 
> I just updated to the latest code for localGPT (September 13th) which now seems to include GGUF models, however, I also get the same error message as stated before: File "D:\xxx\pythonProjects\localGPT\venv\Lib\site-packages\transformers\tokenization_utils_base.py", line 1838, in from_pretrained raise EnvironmentError( OSError: Can't load tokenizer for 'TheBloke/Llama-2-7b-Chat-GGUF'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwi se, make sure 'TheBloke/Llama-2-7b-Chat-GGUF' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.
> 
> What needs to be done to resolve this issue?
> 
> Thank you very much!

Sorry I think I didn't check thourougly. When I run run_localGPT_v2.py it works fine !!!

**Comment by N1h1lv5** [comment]
Hi all,

for some reason v_2 doesnt work for me yet :  

`2023-09-13 13:07:34,527 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-09-13 13:07:35,118 - INFO - run_localGPT_v2.py:50 - Loading Model: TheBloke/Llama-2-7b-Chat-GGUF, on: cpu
2023-09-13 13:07:35,118 - INFO - run_localGPT_v2.py:51 - This action can take a few minutes!
2023-09-13 13:07:35,118 - INFO - load_models.py:41 - Using Llamacpp for GGUF/GGML quantized models
llama.cpp: loading model from ./models\models--TheBloke--Llama-2-7b-Chat-GGUF\snapshots\d4e8fc00ab6a2192c9cc3bacdfe77ac7dedd32a6║█╩«=error loading model: unknown (magic, version) combination: 46554747, 00000002; is this really a GGML file?
llama_load_model_from_file: failed to load model
Traceback (most recent call last):`

and 
'  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
llm
  none is not an allowed value (type=type_error.none.not_allowed)'

I think it doesnt even download the model, any help ? thanks in advance

**Comment by N1h1lv5** [comment]
pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir fixes it
I think requirements.txt has to be updated with the llama-cpp-python version @PromtEngineer

**Comment by simi** [comment]
> pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir fixes it I think requirements.txt has to be updated with the llama-cpp-python version @PromtEngineer

I can confirm this fixes the problem. Thanks for sharing @N1h1lv5.

**Comment by KonradHoeffner** [comment]
@N1h1lv5: llama-cpp-python is not included in requirements.txt anymore, it needs to be installed and upgraded manually now.

**Comment by N1h1lv5** [comment]
Yes, @KonradHoeffner  following PromptEngineer's last video, I also added in the discussion how is this done in windows and conda environment : 

set the environment variable properly :
$Env:CMAKE_ARGS="-DLLAMA_CUBLAS=on"
$Env:FORCE_CMAKE="1"

check that it works
echo $Env:CMAKE_ARGS

uninstall previous version of llama-cpp-python
pip uninstall llama-cpp-python

install the proper version :
pip install llama-cpp-python==0.1.83 --no-cache-dir

**Comment by hackerbin** [comment]
> pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir fixes it I think requirements.txt has to be updated with the llama-cpp-python version @PromtEngineer

Thank you. This solution worked

**Comment by slarrain** [comment]
Shouldn't we install the latest version of llama-cpp-python now? They are currently in version 2.x
