### ISSUE TITLE
How to add Support for TheBloke/CodeLlama-13B-fp16

### ISSUE THREAD

**Issue by elitedeveloper** [PromtEngineer/localGPT#463]
I want to use the following Model for localGPT :
`https://huggingface.co/TheBloke/CodeLlama-13B-fp16`

I have modified the constant.py file with the following changes.

```
MODEL_ID = "TheBloke/CodeLlama-13B-fp16"
MODEL_BASENAME = "NONE"
```

But I am getting the error after running 
`python run_localGPT.py --device_type cpu`

`Traceback (most recent call last):
  File "/home/danish/Projects/localGPT/run_localGPT.py", line 246, in <module>
    main()
  File "/home/danish/anaconda3/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/danish/anaconda3/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/danish/anaconda3/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/danish/anaconda3/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/danish/Projects/localGPT/run_localGPT.py", line 209, in main
    llm = load_model(device_type, model_id=MODEL_ID, model_basename=MODEL_BASENAME)
  File "/home/danish/Projects/localGPT/run_localGPT.py", line 77, in load_model
    model = AutoGPTQForCausalLM.from_quantized(
  File "/home/danish/anaconda3/envs/localGPT/lib/python3.10/site-packages/auto_gptq/modeling/auto.py", line 82, in from_quantized
    return quant_func(
  File "/home/danish/anaconda3/envs/localGPT/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 650, in from_quantized
    quantize_config = BaseQuantizeConfig.from_pretrained(model_name_or_path, **kwargs)
  File "/home/danish/anaconda3/envs/localGPT/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 89, in from_pretrained
    with open(resolved_config_file, "r", encoding="utf-8") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by PromtEngineer** [comment]
This should be: `MODEL_BASENAME = None`
