### ISSUE TITLE
Can't run Web UI

### ISSUE THREAD

**Issue by ChrisBNECBT** [PromtEngineer/localGPT#483]
I encountered the following problem when I tried running the graphical interface.

C:\localGPT>>python run_localGPT_API.py
Traceback (most recent call last):
  File "C:\localGPT\run_localGPT_API.py", line 14, in <module>
    from run_localGPT import load_model
  File "C:\localGPT\run_localGPT.py", line 22, in <module>
    from load_models import (
  File "C:\localGPT\load_models.py", line 12, in <module>
    from constants import CONTEXT_WINDOW_SIZE, MAX_NEW_TOKENS, N_GPU_LAYERS, N_BATCH, MODELS_PATH
  File "C:\localGPT\constants.py", line 23, in <module>
    CHROMA_SETTINGS = Settings(
                      ^^^^^^^^^
  File "pydantic\env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
is_persistent
  extra fields not permitted (type=value_error.extra)

I'm not versed in programming and don't know if this is a real issue or there's some settings I'd not set in place.

**Comment by PromtEngineer** [comment]
@ChrisBNECBT are you using the latest code? Can you please confirm?

**Comment by ChrisBNECBT** [comment]
Hi, the issue came from a fresh install of the latest code after completely uninstalling the previous version and its dependencies.

After the 3rd attempt at reinstall, I changed the model to GPTQ and it worked. I don't know if this was caused by the model, incomplete uninstall of the previous version or possibly dependency clashes with other app libraries.

**Comment by WiktorLigeza** [comment]
I had the same issue. After restarting the environment, it started working xD
