### ISSUE TITLE
[Question] sqlite3.OperationalError: too many SQL variables

### ISSUE THREAD

**Issue by ww2283** [PromtEngineer/localGPT#489]
I have successfully installed and run a small txt file to make sure everything is alright. Then I want to ingest a relatively large .xlsx file with ~20000 lines but then got this error:
```
2023-09-18 21:56:26,686 - INFO - ingest.py:122 - Loading documents from /maintank/Wei/localGPT/SOURCE_DOCUMENTS
2023-09-18 21:56:26,695 - INFO - ingest.py:34 - Loading document batch
2023-09-18 21:57:15,451 - INFO - ingest.py:131 - Loaded 1 documents from /maintank/Wei/localGPT/SOURCE_DOCUMENTS
2023-09-18 21:57:15,451 - INFO - ingest.py:132 - Split into 84632 chunks of text
2023-09-18 21:57:16,064 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
2023-09-18 21:57:16,474 - INFO - instantiator.py:21 - Created a temporary directory at /tmp/tmp9kzwjgek
2023-09-18 21:57:16,474 - INFO - instantiator.py:76 - Writing /tmp/tmp9kzwjgek/_remote_module_non_scriptable.py
max_seq_length  512
Traceback (most recent call last):
  File "/home/wei/Software/localGPT/ingest.py", line 160, in <module>
    main()
  File "/home/wei/anaconda3/envs/geneGPT/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/wei/anaconda3/envs/geneGPT/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/wei/anaconda3/envs/geneGPT/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wei/anaconda3/envs/geneGPT/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/wei/Software/localGPT/ingest.py", line 146, in main
    db = Chroma.from_documents(
  File "/home/wei/anaconda3/envs/geneGPT/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 613, in from_documents
    return cls.from_texts(
  File "/home/wei/anaconda3/envs/geneGPT/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 577, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "/home/wei/anaconda3/envs/geneGPT/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 209, in add_texts
    self._collection.upsert(
  File "/home/wei/anaconda3/envs/geneGPT/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 298, in upsert
    self._client._upsert(
  File "/home/wei/anaconda3/envs/geneGPT/lib/python3.10/site-packages/chromadb/api/segment.py", line 290, in _upsert
    self._producer.submit_embeddings(coll["topic"], records_to_submit)
  File "/home/wei/anaconda3/envs/geneGPT/lib/python3.10/site-packages/chromadb/db/mixins/embeddings_queue.py", line 145, in submit_embeddings
    results = cur.execute(sql, params).fetchall()
sqlite3.OperationalError: too many SQL variables
```
May I know what to do in order to get around this `too many SQL variables` error?

**Comment by ww2283** [comment]
my two cents: seems starting chromadb 0.4.9 a max_batch_size can be passed to api to allow handling of large query, see here: https://github.com/chroma-core/chroma/blob/b930a862bad2cdaa25a8c888d04e97f33351d412/docs/CIP_5_Large_Batch_Handling_Improvements.md?plain=1#L11

**Comment by ww2283** [comment]
I think it should work. But I was impatient and modified the embeddings_queue.py:
```
@override
def submit_embeddings(
    self, topic_name: str, embeddings: Sequence[SubmitEmbeddingRecord]
) -> Sequence[SeqId]:
    if not self._running:
        raise RuntimeError("Component not running")

    if len(embeddings) == 0:
        return []

    # Define the batch size
    batch_size = 500
    total_seq_ids = []

    # Split the embeddings into batches and process each batch
    for i in range(0, len(embeddings), batch_size):
        batch_embeddings = embeddings[i:i+batch_size]
        t = Table("embeddings_queue")
        insert = (
            self.querybuilder()
            .into(t)
            .columns(t.operation, t.topic, t.id, t.vector, t.encoding, t.metadata)
        )
        id_to_idx: Dict[str, int] = {}
        for embedding in batch_embeddings:
            (
                embedding_bytes,
                encoding,
                metadata,
            ) = self._prepare_vector_encoding_metadata(embedding)
            insert = insert.insert(
                ParameterValue(_operation_codes[embedding["operation"]]),
                ParameterValue(topic_name),
                ParameterValue(embedding["id"]),
                ParameterValue(embedding_bytes),
                ParameterValue(encoding),
                ParameterValue(metadata),
            )
            id_to_idx[embedding["id"]] = len(id_to_idx)
        with self.tx() as cur:
            sql, params = get_sql(insert, self.parameter_format())
            sql = f"{sql} RETURNING seq_id, id"
            results = cur.execute(sql, params).fetchall()
            seq_ids = [cast(SeqId, None)] * len(results)
            embedding_records = []
            for seq_id, id in results:
                seq_ids[id_to_idx[id]] = seq_id
                submit_embedding_record = batch_embeddings[id_to_idx[id]]
                embedding_record = EmbeddingRecord(
                    id=id,
                    seq_id=seq_id,
                    embedding=submit_embedding_record["embedding"],
                    encoding=submit_embedding_record["encoding"],
                    metadata=submit_embedding_record["metadata"],
                    operation=submit_embedding_record["operation"],
                )
                embedding_records.append(embedding_record)
            self._notify_all(topic_name, embedding_records)
            total_seq_ids.extend(seq_ids)

    return total_seq_ids

```
After this modification, the ingest.py didn't throw sqlite3 error and I can chat now. However, the ingest took 2hr on RTX6000 Ada. I'm just not sure if sqlite is the best option.

**Comment by erswelljustin** [comment]
I have been playing with the:

```
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=750, chunk_overlap=200)
    python_splitter = RecursiveCharacterTextSplitter.from_language(
        language=Language.PYTHON, chunk_size=660, chunk_overlap=200
    )
```

Values, but this is not working either, @ww2283 where is the file you edited? I cannot see this in the project 🤷🏻‍♂️

**Comment by ww2283** [comment]
should be this one `/home/user/.local/lib/python3.10/site-packages/chromadb/db/mixins/embeddings_queue.py` in your env.

**Comment by erswelljustin** [comment]
@PromtEngineer Any advice on this, please?

**Comment by ar-sumitovant** [comment]
I ran into this same issue, seems this was addressed in ChromaDB==0.4.9
I updated to that version and ingesting my datasource now (will take about 5-6 hours on CPU) and will update if it resolves the issue.

Based on the 0.4.9 code I reviewed, the default value for max_batch_size is now pulled from the "PRAGMA compile_options" query against the sqlite3 database which in my case is "MAX_VARIABLE_NUMBER=250000"

**Comment by thebetauser** [comment]
The latest chroma DB has more checks for max_batch_size however there is no chunking of the data (yet) so for now you will have to wrap the submit_embeddings function in a loop like ww2283 did. There are a few [references](https://github.com/chroma-core/chroma/issues/1049) to this issue.

You can get max_batch_size from chroma using `max_batch_size = PersistentClient()._producer.max_batch_size`
then use that value to optimize your loop around `Chroma.from_documents`

**Comment by erswelljustin** [comment]
Thanks all again for your advice. I eventually landed on this solution:

1. I upgraded to the latest ChromaDB version, at the time of writing, v0.4.12
2. I split the document texts into batches and processed them in batch sizes of no more than 20,000

Code example (Updated `ingest.py`:

```
   def process_in_batches(texts, batch_size):
        for i in range(0, len(texts), batch_size):
            yield texts[i:i+batch_size]

    for batch_texts in process_in_batches(texts, 20000):  # Using 40,000 as an example batch size
        db = Chroma.from_documents(
            batch_texts,
            embeddings,
            persist_directory=PERSIST_DIRECTORY,
            client_settings=CHROMA_SETTINGS,
        )
```

The `ingest.py` now works and is doing so pulling 800+ PDFs from the `SOURCE_DOCUMENTS` folder without any issue
