### ISSUE TITLE
none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by ghrahul** [PromtEngineer/localGPT#490]
Hi, can you please help me with this?

I have created the Vector DB using `python ingest.py --device_type cpu`. And I am using `Apple M1 Pro`.

**Model Used:**
```
MODEL_ID = "TheBloke/Llama-2-7b-Chat-GGUF"
MODEL_BASENAME = "llama-2-7b-chat.Q4_K_M.gguf"
```

**Command:** 
```
python run_localGPT.py --device_type mps
```
**Error:**

```
Traceback (most recent call last):
  File "/Users/rahul.ghosh/Documents/localgpt/localGPT/run_localGPT.py", line 258, in <module>
    main()
  File "/Users/rahul.ghosh/Documents/localgpt/localGPT/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahul.ghosh/Documents/localgpt/localGPT/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/rahul.ghosh/Documents/localgpt/localGPT/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahul.ghosh/Documents/localgpt/localGPT/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahul.ghosh/Documents/localgpt/localGPT/run_localGPT.py", line 229, in main
    qa = retrieval_qa_pipline(device_type, use_history, promptTemplate_type="llama")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahul.ghosh/Documents/localgpt/localGPT/run_localGPT.py", line 144, in retrieval_qa_pipline
    qa = RetrievalQA.from_chain_type(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahul.ghosh/Documents/localgpt/localGPT/venv/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 100, in from_chain_type
    combine_documents_chain = load_qa_chain(
                              ^^^^^^^^^^^^^^
  File "/Users/rahul.ghosh/Documents/localgpt/localGPT/venv/lib/python3.11/site-packages/langchain/chains/question_answering/__init__.py", line 249, in load_qa_chain
    return loader_mapping[chain_type](
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahul.ghosh/Documents/localgpt/localGPT/venv/lib/python3.11/site-packages/langchain/chains/question_answering/__init__.py", line 73, in _load_stuff_chain
    llm_chain = LLMChain(
                ^^^^^^^^^
  File "/Users/rahul.ghosh/Documents/localgpt/localGPT/venv/lib/python3.11/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
llm
  none is not an allowed value (type=type_error.none.not_allowed)
 ````

**pip --list**
```
--------------------------- ------------
accelerate                  0.23.0
aiohttp                     3.8.5
aiosignal                   1.3.1
altair                      5.1.1
anyio                       4.0.0
async-timeout               4.0.3
attrs                       23.1.0
auto-gptq                   0.2.2
backoff                     2.2.1
beautifulsoup4              4.12.2
bitsandbytes                0.41.1
blinker                     1.6.2
cachetools                  5.3.1
certifi                     2023.7.22
cffi                        1.15.1
chardet                     5.2.0
charset-normalizer          3.2.0
chroma-hnswlib              0.7.2
chromadb                    0.4.6
click                       8.1.7
coloredlogs                 15.0.1
contourpy                   1.1.1
cryptography                41.0.3
cycler                      0.11.0
dataclasses-json            0.5.14
datasets                    2.14.5
dill                        0.3.7
docx2txt                    0.8
emoji                       2.8.0
et-xmlfile                  1.1.0
exceptiongroup              1.1.3
faiss-cpu                   1.7.4
Faker                       19.6.1
fastapi                     0.99.1
favicon                     0.7.0
filelock                    3.12.4
filetype                    1.2.0
Flask                       2.3.3
flatbuffers                 23.5.26
fonttools                   4.42.1
frozenlist                  1.4.0
fsspec                      2023.6.0
gitdb                       4.0.10
GitPython                   3.1.36
h11                         0.14.0
htbuilder                   0.6.2
httptools                   0.6.0
huggingface-hub             0.17.2
humanfriendly               10.0
idna                        3.4
importlib-metadata          6.8.0
importlib-resources         6.0.1
InstructorEmbedding         1.0.1
itsdangerous                2.1.2
Jinja2                      3.1.2
joblib                      1.3.2
jsonschema                  4.19.0
jsonschema-specifications   2023.7.1
kiwisolver                  1.4.5
langchain                   0.0.267
langsmith                   0.0.38
lxml                        4.9.3
Markdown                    3.4.4
markdown-it-py              3.0.0
markdownlit                 0.0.7
MarkupSafe                  2.1.3
marshmallow                 3.20.1
matplotlib                  3.8.0
mdurl                       0.1.2
monotonic                   1.6
more-itertools              10.1.0
mpmath                      1.3.0
multidict                   6.0.4
multiprocess                0.70.15
mypy-extensions             1.0.0
networkx                    3.1
nltk                        3.8.1
numexpr                     2.8.6
numpy                       1.26.0
onnxruntime                 1.15.1
openapi-schema-pydantic     1.2.4
openpyxl                    3.1.2
overrides                   7.4.0
packaging                   23.1
pandas                      2.1.0
pdfminer.six                20221105
Pillow                      9.5.0
pip                         21.2.3
posthog                     3.0.2
protobuf                    3.20.3
psutil                      5.9.5
pulsar-client               3.3.0
pyarrow                     13.0.0
pycparser                   2.21
pydantic                    1.10.12
pydeck                      0.8.0
Pygments                    2.16.1
pymdown-extensions          10.3
Pympler                     1.0.1
pyparsing                   3.1.1
PyPika                      0.48.9
python-dateutil             2.8.2
python-dotenv               1.0.0
python-magic                0.4.27
pytz                        2023.3.post1
pytz-deprecation-shim       0.1.0.post0
PyYAML                      6.0.1
referencing                 0.30.2
regex                       2023.8.8
requests                    2.31.0
rich                        13.5.3
rouge                       1.0.1
rpds-py                     0.10.3
safetensors                 0.3.3
scikit-learn                1.3.0
scipy                       1.11.2
sentence-transformers       2.2.2
sentencepiece               0.1.99
setuptools                  57.4.0
six                         1.16.0
smmap                       5.0.1
sniffio                     1.3.0
soupsieve                   2.5
SQLAlchemy                  2.0.21
st-annotated-text           4.0.1
starlette                   0.27.0
streamlit                   1.26.0
streamlit-camera-input-live 0.2.0
streamlit-card              0.0.61
streamlit-embedcode         0.1.2
streamlit-extras            0.3.2
streamlit-faker             0.0.2
streamlit-image-coordinates 0.1.6
streamlit-keyup             0.2.0
streamlit-toggle-switch     1.0.2
streamlit-vertical-slider   1.0.2
sympy                       1.12
tabulate                    0.9.0
tenacity                    8.2.3
threadpoolctl               3.2.0
tokenizers                  0.13.3
toml                        0.10.2
toolz                       0.12.0
torch                       2.0.1
torchvision                 0.15.2
tornado                     6.3.3
tqdm                        4.66.1
transformers                4.33.2
typing_extensions           4.8.0
typing-inspect              0.9.0
tzdata                      2023.3
tzlocal                     4.3.1
unstructured                0.10.15
urllib3                     1.26.6
uvicorn                     0.23.2
uvloop                      0.17.0
validators                  0.22.0
watchfiles                  0.20.0
websockets                  11.0.3
Werkzeug                    2.3.7
xxhash                      3.3.0
yarl                        1.9.2
zipp                        3.17.0
WARNING: You are using pip version 21.2.3; however, version 23.2.1 is available.
You should consider upgrading via the '/Users/rahul.ghosh/Documents/localgpt/localGPT/venv/bin/python3.10 -m pip install --upgrade pip' command.
 ```

**Comment by ghrahul** [comment]
The llama-cpp-python >=0.1.83 was not installed correctly. Doing the installation resolved the issue. The exception was not showing the proper import error. we can include the exception message as well for this function: load_quantized_model_gguf_ggml

**Comment by hyperp0ppy** [comment]
Hi,

Do you know how to reinstall the llama-cpp-python? I'm not sure how to do that.

**Comment by ghrahul** [comment]
Hi,

You can use this: `pip install llama-cpp-python==0.1.83`
