### ISSUE TITLE
exit on line 40

### ISSUE THREAD

**Issue by JohnOstrowick** [PromtEngineer/localGPT#494]
ingest.py and localGPT_UI.py both return the following with python3.10.

Traceback (most recent call last):
  File "/home/john/ai/development/localGPT/ingest.py", line 12, in <module>
    from constants import (
  File "/home/john/ai/development/localGPT/constants.py", line 22, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
is_persistent
  extra fields not permitted (type=value_error.extra)

**Comment by JohnOstrowick** [comment]
Removing line 22 of the constants.py file fixed it. I think.
