### ISSUE TITLE
should try the next file

### ISSUE THREAD

**Issue by JohnOstrowick** [PromtEngineer/localGPT#495]
Hi there. I gave it a directory of PDFs to process - 594 documents to be precise. It exited without telling me WHICH document is broken. I'd like to humbly propose that if a document is unparseable it should continue and simply move broken documents aside, e.g. into a "seems to be broken" folder. Or, if you like, use PDFtk to fix it.

ome/john/ai/development/localGPT/SOURCE_DOCUMENTS
2023-09-19 17:59:30,211 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,211 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,211 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,211 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,211 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,212 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,212 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,212 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,212 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,212 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,212 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,212 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,212 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,212 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,212 - INFO - ingest.py:34 - Loading document batch
2023-09-19 17:59:30,212 - INFO - ingest.py:34 - Loading document batch
2023-09-19 18:01:28,037 - WARNING - pdftypes.py:242 - Data-loss while decompressing corrupted data
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/john/ai/development/localGPT/ingest.py", line 40, in load_document_batch
    data_list = [future.result() for future in futures]
  File "/home/john/ai/development/localGPT/ingest.py", line 40, in <listcomp>
    data_list = [future.result() for future in futures]
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/john/ai/development/localGPT/ingest.py", line 30, in load_single_document
    return loader.load()[0]
  File "/home/john/.local/lib/python3.10/site-packages/langchain/document_loaders/pdf.py", line 211, in load
    return list(self.lazy_load())
  File "/home/john/.local/lib/python3.10/site-packages/langchain/document_loaders/pdf.py", line 218, in lazy_load
    yield from self.parser.parse(blob)
  File "/home/john/.local/lib/python3.10/site-packages/langchain/document_loaders/base.py", line 95, in parse
    return list(self.lazy_parse(blob))
  File "/home/john/.local/lib/python3.10/site-packages/langchain/document_loaders/parsers/pdf.py", line 38, in lazy_parse
    text = extract_text(pdf_file_obj)
  File "/home/john/.local/lib/python3.10/site-packages/pdfminer/high_level.py", line 168, in extract_text
    for page in PDFPage.get_pages(
  File "/home/john/.local/lib/python3.10/site-packages/pdfminer/pdfpage.py", line 151, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File "/home/john/.local/lib/python3.10/site-packages/pdfminer/pdfdocument.py", line 752, in __init__
    raise PDFSyntaxError("No /Root object! - Is this really a PDF?")
pdfminer.pdfparser.PDFSyntaxError: No /Root object! - Is this really a PDF?
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/john/ai/development/localGPT/ingest.py", line 159, in <module>
    main()
  File "/home/john/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/john/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/john/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/john/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/john/ai/development/localGPT/ingest.py", line 122, in main
    documents = load_documents(SOURCE_DIRECTORY)
  File "/home/john/ai/development/localGPT/ingest.py", line 71, in load_documents
    contents, _ = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
pdfminer.pdfparser.PDFSyntaxError: No /Root object! - Is this really a PDF?

**Comment by JohnOstrowick** [comment]
My workaround as follows:

#!/bin/sh

for i in `/bin/ls pdfs | grep -i pdf` ; do ( echo $i ; mv pdfs/$i SOURCE_DOCUMENTS/ ; python3.10 ingest.py ; mv SOURCE_DOCUMENTS/$i ./pdfs  ) ; done

**Comment by ww2283** [comment]
@JohnOstrowick Thank you for sharing your idea, as I'm facing a very large PDF collection as well. Does the final DB construction the same in your method vs. using `python ingest.py` to ingest all document at once?

**Comment by JohnOstrowick** [comment]
Unfortunately if you see my other bug report at [https://github.com/PromtEngineer/localGPT/issues/502](https://github.com/PromtEngineer/localGPT/issues/502) it doesn't seem to make the DB folder so I can't tell at this stage if it works :(

**Comment by ww2283** [comment]
I tried and it works to use shell script to serial ingest. Just in case this helps.

**Comment by JohnOstrowick** [comment]
Great. Let me re-run it.
