### ISSUE TITLE
TheBloke/wizard-vicuna-13B-GGML, ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by dportabella** [PromtEngineer/localGPT#511]
I select this model in constants.py as follows:
```
MODEL_ID = "TheBloke/wizard-vicuna-13B-GGML"
MODEL_BASENAME = "wizard-vicuna-13B.ggmlv3.q4_0.bin"
```

`run_localGPT.py` fails with `ValueError: too many values to unpack (expected 2)`.
How to solve this?

```
python run_localGPT.py
2023-09-22 04:42:43,716 - INFO - run_localGPT.py:221 - Running on: cuda
2023-09-22 04:42:43,716 - INFO - run_localGPT.py:222 - Display Source Documents set to: False
2023-09-22 04:42:43,716 - INFO - run_localGPT.py:223 - Use history set to: False
2023-09-22 04:42:43,889 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-09-22 04:42:45,418 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-09-22 04:42:45,450 - INFO - run_localGPT.py:56 - Loading Model: TheBloke/wizard-vicuna-13B-GGML, on: cuda
2023-09-22 04:42:45,450 - INFO - run_localGPT.py:57 - This action can take a few minutes!
2023-09-22 04:42:45,450 - INFO - load_models.py:38 - Using Llamacpp for GGUF/GGML quantized models
llama.cpp: loading model from ./models/models--TheBloke--wizard-vicuna-13B-GGML/snapshots/18c48a2979551dbc957dc95638384db5f9f63400/wizard-vicuna-13B.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 4096
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_head_kv  = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 5.0e-06
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.11 MB
llama_model_load_internal: mem required  = 6983.72 MB (+ 3200.00 MB per state)
llama_new_context_with_model: kv self size  = 3200.00 MB
llama_new_context_with_model: compute buffer total size =  351.35 MB
AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
Traceback (most recent call last):
  File "/home/david/localGPT/run_localGPT.py", line 258, in <module>
    main()
  File "/home/david/anaconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/anaconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/david/anaconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/anaconda3/envs/localGPT/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/localGPT/run_localGPT.py", line 229, in main
    qa = retrieval_qa_pipline(device_type, use_history, promptTemplate_type="llama")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/localGPT/run_localGPT.py", line 132, in retrieval_qa_pipline
    llm = load_model(device_type, model_id=MODEL_ID, model_basename=MODEL_BASENAME, LOGGING=logging)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/localGPT/run_localGPT.py", line 64, in load_model
    model, tokenizer = load_quantized_model_gguf_ggml(model_id, model_basename, device_type, LOGGING)
    ^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

**Comment by Keykubat60** [comment]
Same Issue, did you solve it?

**Comment by M-Kevin-exe** [comment]
I also encountered this problem when I wanted to use the ggml model. Later, I used the default model and llama-cpp-python=0.1.83 and it ran successfully. I think it might be related to the version of the model and llama-cpp-python library. Although the default model is gguf, it can still be executed using --device_type cpu. Hope it helps you. (from Google Translate)
