### ISSUE TITLE
ingest.py: sqlite3.OperationalError: too many SQL variables

### ISSUE THREAD

**Issue by fireballer** [PromtEngineer/localGPT#519]
I was running an ingest on RunPod...After about 3 hours I got this error: 

I am using: hkunlp/instructor-xl

Traceback (most recent call last):
  File "/workspace/localGPT/ingest.py", line 175, in <module>
    main()
  File "/workspace/miniconda3/envs/localGPT2/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/workspace/miniconda3/envs/localGPT2/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/workspace/miniconda3/envs/localGPT2/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspace/miniconda3/envs/localGPT2/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/workspace/localGPT/ingest.py", line 154, in main
    db = Chroma.from_documents(
  File "/workspace/miniconda3/envs/localGPT2/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 613, in from_documents
    return cls.from_texts(
  File "/workspace/miniconda3/envs/localGPT2/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 577, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "/workspace/miniconda3/envs/localGPT2/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 209, in add_texts
    self._collection.upsert(
  File "/workspace/miniconda3/envs/localGPT2/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 298, in upsert
    self._client._upsert(
  File "/workspace/miniconda3/envs/localGPT2/lib/python3.10/site-packages/chromadb/api/segment.py", line 290, in _upsert
    self._producer.submit_embeddings(coll["topic"], records_to_submit)
  File "/workspace/miniconda3/envs/localGPT2/lib/python3.10/site-packages/chromadb/db/mixins/embeddings_queue.py", line 145, in submit_embeddings
    results = cur.execute(sql, params).fetchall()
sqlite3.OperationalError: too many SQL variables

**Comment by rcantada** [comment]
Please see offered solutions at #489
