### ISSUE TITLE
Report error when using MapRerank

### ISSUE THREAD

**Issue by Zephyruswind** [PromtEngineer/localGPT#552]
Do you get simliar error when using map_rerank?

(localGPT) PS D:\projects_llm\lgpt> python.exe '.\run_localGPT.py'
2023-10-03 07:32:14,263 - INFO - run_localGPT.py:221 - Running on: cuda
2023-10-03 07:32:14,263 - INFO - run_localGPT.py:222 - Display Source Documents set to: False
2023-10-03 07:32:14,263 - INFO - run_localGPT.py:223 - Use history set to: False
2023-10-03 07:32:14,656 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-xl
load INSTRUCTOR_Transformer
max_seq_length  512
2023-10-03 07:32:20,933 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-10-03 07:32:21,031 - INFO - run_localGPT.py:56 - Loading Model: NousResearch/Llama-2-7b-chat-hf, on: cuda
2023-10-03 07:32:21,031 - INFO - run_localGPT.py:57 - This action can take a few minutes!
2023-10-03 07:32:21,031 - INFO - load_models.py:135 - Using AutoModelForCausalLM for full models
2023-10-03 07:32:22,185 - INFO - load_models.py:137 - Tokenizer loaded
Loading checkpoint shards: 100%|██████████████████████████| 2/2 [00:06<00:00,  3.39s/it]
C:\Users\Heaven\.conda\envs\localGPT\lib\site-packages\transformers\generation\configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
C:\Users\Heaven\.conda\envs\localGPT\lib\site-packages\transformers\generation\configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
2023-10-03 07:32:31,693 - INFO - run_localGPT.py:89 - Local LLM Loaded
Traceback (most recent call last):
  File "D:\projects_llm\lgpt\run_localGPT.py", line 258, in <module>
    main()
  File "C:\Users\Heaven\.conda\envs\localGPT\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Heaven\.conda\envs\localGPT\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Heaven\.conda\envs\localGPT\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Heaven\.conda\envs\localGPT\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\projects_llm\lgpt\run_localGPT.py", line 229, in main
    qa = retrieval_qa_pipline(device_type, use_history, promptTemplate_type="llama")
  File "D:\projects_llm\lgpt\run_localGPT.py", line 144, in retrieval_qa_pipline
    qa = RetrievalQA.from_chain_type(
  File "C:\Users\Heaven\.conda\envs\localGPT\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 100, in from_chain_type
    combine_documents_chain = load_qa_chain(
  File "C:\Users\Heaven\.conda\envs\localGPT\lib\site-packages\langchain\chains\question_answering\__init__.py", line 249, in load_qa_chain
    return loader_mapping[chain_type](
  File "C:\Users\Heaven\.conda\envs\localGPT\lib\site-packages\langchain\chains\question_answering\__init__.py", line 52, in _load_map_rerank_chain
    return MapRerankDocumentsChain(
  File "C:\Users\Heaven\.conda\envs\localGPT\lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MapRerankDocumentsChain
__root__
  Output parser of llm_chain should be a RegexParser, got None (type=value_error)

**Comment by Zephyruswind** [comment]
Solved by adding RegexParser
