### ISSUE TITLE
dockerfile broken

### ISSUE THREAD

**Issue by CodeXTF2** [PromtEngineer/localGPT#554]
```123.6   Created wheel for lit: filename=lit-17.0.2-py3-none-any.whl size=93277 sha256=1fdd79aa132ef477a1d51bc219e1dab2d874bfac533f4a1c57d6da74d0cc7d8f
123.6   Stored in directory: /root/.cache/pip/wheels/3a/ff/73/ce1a12d89231e9ac175fb6493ee1fcc8768e85ee3bea4b98b2
123.6   Building wheel for antlr4-python3-runtime (setup.py): started
123.7   Building wheel for antlr4-python3-runtime (setup.py): finished with status 'done'
123.7   Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144575 sha256=8f38ecb622770c8103367739d1dbe7392f05d4ef4974c076665a5f4c008559a3
123.7   Stored in directory: /root/.cache/pip/wheels/12/93/dd/1f6a127edc45659556564c5730f6d4e300888f4bca2d4c5a88
123.7 Successfully built llama-cpp-python auto-gptq chroma-hnswlib sentence-transformers docx2txt pypika iopath lit antlr4-python3-runtime
123.7 ERROR: Exception:
123.7 Traceback (most recent call last):
123.7   File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
123.7     status = run_func(*args)
123.7   File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
123.7     return func(self, options, args)
123.7   File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run
123.7     to_install = resolver.get_installation_order(requirement_set)
123.7   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
123.7     weights = get_topological_weights(
123.7   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
123.7     assert len(weights) == expected_node_count
123.7 AssertionError
------
Dockerfile:11
--------------------
   9 |     COPY ./requirements.txt .
  10 |     # use BuildKit cache mount to drastically reduce redownloading from pip on repeated builds
  11 | >>> RUN --mount=type=cache,target=/root/.cache CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install --timeout 100 -r requirements.txt llama-cpp-python==0.1.83
  12 |     COPY SOURCE_DOCUMENTS ./SOURCE_DOCUMENTS
  13 |     COPY ingest.py constants.py ./
--------------------
ERROR: failed to solve: process "/bin/sh -c CMAKE_ARGS=\"-DLLAMA_CUBLAS=on\" FORCE_CMAKE=1 pip install --timeout 100 -r requirements.txt llama-cpp-python==0.1.83" did not complete successfully: exit code: 2```

**Comment by madjohn698** [comment]
I have the same error, my os is ubuntu22.04, docker version is  24.0.6, build ed223bc, looks like a version issue.
@CodeXTF2

**Comment by HasanMcAbdAllah** [comment]
I have the same issue.

**Comment by markjlorenz** [comment]
I was able to resolve by making two small changes:

In `Dockerfile`
```
COPY ./requirements.txt .
RUN apt remove -y python3-blinker # ADD THIS LINE
RUN pip install --upgrade pip
```

In `requirements.txt`
```
# bump the protobuf to 3.20.2
protobuf==3.20.2; sys_platform != 'darwin'
protobuf==3.20.2; sys_platform == 'darwin' and platform_machine != 'arm64'
```
