### ISSUE TITLE
Ingestion crashes upon encountering a corrupted / invalid Zip file

### ISSUE THREAD

**Issue by MadMartian** [PromtEngineer/localGPT#556]
```
Traceback (most recent call last):
  File "/opt/dev/oss/localGPT/ingest.py", line 159, in <module>
    main()
  File "<redacted>/.local/share/virtualenvs/localGPT-<redacted>/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "<redacted>/.local/share/virtualenvs/localGPT-<redacted>/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "<redacted>/.local/share/virtualenvs/localGPT-<redacted>/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.acllback, **ctx.params)
  File "<redacted>/.local/share/virtualenvs/localGPT-<redacted>/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/dev/oss/localGPT/ingest.py", line 122, in main
    documents = load_documents(SOURCE_DIRECTORY)
  File "/opt/dev/oss/localGPT/ingest.py", line 71, in load_documents
    contents, _ = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
zipfile.BadZipFile: File is not a zip file
```

I did further investigation and found another stack trace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/dev/oss/localGPT/ingest.py", line 40, in load_document_batch
    data_list = [future.result() for future in futures]
  File "/opt/dev/oss/localGPT/ingest.py", line 40, in <listcomp>
    data_list = [future.result() for future in futures]
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/dev/oss/localGPT/ingest.py", line 30, in load_single_document
    return loader.load()[0]
  File "<redacted>/.local/share/virtualenvs/localGPT-<redacted>/lib/python3.10/site-packages/langchain/document_loaders/word_document.py", line 55, in load
    page_content=docx2txt.process(self.file_path),
  File "<redacted>/.local/share/virtualenvs/localGPT-<redacted>/lib/python3.10/site-packages/docx2txt/docx2txt.py", line 76, in process
    zipf = zipfile.ZipFile(docx)
  File "/usr/lib/python3.10/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.10/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

It's not actually clear which file it's trying to open as a Zip file (assuming that's what it is trying to do).  `strace -f -e trace=file python ingest.py --device_type cuda` reveals the last file touched beneath the _SOURCE_DOCUMENTS_ folder was an `xls` file.

**Comment by CHAZAK23** [comment]
also having the same issue

**Comment by PGCJ** [comment]
me too

**Comment by MadMartian** [comment]
I pulled from master and I'm not running into this issue anymore, it's not clear whether the root cause was addressed.
