### ISSUE TITLE
Internal Server Error for 0.0.0.0 localGPTUI

### ISSUE THREAD

**Issue by googlier325** [PromtEngineer/localGPT#566]
### General Issue:

modified line 66 to 0.0.0.0 in localGPTUI.py for interfaces to listen on all network interfaces so other computers on the network can navigate to the http://10.x.x.x:5111

results are the same with line 66 has 127.0.0.1 and using --host flag

The localGPT page loads correctly but fails on asking a question. LocalGPT works fine with default localhost is used on the local machine.

Error is generated on the local machine and other machines on the network when navigating to http://10.x.x.x:5111

No firewalls are preventing communication. Text generation webUI works fine on the same machine when other computers access the webgui.

### Error

**Web Browser:**
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Terminal**:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.conda/envs/localGPT/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.conda/envs/localGPT/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.conda/envs/localGPT/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.conda/envs/localGPT/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/localGPT/localGPTUI/localGPTUI.py", line 27, in home_page
    response = requests.post(main_prompt_url, data={"user_prompt": user_prompt})
  File "/home/user/.conda/envs/localGPT/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/user/.conda/envs/localGPT/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/.conda/envs/localGPT/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.conda/envs/localGPT/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.conda/envs/localGPT/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5110): Max retries exceeded with url: /api/prompt_route (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cb88bfb20>: Failed to establish a new connection: [Errno 111] Connection refused'))
10.0.4.53 - - [08/Oct/2023 15:15:06] "POST / HTTP/1.1" 500 -

**Comment by googlier325** [comment]
Resolved - run the API backend service first by launching separate terminal and then execute python localGPTUI.py --host

Launch new terminal and execute: python localGPT.py --host 10.x.x.x
