### ISSUE TITLE
Error while running Mistral-7B-Instruct-v0.1-GPTQ

### ISSUE THREAD

**Issue by alphomeg** [PromtEngineer/localGPT#573]
`
2023-10-11 16:12:11.862166: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-10-11 16:12:14,897 - INFO - run_localGPT.py:229 - Running on: cuda
2023-10-11 16:12:14,897 - INFO - run_localGPT.py:230 - Display Source Documents set to: False
2023-10-11 16:12:14,898 - INFO - run_localGPT.py:231 - Use history set to: False
2023-10-11 16:12:15,074 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-10-11 16:12:18,655 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-10-11 16:12:18,731 - INFO - run_localGPT.py:56 - Loading Model: TheBloke/Mistral-7B-Instruct-v0.1-GPTQ, on: cuda
2023-10-11 16:12:18,731 - INFO - run_localGPT.py:57 - This action can take a few minutes!
2023-10-11 16:12:18,731 - INFO - load_models.py:86 - Using AutoGPTQForCausalLM for quantized models
Downloading (…)okenizer_config.json: 100% 1.46k/1.46k [00:00<00:00, 10.7MB/s]
Downloading tokenizer.model: 100% 493k/493k [00:01<00:00, 346kB/s]
Downloading (…)/main/tokenizer.json: 100% 1.80M/1.80M [00:00<00:00, 2.03MB/s]
Downloading (…)cial_tokens_map.json: 100% 72.0/72.0 [00:00<00:00, 523kB/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2023-10-11 16:12:23,764 - INFO - load_models.py:93 - Tokenizer loaded
Downloading (…)lve/main/config.json: 100% 963/963 [00:00<00:00, 5.77MB/s]
Traceback (most recent call last):
  File "/content/localGPT/run_localGPT.py", line 266, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/content/localGPT/run_localGPT.py", line 237, in main
    qa = retrieval_qa_pipline(device_type, use_history, promptTemplate_type=model_type)
  File "/content/localGPT/run_localGPT.py", line 132, in retrieval_qa_pipline
    llm = load_model(device_type, model_id=MODEL_ID, model_basename=MODEL_BASENAME, LOGGING=logging)
  File "/content/localGPT/run_localGPT.py", line 66, in load_model
    model, tokenizer = load_quantized_model_qptq(model_id, model_basename, device_type, LOGGING)
  File "/content/localGPT/load_models.py", line 95, in load_quantized_model_qptq
    model = AutoGPTQForCausalLM.from_quantized(
  File "/usr/local/lib/python3.10/dist-packages/auto_gptq/modeling/auto.py", line 79, in from_quantized
    model_type = check_and_get_model_type(save_dir or model_name_or_path, trust_remote_code)
  File "/usr/local/lib/python3.10/dist-packages/auto_gptq/modeling/_utils.py", line 125, in check_and_get_model_type
    raise TypeError(f"{config.model_type} isn't supported yet.")
TypeError: mistral isn't supported yet.
`

**Comment by alphomeg** [comment]
after some research i found out that AutoGPTQ doesn't handle mistral yet, is there any workaround to run mistral GPTQ?

**Comment by nachocheeseburger** [comment]
same issue here. any workaround?

**Comment by mariozupan** [comment]
the same issue. Which GPTQ model works fine?
