### ISSUE TITLE
error on run_localGPT.py:  none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by aasem-research-work** [PromtEngineer/localGPT#584]
Hi

I tried to execute the following:
`
(localGPT) E:\dev\python\localGPT>python run_localGPT.py
`
It begins correctly, downloaded required files but ends up with error:

(localGPT) E:\dev\python\localGPT>python run_localGPT.py 
2023-10-13 02:04:31,251 - INFO - run_localGPT.py:229 - Running on: cpu
2023-10-13 02:04:31,251 - INFO - run_localGPT.py:230 - Display Source Documents set to: False
2023-10-13 02:04:31,251 - INFO - run_localGPT.py:231 - Use history set to: False
2023-10-13 02:04:31,736 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-10-13 02:04:36,411 - INFO - posthog.py:16 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-10-13 02:04:36,558 - INFO - run_localGPT.py:56 - Loading Model: TheBloke/Llama-2-7b-Chat-GGUF, on: cpu
2023-10-13 02:04:36,558 - INFO - run_localGPT.py:57 - This action can take a few minutes!
2023-10-13 02:04:36,558 - INFO - load_models.py:38 - Using Llamacpp for GGUF/GGML quantized models
Traceback (most recent call last):
  File "E:\dev\python\localGPT\run_localGPT.py", line 266, in <module>
    main()
:
:

File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
llm
  none is not an allowed value (type=type_error.none.not_allowed)

Would anyone please advise on what is I am missing.

**Comment by Pranav-Kimbodo** [comment]
I faced the similar issue but having no solution : (

**Comment by tonys010968** [comment]
I'm also getting this error and I think it has to do with the PromptType.  I don't think it expects a string and the code is trying to send it a string.  I am still looking at it though.

**Comment by eslam-gomaa-careem** [comment]
same

**Comment by eslam-gomaa-careem** [comment]
try this
```bash
pip3.10 install llama-cpp-python
```
It worked with me

https://github.com/PromtEngineer/localGPT/issues/525#issuecomment-1745766968

**Comment by aasem-research-work** [comment]
I tried 
`
pip install llama-cpp-python
`

but mine is not fixed

**Comment by tonys010968** [comment]
> try this
> 
> ```shell
> pip3.10 install llama-cpp-python
> ```
> 
> It worked with me
> 
> [#525 (comment)](https://github.com/PromtEngineer/localGPT/issues/525#issuecomment-1745766968)

What version of llama-cpp-python are you running?  I am running 0.1.83 and I am still getting the error.

**Comment by tonys010968** [comment]
> > try this
> > ```
> > pip3.10 install llama-cpp-python
> > ```
> > 
> > 
> > It worked with me
> > [#525 (comment)](https://github.com/PromtEngineer/localGPT/issues/525#issuecomment-1745766968)
> 
> What version of llama-cpp-python are you running? I am running 0.1.83 and I am still getting the error.

And I just downgraded to version 0.1.48 because I saw when PromtEngineer put out a video on localGPT.  I figured I would downgrade to the version that was current around when that video came out.  Still not working though.

**Comment by aasem-research-work** [comment]
I have tried the followings but got no luck:

- pip install llama-cpp-python==0.1.83 --force-reinstall --upgrade --no-cache-dir
- pip install llama-cpp-python==0.2.11 --force-reinstall --upgrade --no-cache-dir

Upon debugging, it observe.. the load_model is returning None. It might be due to the incorrect path to the llama-2-7b-chat.Q4_K_M.gguf file or its directory.

```
    # load the llm pipeline
    llm = load_model(device_type, model_id=MODEL_ID, model_basename=MODEL_BASENAME, LOGGING=logging)
```

**Comment by orchardc** [comment]
Same problem here. Is there a solution for Windows users?

**Comment by tonys010968** [comment]
Not so far.  I think that aasem's post above is on track.  The models path does seem to be off, but I am not sure how to fix it or what the correct path should be.  

The path I see is as follows:

'./models\\models--TheBloke--Llama-2-7b-Chat-GGUF\\snapshots\\191239b3e26b2882fb562ffccdd1cf0f65402adb\\llama-2-7b-chat.Q4_K_M.gguf'

See how it uses a / and then the double blackslash (\\) in the path.  I feel like that is wrong, but I am not sure how to fix it.

**Comment by ShishirMaidenCodeLife** [comment]
Try this : 
pip install llama-cpp-python==0.1.83

**Comment by orchardc** [comment]
Thanks @ShishirMaidenCodeLife , it works for me with cpu

**Comment by ramaseshireddykolli** [comment]
@ShishirMaidenCodeLife thanks now None error is gone but i am not getting any response from the entered query. it goes in to unresponsive mode. I had to kill script using ctrl+z. 

Steps followed
(ivrGPT-env) root@Audio-Temp:/home/ubuntu/ram/gpt/localGPT# python ingest.py --device_type cpu
Requirement already satisfied: pysqlite3-binary in /home/ubuntu/ram/gpt/ivrGPT-env/lib/python3.10/site-packages (0.5.2.post1)

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
2023-10-17 05:40:29,142 - INFO - ingest.py:121 - Loading documents from /home/ubuntu/ram/gpt/localGPT/SOURCE_DOCUMENTS
2023-10-17 05:40:29,151 - INFO - ingest.py:34 - Loading document batch
2023-10-17 05:40:29,195 - INFO - ingest.py:130 - Loaded 1 documents from /home/ubuntu/ram/gpt/localGPT/SOURCE_DOCUMENTS
2023-10-17 05:40:29,195 - INFO - ingest.py:131 - Split into 4 chunks of text
2023-10-17 05:40:31,424 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
(ivrGPT-env) root@Audio-Temp:/home/ubuntu/ram/gpt/localGPT# python run_localGPT.py --device_type cpu
Requirement already satisfied: pysqlite3-binary in /home/ubuntu/ram/gpt/ivrGPT-env/lib/python3.10/site-packages (0.5.2.post1)

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
2023-10-17 05:41:36,794 - INFO - run_localGPT.py:231 - Running on: cpu
2023-10-17 05:41:36,794 - INFO - run_localGPT.py:232 - Display Source Documents set to: False
2023-10-17 05:41:36,794 - INFO - run_localGPT.py:233 - Use history set to: False
2023-10-17 05:41:37,182 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-10-17 05:41:49,462 - INFO - run_localGPT.py:57 - Loading Model: TheBloke/Llama-2-7b-Chat-GGUF, on: cpu
2023-10-17 05:41:49,462 - INFO - run_localGPT.py:58 - This action can take a few minutes!
2023-10-17 05:41:49,462 - INFO - load_models.py:38 - Using Llamacpp for GGUF/GGML quantized models
Downloading (…)-7b-chat.Q4_K_M.gguf: 100%|███████████████████████████████████████████████████████████████████████████████████| 4.08G/4.08G [00:27<00:00, 148MB/s]
llama_model_loader: loaded meta data with 19 key-value pairs and 291 tensors from ./models/models--TheBloke--Llama-2-7b-Chat-GGUF/snapshots/191239b3e26b2882fb562ffccdd1cf0f65402adb/llama-2-7b-chat.Q4_K_M.gguf (version GGUF V2 (latest))

..................................................................................................
llama_new_context_with_model: kv self size  = 2048.00 MB
llama_new_context_with_model: compute buffer total size =  281.47 MB
AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 

Enter a query: what are the terms and conditions of laptop?
[1]+  Stopped                 python run_localGPT.py --device_type cpu
(ivrGPT-env) root@Audio-Temp:/home/ubuntu/ram/gpt/localGPT# 

Can you some one please what i am doing wrong? i am using all default settings.

**Comment by tonys010968** [comment]
I did manage to get this working.  I can't remember all of the changes I made, but I exported my conda environment to YAML.  Here it is.  I hope this helps someone.

name: localGPT
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.08.22=haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=1.1.1w=h2bbff1b_0
  - pip=23.2.1=py310haa95532_0
  - python=3.10.9=h966fe2a_2
  - setuptools=68.0.0=py310haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py310haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - accelerate==0.23.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - altair==5.1.2
      - antlr4-python3-runtime==4.9.3
      - anyio==4.0.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - auto-gptq==0.2.2
      - backoff==2.2.1
      - beautifulsoup4==4.12.2
      - bitsandbytes-windows==0.37.5
      - blinker==1.6.3
      - cachetools==5.3.1
      - certifi==2023.7.22
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.0
      - chroma-hnswlib==0.7.2
      - chromadb==0.4.6
      - click==8.1.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.1.1
      - cryptography==41.0.4
      - cycler==0.12.1
      - dataclasses-json==0.5.14
      - datasets==2.14.5
      - dill==0.3.7
      - diskcache==5.6.3
      - docx2txt==0.8
      - effdet==0.4.1
      - emoji==2.8.0
      - et-xmlfile==1.1.0
      - exceptiongroup==1.1.3
      - faiss-cpu==1.7.4
      - fastapi==0.99.1
      - filelock==3.12.4
      - filetype==1.2.0
      - flask==3.0.0
      - flatbuffers==23.5.26
      - fonttools==4.43.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gitdb==4.0.10
      - gitpython==3.1.37
      - greenlet==3.0.0
      - h11==0.14.0
      - httptools==0.6.0
      - huggingface-hub==0.17.3
      - humanfriendly==10.0
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - instructorembedding==1.0.1
      - iopath==0.1.10
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - kiwisolver==1.4.5
      - langchain==0.0.267
      - langdetect==1.0.9
      - langsmith==0.0.43
      - layoutparser==0.3.4
      - llama-cpp-python==0.1.83
      - lxml==4.9.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - matplotlib==3.8.0
      - mdurl==0.1.2
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - networkx==3.1
      - nltk==3.8.1
      - numexpr==2.8.7
      - numpy==1.26.0
      - omegaconf==2.3.0
      - onnx==1.14.1
      - onnxruntime==1.15.1
      - openapi-schema-pydantic==1.2.4
      - opencv-python==4.8.1.78
      - openpyxl==3.1.2
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.1
      - pdf2image==1.16.3
      - pdfminer-six==20221105
      - pdfplumber==0.10.2
      - pillow==10.0.1
      - portalocker==2.8.2
      - posthog==3.0.2
      - protobuf==3.20.2
      - psutil==5.9.5
      - pulsar-client==3.3.0
      - pyarrow==13.0.0
      - pycocotools==2.0.7
      - pycparser==2.21
      - pydantic==1.10.13
      - pydeck==0.8.1b0
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pypdfium2==4.21.0
      - pypika==0.48.9
      - pyreadline3==3.4.1
      - pytesseract==0.3.10
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-iso639==2023.6.15
      - python-magic==0.4.27
      - python-multipart==0.0.6
      - pytz==2023.3.post1
      - pywin32==306
      - pyyaml==6.0.1
      - rapidfuzz==3.4.0
      - referencing==0.30.2
      - regex==2023.10.3
      - requests==2.31.0
      - rich==13.6.0
      - rouge==1.0.1
      - rpds-py==0.10.6
      - safetensors==0.4.0
      - scikit-learn==1.3.1
      - scipy==1.11.3
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.22
      - starlette==0.27.0
      - streamlit==1.27.2
      - streamlit-extras==0.0.9
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - threadpoolctl==3.2.0
      - timm==0.9.7
      - tokenizers==0.14.1
      - toml==0.10.2
      - toolz==0.12.0
      - torch==2.1.0
      - torchvision==0.16.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - transformers==4.34.0
      - typing-extensions==4.8.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - tzlocal==5.1
      - unstructured==0.10.21
      - unstructured-inference==0.7.2
      - unstructured-pytesseract==0.3.12
      - urllib3==1.26.6
      - uvicorn==0.23.2
      - validators==0.22.0
      - watchdog==3.0.0
      - watchfiles==0.20.0
      - websockets==11.0.3
      - werkzeug==3.0.0
      - xxhash==3.4.1
      - yarl==1.9.2
      - zipp==3.17.0
prefix: C:\Users\ajsavoca\AppData\Local\anaconda3\envs\localGPT

**Comment by levinit** [comment]
> Try this : pip install llama-cpp-python==0.1.83
> 
> Worked for me.... hope works for you too !!

It works, I run `pip install llama-cpp-python` , didn't specify a version number.
