### ISSUE TITLE
logging.INFO("If you were using GGML model, LLAMA-CPP Dropped Support, Use GGUF Instead")

### ISSUE THREAD

**Issue by Musthafamoz** [PromtEngineer/localGPT#594]
![image](https://github.com/PromtEngineer/localGPT/assets/107695170/24123ffa-2ec8-49fb-8c94-9f2016912c54)
any one faced the same error?While running LocalGPT using This model

MODEL_ID = "TheBloke/Llama-2-7B-Chat-GGML"
MODEL_BASENAME = "llama-2-7b-chat.ggmlv3.q4_0.bin"

**Comment by Musthafamoz** [comment]
THIS IS THE FULL ERROR

gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from ./models\models--TheBloke--Llama-2-7B-Chat-GGML\snapshots\76cd63c351ae389e1d4b91cab2cf470aab11864b\llama-2-7b-chat.ggmlv3.q4_0.bin

llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "C:\Users\intellectyx\Desktop\LocalGPT\localGPT\load_models.py", line 56, in load_quantized_model_gguf_ggml
    return LlamaCpp(**kwargs)
  File "C:\Users\intellectyx\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\load\serializable.py", line 74, in __init__        
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: ./models\models--TheBloke--Llama-2-7B-Chat-GGML\snapshots\76cd63c351ae389e1d4b91cab2cf470aab11864b\llama-2-7b-chat.ggmlv3.q4_0.bin. Received error  (type=value_error)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\intellectyx\Desktop\LocalGPT\localGPT\run_localGPT.py", line 268, in <module>
    main()
  File "C:\Users\intellectyx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\intellectyx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\intellectyx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\intellectyx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\intellectyx\Desktop\LocalGPT\localGPT\run_localGPT.py", line 239, in main
    qa = retrieval_qa_pipline(device_type, use_history, promptTemplate_type=model_type)
  File "C:\Users\intellectyx\Desktop\LocalGPT\localGPT\run_localGPT.py", line 134, in retrieval_qa_pipline
    llm = load_model(device_type, model_id=MODEL_ID, model_basename=MODEL_BASENAME, LOGGING=logging)
  File "C:\Users\intellectyx\Desktop\LocalGPT\localGPT\run_localGPT.py", line 65, in load_model
    model, tokenizer = load_quantized_model_gguf_ggml(model_id, model_basename, device_type, LOGGING)
  File "C:\Users\intellectyx\Desktop\LocalGPT\localGPT\load_models.py", line 59, in load_quantized_model_gguf_ggml
    logging.INFO("If you were using GGML model, LLAMA-CPP Dropped Support, Use GGUF Instead")
TypeError: 'int' object is not callable

**Comment by PromtEngineer** [comment]
As the logging info suggest, use a gguf format model instead of the ggml format. llamacpp has dropped support for the ggml models and that's why you are seeing this error.

**Comment by ant5788** [comment]
If you still want to continue using the GGML model, is there a solution?
