### ISSUE TITLE
Some files causing ingestion problems

### ISSUE THREAD

**Issue by gurrier** [PromtEngineer/localGPT#604]
I've encountered a few files of format PDF and DOCX that cause the ingestion process to fail. The recent changes have made it a little easier as it is now reported which file failed.

See an example below which seems to consider the docx to be a zip file for some reason.

-----

(localGPT2) C:\Users\username\localGPT>python ingest.py --device_type cuda
2023-10-23 00:04:01,660 - INFO - ingest.py:144 - Loading documents from C:\Users\username\localGPT/SOURCE_DOCUMENTS
Importing: SCP094 Clearing of Trash Racks .docx
C:\Users\username\localGPT/SOURCE_DOCUMENTS\SCP094 Clearing of Trash Racks .docx loaded.

C:\Users\username\localGPT/SOURCE_DOCUMENTS\SCP094 Clearing of Trash Racks .docx loading error:
File is not a zip file

2023-10-23 00:04:07,577 - INFO - ingest.py:153 - Loaded 1 documents from C:\Users\username\localGPT/SOURCE_DOCUMENTS
2023-10-23 00:04:07,577 - INFO - ingest.py:154 - Split into 0 chunks of text
2023-10-23 00:04:09,186 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-xl
load INSTRUCTOR_Transformer
max_seq_length  512
Traceback (most recent call last):
  File "C:\Users\username\localGPT\ingest.py", line 181, in <module>
    main()
  File "C:\Users\username\anaconda3\envs\localGPT2\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\username\anaconda3\envs\localGPT2\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\username\anaconda3\envs\localGPT2\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\username\anaconda3\envs\localGPT2\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\username\localGPT\ingest.py", line 168, in main
    db = Chroma.from_documents(
  File "C:\Users\username\anaconda3\envs\localGPT2\lib\site-packages\langchain\vectorstores\chroma.py", line 613, in from_documents
    return cls.from_texts(
  File "C:\Users\username\anaconda3\envs\localGPT2\lib\site-packages\langchain\vectorstores\chroma.py", line 577, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "C:\Users\username\anaconda3\envs\localGPT2\lib\site-packages\langchain\vectorstores\chroma.py", line 187, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
  File "C:\Users\username\anaconda3\envs\localGPT2\lib\site-packages\langchain\embeddings\huggingface.py", line 169, in embed_documents
    embeddings = self.client.encode(instruction_pairs, **self.encode_kwargs)
  File "C:\Users\username\anaconda3\envs\localGPT2\lib\site-packages\InstructorEmbedding\instructor.py", line 524, in encode
    if isinstance(sentences[0],list):
IndexError: list index out of range

**Comment by JayRathod56** [comment]
Hey, I had the same error!!! the solution to this was really simple just use sudo for ewerything: pip, ingest.py, run_localgpt.py
I encountered, this issue as I don't use linux much. Hope that Helps!!! :)

**Comment by JannikSchneider12** [comment]
@JayRathod56 How do you mean this exactly?

**Comment by aphixe** [comment]
> @JayRathod56 How do you mean this exactly?

i'm using windows, but he is saying using linux you type. sudo python ingest.py or sudo python run_localgpt.py
I dont know the solution for windows.
