### ISSUE TITLE
UnboundLocalError: local variable 'loader' referenced before assignment

### ISSUE THREAD

**Issue by Simpleeasily** [PromtEngineer/localGPT#61]
Loading documents from D:\localGPT-main/SOURCE_DOCUMENTS
Traceback (most recent call last):
  File "D:\localGPT-main\ingest.py", line 57, in <module>
    main()
  File "C:\Users\KaiHongTech\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\KaiHongTech\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\KaiHongTech\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\KaiHongTech\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\localGPT-main\ingest.py", line 41, in main
    documents = load_documents(SOURCE_DIRECTORY)
  File "D:\localGPT-main\ingest.py", line 27, in load_documents
    return [load_single_document(f"D:\localGPT-main\SOURCE_DOCUMENTS") for file_path in all_files if file_path[-4:] in ['.txt', '.pdf', '.csv'] ]
  File "D:\localGPT-main\ingest.py", line 27, in <listcomp>
    return [load_single_document(f"D:\localGPT-main\SOURCE_DOCUMENTS") for file_path in all_files if file_path[-4:] in ['.txt', '.pdf', '.csv'] ]
  File "D:\localGPT-main\ingest.py", line 21, in load_single_document
    return loader.load()[0]
UnboundLocalError: local variable 'loader' referenced before assignment

**Comment by PromtEngineer** [comment]
Can you confirm if the path of the file you are trying to read is correct? What file type are you trying to load?

**Comment by Simpleeasily** [comment]
The file I loaded is the default PDF file, and the file path is also correct, but I don't know where the problem is ,lol

**Comment by Simpleeasily** [comment]
> Can you confirm if the path of the file you are trying to read is correct? What file type are you trying to load?

Sorryyyyyyyyyyy,i changed the path incorrectly, now it runs with no problem

**Comment by PromtEngineer** [comment]
Perfect, I will close the issue then.
