### ISSUE TITLE
Error when run ingest.py. Wrappers.ValidationError: 1 validation error for Settings is_persistent

### ISSUE THREAD

**Issue by stonez56** [PromtEngineer/localGPT#624]
As soon as I run this in VS code, I got this error message. 
I have 3 .pdf files in the SOURCE_DOCUMENTS folder.

Can any one help?
```
/Users/Stonez56/.pyenv/versions/3.11.3/bin/python /Users/Stonez56/python/local_gpt/ingest.py
~/python/local_gpt$/Users/Stonez56/.pyenv/versions/3.11.3/bin/python /Users/Stonez56/python/local_gpt/ingest.py
Traceback (most recent call last):
  File "/Users/Stonez56/python/local_gpt/ingest.py", line 12, in <module>
    from constants import (
  File "/Users/Stonez56/python/local_gpt/constants.py", line 25, in <module>
    CHROMA_SETTINGS = Settings(
                      ^^^^^^^^^
  File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
is_persistent
  extra fields not permitted (type=value_error.extra)
```

**Comment by jafrank88** [comment]
I see this in constants.py,

# Define the Chroma settings
CHROMA_SETTINGS = Settings(
    anonymized_telemetry=False,
    is_persistent=True,
)

When I commented out line 27 ( #   is_persistent=True, ), it seems to work and I think chroma defaults to this being true, so it is no longer needed.

**Comment by stonez56** [comment]
Indeed! After I commented line 27 #is_presistent=True from constants.py, it worked!
Thank you @jafrank88
