### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by parthi0202** [PromtEngineer/localGPT#626]
Received below error when i ran "python ingest.py"

`Traceback (most recent call last):
  File "C:\Softwares\chatai\localGPT-main\ingest.py", line 181, in <module>
    main()
  File "C:\Users\pramba\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pramba\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\pramba\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pramba\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Softwares\chatai\localGPT-main\ingest.py", line 168, in main
    db = Chroma.from_documents(
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pramba\AppData\Local\anaconda3\Lib\site-packages\langchain\vectorstores\chroma.py", line 684, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "C:\Users\pramba\AppData\Local\anaconda3\Lib\site-packages\langchain\vectorstores\chroma.py", line 642, in from_texts
    chroma_collection.add_texts(
  File "C:\Users\pramba\AppData\Local\anaconda3\Lib\site-packages\langchain\vectorstores\chroma.py", line 188, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pramba\AppData\Local\anaconda3\Lib\site-packages\langchain\embeddings\huggingface.py", line 171, in embed_documents
    embeddings = self.client.encode(instruction_pairs, **self.encode_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pramba\AppData\Local\anaconda3\Lib\site-packages\InstructorEmbedding\instructor.py", line 524, in encode
    if isinstance(sentences[0],list):
                  ~~~~~~~~~^^^
IndexError: list index out of range`

**Comment by ajarang** [comment]
still encountering this error even after git pull

**Comment by Tiagochicoo** [comment]
@parthi0202 I'm having the same issue as above, is there a fix for it? Thanks

`(localGPT) ➜  localGPT git:(main) python ingest.py --device_type mps
2023-12-08 13:50:08,050 - INFO - ingest.py:144 - Loading documents from /Users/tiago/rep/localGPT/SOURCE_DOCUMENTS
Importing: Orca_paper.pdf
/Users/tiago/rep/localGPT/SOURCE_DOCUMENTS/Orca_paper.pdf loaded.

/Users/tiago/rep/localGPT/SOURCE_DOCUMENTS/Orca_paper.pdf loading error:
partition_pdf is not available. Install the pdf dependencies with pip install "unstructured[pdf]"

2023-12-08 13:50:10,700 - INFO - ingest.py:153 - Loaded 1 documents from /Users/tiago/rep/localGPT/SOURCE_DOCUMENTS
2023-12-08 13:50:10,700 - INFO - ingest.py:154 - Split into 0 chunks of text
2023-12-08 13:50:11,354 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
Traceback (most recent call last):
  File "/Users/tiago/rep/localGPT/ingest.py", line 181, in <module>
    main()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tiago/rep/localGPT/ingest.py", line 168, in main
    db = Chroma.from_documents(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/localGPT/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 771, in from_documents
    return cls.from_texts(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/localGPT/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 729, in from_texts
    chroma_collection.add_texts(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/localGPT/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 275, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/localGPT/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 170, in embed_documents
    embeddings = self.client.encode(instruction_pairs, **self.encode_kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/localGPT/lib/python3.10/site-packages/InstructorEmbedding/instructor.py", line 524, in encode
    if isinstance(sentences[0],list):
IndexError: list index out of range`

**Comment by missmissfreya** [comment]
Hi @parthi0202 I'm having the same issue as you, how did you fix this? Why did you close it?

**Comment by ajarang** [comment]
I ended up remaking the anaconda environment, reinstalled llama-cpp-python to force cuda and making sure that my cuda SDK was installed properly and the visual studio extensions were in the right place. Not sure if that fixed the issue, but I haven't had an issue since.

**Comment by PayteR** [comment]
I am Windows user. I deleted CUDA 12.3 and installed CUDA again but version 12.1, because on site https://pytorch.org/ is 12.1 in `Compute platform` row. Then I installed `pytorch` again by command written there.
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
```
And now I don't have any issue.
