### ISSUE TITLE
Error - TheBloke/Llama-2-7b-Chat-GGUF on CPU, Using Llamacpp for GGUF/GGML quantized models

### ISSUE THREAD

**Issue by ryhkml** [PromtEngineer/localGPT#652]
I get an error when running `python run_localGPT.py`
```sh
2023-11-19 08:28:21,403 - INFO - run_localGPT.py:238 - Running on: cpu
2023-11-19 08:28:21,403 - INFO - run_localGPT.py:239 - Display Source Documents set to: False
2023-11-19 08:28:21,403 - INFO - run_localGPT.py:240 - Use history set to: False
2023-11-19 08:28:21,624 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-11-19 08:28:24,537 - INFO - run_localGPT.py:58 - Loading Model: TheBloke/Llama-2-7b-Chat-GGUF, on: cpu
2023-11-19 08:28:24,538 - INFO - run_localGPT.py:59 - This action can take a few minutes!
2023-11-19 08:28:24,538 - INFO - load_models.py:38 - Using Llamacpp for GGUF/GGML quantized models
Downloading (…)-7b-chat.Q4_K_M.gguf:   6%|██▋                                             | 231M/4.08G [00:58<16:18, 3.93MB/s]
Traceback (most recent call last):
  File "/home/user/codes/self/localGPT/run_localGPT.py", line 279, in <module>
    main()
  File "/home/user/anaconda3/lib/python3.11/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.11/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.11/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.11/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/codes/self/localGPT/run_localGPT.py", line 246, in main
    qa = retrieval_qa_pipline(device_type, use_history, promptTemplate_type=model_type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/codes/self/localGPT/run_localGPT.py", line 147, in retrieval_qa_pipline
    qa = RetrievalQA.from_chain_type(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 100, in from_chain_type
    combine_documents_chain = load_qa_chain(
                              ^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.11/site-packages/langchain/chains/question_answering/__init__.py", line 249, in load_qa_chain
    return loader_mapping[chain_type](
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.11/site-packages/langchain/chains/question_answering/__init__.py", line 73, in _load_stuff_chain
    llm_chain = LLMChain(
                ^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.11/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
llm
  none is not an allowed value (type=type_error.none.not_allowed)
```
Constants
```py
EMBEDDING_MODEL_NAME = "hkunlp/instructor-large"
MODEL_ID = "TheBloke/Llama-2-7b-Chat-GGUF"
MODEL_BASENAME = "llama-2-7b-chat.Q4_K_M.gguf"
```
OS
```txt
OS: Ubuntu 22.04.3 LTS x86_64
Kernel: 6.2.0-36-generic
CPU: 11th Gen Intel i5-11300H (8)
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]
```

**Comment by jeroenrnl** [comment]
I had this same problem and fixed it with
```
pip install llama-cpp-python
```
so I suppose that is missing from `requirements.txt`.

It's also probably a good idea to add some output to
```
    except:
        if "ggml" in model_basename:
            logging.INFO("If you were using GGML model, LLAMA-CPP Dropped Support, Use GGUF Instead")
        return None
```
in `load_models.py`, as the exception thrown quite clearly says what the problem is, but this is not displayed.

**Comment by Yak0vkaSup** [comment]
try it https://github.com/PromtEngineer/localGPT/issues/535#issuecomment-1737197639
