### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain llm

### ISSUE THREAD

**Issue by vermashubhangi** [PromtEngineer/localGPT#656]
Traceback (most recent call last):
  File "/home/shubhangiverma/localGPT/run_localGPT.py", line 279, in <module>
    main()
  File "/home/shubhangiverma/miniconda3/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/shubhangiverma/miniconda3/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/shubhangiverma/miniconda3/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shubhangiverma/miniconda3/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/shubhangiverma/localGPT/run_localGPT.py", line 246, in main
    qa = retrieval_qa_pipline(device_type, use_history, promptTemplate_type=model_type)
  File "/home/shubhangiverma/localGPT/run_localGPT.py", line 147, in retrieval_qa_pipline
    qa = RetrievalQA.from_chain_type(
  File "/home/shubhangiverma/miniconda3/envs/localGPT/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 100, in from_chain_type
    combine_documents_chain = load_qa_chain(
  File "/home/shubhangiverma/miniconda3/envs/localGPT/lib/python3.10/site-packages/langchain/chains/question_answering/__init__.py", line 249, in load_qa_chain
    return loader_mapping[chain_type](
  File "/home/shubhangiverma/miniconda3/envs/localGPT/lib/python3.10/site-packages/langchain/chains/question_answering/__init__.py", line 73, in _load_stuff_chain
    llm_chain = LLMChain(
  File "/home/shubhangiverma/miniconda3/envs/localGPT/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
llm
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by Yak0vkaSup** [comment]
It might help you https://github.com/PromtEngineer/localGPT/issues/535#issuecomment-1737197639
