### ISSUE TITLE
Error everytime I interact with the UI

### ISSUE THREAD

**Issue by Zetto12** [PromtEngineer/localGPT#657]
I can open the UI with no problem but every time I submit a prompt or upload a document to ingest I'm greeted with a 500 Internal Server Error message. 

This is the message I get in miniconda. 

User Prompt: Can you tell me about yourself?
[2023-11-22 15:47:05,528] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\zipfe\miniconda3\envs\localGPT\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\zipfe\miniconda3\envs\localGPT\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\zipfe\miniconda3\envs\localGPT\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

Anyone experienced the same and knows where I went wrong?

Thank you,
Martin

**Comment by PromtEngineer** [comment]
Are you running the API on a remote machine? Seems like there are connection issues. Make sure you are allowing incoming traffic on the port you are using.

**Comment by Zetto12** [comment]
Thank you for the quick reply. I'm not using the API. I used the UI accessed via http://localhost:5111/

**Comment by JamieVC** [comment]
same issue happen on my laptop locally.
http://127.0.0.1:5111/

![image](https://github.com/PromtEngineer/localGPT/assets/59042153/3b62f09c-2e22-485b-89ba-2408ffb08b9b)
