### ISSUE TITLE
/lib64/libgcc_s.so.1: version `GCC_7.0.0' not found  libarrow.so.1400

### ISSUE THREAD

**Issue by jjc120074203** [PromtEngineer/localGPT#691]
(localgptEnv) [root@localhost localGPT]# pip list |grep pyarrow                                                                                                            
pyarrow                   14.0.2                                                                                                                                           
pyarrow-hotfix            0.6                                                                                                                                              
(localgptEnv) [root@localhost localGPT]# pip list |grep pandas                                                                                                             
pandas                    2.0.0                        

when I  execute this command " python -c "import pyarrow; print(pyarrow.__version__)"   

always show this error!

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/apps/localGPT/localgptEnv/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: /lib64/libgcc_s.so.1: version `GCC_7.0.0' not found (required by /home/apps/localGPT/localgptEnv/lib/python3.10/site-packages/pyarrow/libarrow.so.1400)

**Comment by iris-qq** [comment]
did you solved this problem?

**Comment by yHoweM** [comment]
did you solved this problem? @jjc120074203
