### ISSUE TITLE
"TypeError: 'HuggingFaceInstructEmbeddings' object is not callable" after enter a query

### ISSUE THREAD

**Issue by Serializ3r** [PromtEngineer/localGPT#731]
After install everything and ingest a document i tried to call the `run_localGPT.py`, but when i enter a query, i get the error described in the tittle.

here's the log:

> (localGPT) C:\Private-localGPT>python run_localGPT.py
> 2024-02-03 17:27:30,678 - INFO - run_localGPT.py:265 - Running on: cpu
> 2024-02-03 17:27:30,678 - INFO - run_localGPT.py:266 - Display Source Documents set to: False
> 2024-02-03 17:27:30,679 - INFO - run_localGPT.py:267 - Use history set to: False
> 2024-02-03 17:27:31,074 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
> load INSTRUCTOR_Transformer
> max_seq_length  512
> 
> Enter a query: hi
> Traceback (most recent call last):
>   File "C:\Private-localGPT\run_localGPT.py", line 306, in <module>
>     main()
>   File "C:\Users\patri\anaconda3\envs\localGPT\lib\site-packages\click\core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Users\patri\anaconda3\envs\localGPT\lib\site-packages\click\core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "C:\Users\patri\anaconda3\envs\localGPT\lib\site-packages\click\core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Users\patri\anaconda3\envs\localGPT\lib\site-packages\click\core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "C:\Private-localGPT\run_localGPT.py", line 280, in main
>     res = qa(query)
> TypeError: 'HuggingFaceInstructEmbeddings' object is not callable

Any thoughts on this?

**Comment by g1ra** [comment]
I have the same !

**Comment by xXPhenomXx** [comment]
I also have the same, fresh EC2 install. Ubuntu 20

**Comment by tedcochran** [comment]
Not the most elegant solution perhaps, but I had to explicitly set embeddings in both the ingest.py and run_localGPT.py to get around this issue.  
<img width="1044" alt="workaround" src="https://github.com/PromtEngineer/localGPT/assets/36202682/1a44bdc8-f7c5-4fb4-ac9f-ac1504e5d514">

**Comment by tedcochran** [comment]
This is probably a bit better:
<img width="1044" alt="better-workaround" src="https://github.com/PromtEngineer/localGPT/assets/36202682/721a71cd-f35f-4d43-9092-456916fbebd0">

**Comment by kime541200** [comment]
I have same issue.
I try to add some import as below:
```Python
from langchain.embeddings import HuggingFaceBgeEmbeddings
from langchain.embeddings import HuggingFaceEmbeddings
```
but the issue still happen.

**Comment by PromtEngineer** [comment]
Should be fixed now. I think there was a bug in one of the recent PR. Somehow missed it.

**Comment by NitkarshChourasia** [comment]
So, what was the bug?

**Comment by NitkarshChourasia** [comment]
So, what was the bug?

@PromtEngineer which was introduced into the recent PR?
