### ISSUE TITLE
ingest.py is not running / mbp16 m1

### ISSUE THREAD

**Issue by pascalandy** [PromtEngineer/localGPT#81]
### Error:

```bash
~/Documents/github_pascalandy/localGPT|main⚡ ⇒  python3 ingest.py
Traceback (most recent call last):
  File "/Users/andy16/Documents/github_pascalandy/localGPT/ingest.py", line 4, in <module>
    from utils import xlxs_to_csv
  File "/Users/andy16/Documents/github_pascalandy/localGPT/utils.py", line 1, in <module>
    import openpyxl
ModuleNotFoundError: No module named 'openpyxl'
~/Documents/github_pascalandy/localGPT|main⚡ ⇒
```

For the records, I was able to run privategpt smoothly.

### m1 GPU

something is not the same as the README on step 4

- I have `/Volumes/Data/Users/USERNAME/miniconda3
- not `/Volumes/Data/Users/USERNAME/anaconda3`
- `envs` is empty

```bash
~/miniconda3|⇒  tree -L 1
.
├── LICENSE.txt
├── bin
├── conda-meta
├── condabin
├── envs
├── etc
├── include
├── lib
├── man
├── pkgs
├── python.app
├── share
├── shell
└── ssl
```

### versions

python --version
Python 3.10.10

**Comment by PromtEngineer** [comment]
Updating to the latest version will most probably fix this:

`pip install --force-reinstall charset-normalizer==3.1.0`

**Comment by ljmatan** [comment]
> Updating to the latest version will most probably fix this:

Didn't help.

What helped was looking at the error messages which suggested I should do:

```
$ python3
```

```
import ssl
import ntlk

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context
nltk.download('punkt')

nltk.download('averaged_perceptron_tagger')
```
