### ISSUE TITLE
Installation with Docker image and Windows 11 is very slow

### ISSUE THREAD

**Issue by paulusTecnion** [PromtEngineer/localGPT#830]
![image](https://github.com/user-attachments/assets/f79b4c89-f30f-4346-b585-2a1558764215)

I'm already busy for almost 24 hours! Why is this taking so long? Anything I can do about it?

**Comment by paulusTecnion** [comment]
Now it stopped with this message:

62384.4      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 KB 2.1 MB/s eta 0:00:00
68492.9   Downloading requests-2.28.2-py3-none-any.whl (62 kB)
68492.9      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 4.7 MB/s eta 0:00:00
69246.9 ERROR: Exception:
69246.9 Traceback (most recent call last):
69246.9   File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
69246.9     status = run_func(*args)
69246.9   File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
69246.9     return func(self, options, args)
69246.9   File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 339, in run
69246.9     requirement_set = resolver.resolve(
69246.9   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
69246.9     result = self._result = resolver.resolve(
69246.9   File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
69246.9     state = resolution.resolve(requirements, max_rounds=max_rounds)
69246.9   File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 392, in resolve
69246.9     raise ResolutionTooDeep(max_rounds)
69246.9 pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000

**Comment by LoneDev6** [comment]
Same issue

**Comment by ErnestMolner** [comment]
@paulusTecnion @LoneDev6 
The problem is that it's looking for version compatibility. It looks like to me like that is the main time consumer.
![slow](https://github.com/user-attachments/assets/c110de2e-d896-48ee-baf5-4292b13e3b21)
I'm still not done with my first install, so I'm not sure. But one possible simple solution that I'm thinking about is once you have installed it, assuming that you wanna install again in a similar environment would be to generate a new, more specific requirements.txt
`pip freeze > requirements.txt`

**Comment by TinoCoda** [comment]
I was not on docker but I also face the same problem of a very slow package installation, when I ran `pip install -r requirements.txt`

**Comment by cattycnir** [comment]
I meet the same slow issue and found the workaround (modify the `Dockerfile` and add `--use-deprecated=legacy-resolver` option for `pip install`).

- Dockerfile, line 12 (original)
`RUN --mount=type=cache,target=/root/.cache CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install --timeout 100 -r requirements.txt llama-cpp-python==0.1.83`

- Dockerfile, line 12 (fixed)
`RUN --mount=type=cache,target=/root/.cache CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install --use-deprecated=legacy-resolver --timeout 100 -r requirements.txt llama-cpp-python==0.1.83`
