### ISSUE TITLE
 python run_localGPT.py --device-type=cpu crashing shell. no warnings!

### ISSUE THREAD

**Issue by Free-Radical** [PromtEngineer/localGPT#97]
as subject says,  whether device_type flag used or not.

```
$ python run_localGPT.py --device_type=cpu
Running on: cpu
load INSTRUCTOR_Transformer
max_seq_length  512
Using embedded DuckDB with persistence: data will be stored in: /home/khan/Documents/Github/localGPT/DB
```

terminal window/shell crashes NO WARNINGS  NOTHING!

**Comment by zhangweimtan** [comment]
am working fine as: python run_localGPT.py --device_type=cpu

if running python run_localGPT.py --device_type=cuda crashed as 
Traceback (most recent call last):
  File "E:\localGPT-main2\localGPT-main\run_localGPT.py", line 256, in <module>
    main()
  File "C:\Users\zhang\miniconda3\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\zhang\miniconda3\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\zhang\miniconda3\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\zhang\miniconda3\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "E:\localGPT-main2\localGPT-main\run_localGPT.py", line 225, in main
    llm = load_model(device_type, model_id=model_id, model_basename=model_basename)
  File "E:\localGPT-main2\localGPT-main\run_localGPT.py", line 70, in load_model
    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)
  File "C:\Users\zhang\miniconda3\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 720, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "C:\Users\zhang\miniconda3\lib\site-packages\transformers\tokenization_utils_base.py", line 1825, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'TheBloke/Llama-2-7B-Chat-GGML'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'TheBloke/Llama-2-7B-Chat-GGML' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.
2023-07-28 14:06:24,941 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: E:\localGPT-main2\localGPT-main/DB
